### ISSUE TITLE
Assert the date field format and not its content (Regex match)

### ISSUE THREAD

**Issue by authorjapps** [authorjapps/zerocode#101]
Charaan @Charaan_twitter wrote-
how do I assert for date field format and not its content ?

> "r_creation_date" : "2018-06-26T04:11:12.000+00:00"

**Comment by nirmalchandra** [comment]
@authorjapps , i have implemented this now, branch is
> `ISSUE-101_regex_match`

**Comment by nirmalchandra** [comment]
thanks. PR #102 merged.

**Comment by nirmalchandra** [comment]
Feature available in the released version below-
```
<dependency>
    <groupId>org.jsmart</groupId>
    <artifactId>zerocode-rest-bdd</artifactId>
    <version>1.2.4</version>
</dependency>
```
+ Check in the [release tab](https://github.com/authorjapps/zerocode/releases) to learn `what's new`.
