### ISSUE TITLE
Clarification on using properties file

### ISSUE THREAD

**Issue by Pulsar1224** [authorjapps/zerocode#106]
Few clarifications needed on how to use the properties file -
1. Is "restful.application.endpoint" a syntax to be used across all the properties files ?
2. If I need to use only one key/value pair in the endpoint.host in the properties file. Is this allowed?
3. For example I need to define and use only the endpoint.host and not the endpoint.port ... Is this allowed?
4. Need more examples on how to use the properties files and all the parameters that can used.

**Comment by aghorpade** [comment]
@Pulsar1224   - PFB inline comments for questions
1. Is "restful.application.endpoint" a syntax to be used across all the properties files ? - _Yes, this is a key used in Zerocode framework to pickup host address_
2. If I need to use only one key/value pair in the endpoint.host in the properties file. Is this allowed? - we have pre-defined key which needs to have values e,g, 
restful.application.endpoint.host=
restful.application.endpoint.port=
3. For example I need to define and use only the endpoint.host and not the endpoint.port ... Is this allowed? nope
4. Need more examples on how to use the properties files and all the parameters that can used. - you can write you own java classes to pick up properties from env specifi property file. we will try to add few more examples

**Comment by authorjapps** [comment]
#### A point to note-


If you provide absolute url in the "url" field of the test-case instead of relative url, then Zerocode framework picks that and runs. That means it ignores the host and port mentioned in the properties file.
e.g.
```
{
    "scenarioName": "Invoke GitHub GET users and assert",
    "steps": [
        {
            "name": "get_user_details",
            "url": "https://api.github.com:443/users/octocat",
            "operation": "GET",
            "request": {
            },
            "assertions": {
                "status": 200,
                "body": {
                    "login" : "octocat",
                    "id" : 583231,
                    "type" : "User"
                }
            }
        }
    ]
}
```
When you run this via e.g.-
```
@TargetEnv("github_host.properties")
@RunWith(ZeroCodeUnitRunner.class)
public class JustHelloWorldTest {

    @Test
    @JsonTestCase("helloworld/hello_world_status_ok_assertions.json")
    public void testGet() throws Exception {
    }

}
```
Here `github_host.properties` host/port/context are ignored. Not _recommended_ for your **regression suite**, but useful when you want to quickly test something locally. 👍

**Comment by nirmalchandra** [comment]
@Pulsar1224 , I think your question is, if one of the key is empty, is that allowed?
> i.e. whether something like this is allowed or not?
```
restful.application.endpoint.host=https://api.github.com
restful.application.endpoint.port=
```
Answer is no.
You definitely should mention the port.
If you are not sure about the port, please put `80 for http` and `443 for https or TLS` connections.

Note-
These(80, 443) are conventions only for `http/https/tls`. But we/you should not assume -or- the Zerocode framework can not assume some port, the server is listening to. Hence you should always put a value against it.

**Comment by authorjapps** [comment]
There are very short videos available in `youtube` explaining the `properties` aspects and overall usage of the framework.
+ 2min+ covering basic use cases - [youtube link](https://www.youtube.com/watch?v=nSWq5SuyqxE&t=74s) (Content is good, sound quality is bit low)
+ 10min+ covering bit more details - [youtube link](https://www.youtube.com/watch?v=YCV1cqGt5e0&t=78s) (increase the speed to reduce to 7min types)
