### ISSUE TITLE
[Gitter harikachepuri04] - Example of multipart/form-data in zerocode

### ISSUE THREAD

**Issue by authorjapps** [authorjapps/zerocode#107]
TODO-
- Create a Spring end point which accepts `multipart/form-data`
- Write a `zerocode test` to assert that it has uploaded successfully.

**Comment by nirmalchandra** [comment]
@santhoshTpixler, yes, it is possible.
But. one of us will put an example soon. It should include both end-point and a test to verify. (In the mean time if you wanted a quick turn around, you can simply upload using Apache Http client's `import org.apache.http.entity.mime.MultipartEntityBuilder;`, `org.apache.commons.httpclient.methods.multipart.MultipartRequestEntity` and execute the step in Zerocode.). 

@aghorpade, can you please add an end point to the **spring-boot demo** project which accepts a multi-part form data and just log it to console, then returns `200/201` upon success?

**Comment by aghorpade** [comment]
@nirmalchandra - PR has been raised against spring boot demo project for file upload code

**Comment by nirmalchandra** [comment]
Thanks @aghorpade . [PR-3](https://github.com/authorjapps/spring-boot-integration-test/pull/3) and [PR-4](https://github.com/authorjapps/spring-boot-integration-test/pull/4) are pending review.
@santhoshTpixler, before merged, you can refer to [this test case](https://github.com/authorjapps/spring-boot-integration-test/blob/ISS-107_file_up/src/test/resources/integration_tests/upload_file/file_upload_test.json) in the mean time. 

In case you want to run it before the PRs are approved/merged, you need to clone/download [this repo](https://github.com/authorjapps/spring-boot-integration-test) and run locally (branch `ISS-107_file_up` and run the test `integrationtests.uploadfile.VerifyFileUpload.java`).

**Comment by santhoshTpixler** [comment]
@nirmalchandra Thank you for the example.

**Comment by harikachepuri04** [comment]
Hi,
I tried using the same test case for uploading a pdf file but i am getting  400 error code[E_INPUT_MESSAGE_NOT_READABLE]. Aren't we supposed to send parameters like content-type and Content-Disposition ..

**Comment by authorjapps** [comment]
@harikachepuri04, 
> name="content"; filename="abc.pdf"

This above is what the server expects. If you send the below, the upload will not work.

> name="file"; filename="abc.pdf"

Hence I have put the respective review comments to take care of this aspects **in the example PR**.

The test will look like **below** and it enables `one as well as more files` to upload to the server.
(Of course you can override this behaviour in your HttpClient to match your project requirement, that's the advantage of the Zerocode framwork).
- Example-1
```
{
    "scenarioName": "Upload a file to the server and assert success @@Harikachepuri04 And Santhoshkumar@@",
    "steps": [
        {
            "name": "upload_a_pdf_file",
            "url": "/api/abc-bank/upload",
            "operation": "POST",
            "request": {
                "headers": {
                    "content-type": "multipart/form-data"
                },
                "body": {
                    "files": ["file:project_files/my_zip_file.zip"]

                    // Comments -
                    // file: match this field name "file:<path>" to what your server expects
                    //    -- e.g. "file": "content:project_files/my_zip_file.zip"
                    //    -- e.g. "file": "binary:project_files/my_pdf_file.pdf"
                    //    -- e.g. "file": "file1:project_files/my_file.txt"
                    //    -- e.g. "file": "file2:project_files/my_zip_file.zip" etc
                    // and-
                    // "project_files/my_zip_file.zip": Allows 'test/resources' path or full absolute path
                }
            },
            "assertions": {
                "status": 200,
                "body": {
                    "message": "$CONTAINS.STRING:File uploaded successfully !"
                }
            }
        }
    ]
}

```

- Example-2
```
{
    "scenarioName": "Upload two files and send more key-value request params Santhoshkumar@@",
    "steps": [
        {
            "name": "upload_a_pdf_file",
            "url": "/api/abc-bank/upload/filesAndRequestParams",
            "operation": "POST",
            "request": {
                "headers": {
                    "content-type": "multipart/form-data"
                },
                "body": {
                    "files": ["file:project_files/my_zip_file.zip", "file2:project_files/pdf_file.pdf"],
                    "trainList" : "Jubilee, Central, Bakerloo",
                    "id" : "LONDON-TUBE-UNDERGROUND"
                    
                    // Comment-
                    // It uploads two files ".zip" and ".pdf" file
                    // Also sends two key-value param to server
                    // Server just prints these key-value(see in the server console)
                }
            },
            "assertions": {
                "status": 200,
                "body": {
                    "message": "$CONTAINS.STRING:File uploaded successfully !"
                }
            }
        }
    ]
}

```
- See below how to run the above examples(Nothing different, except the `@UseHttpClient`)?
```
@TargetEnv("application_host.properties")
@UseHttpClient(ProjectApacheHttpClient.class)  //<--- Implements Apache multipart upload api.
@RunWith(E2eJunitRunner.class)
public class VerifyFileUpload {

    @Test
    @JsonTestCase("integration_tests/upload_file/file_upload_test.json")
    public void test_uploadFile() throws Exception {
    }

    @Test
    @JsonTestCase("integration_tests/upload_file/file_upload_and_more_params_test.json")
    public void test_uploadFileAndPassMoreParams() throws Exception {
    }

}
```

`@UseHttpClient(ProjectApacheHttpClient.class)` - This client has the upload code(We will put this into **core framework** in the next major release), until then you can use as it is or modify it to match your project needs.
e.g. If you need a "`boundary`" you can pass as below-
```
               {
                    "files": ["file:project_files/my_zip_file.zip"],
                    "boundary" : "--1122-boundry-8980912-sadf098-werwer"
               }
```
Hope it helps !

Did you clone the `spring-boot demo` repo and tried to run? That will make lot things easy.
You can simply **change** the **server** **address** and run these tests(or a bit of amendment) against **your** deployed app.

**Comment by santhoshTpixler** [comment]
Finally, I have implemented a BasicHttpClient in order to fit my requirements. Thank you for providing such a useful piece of software. I was saved from reinventing the wheel.

**Comment by authorjapps** [comment]
@santhoshTpixler, glad to know that it helped you 👍 
We will put this into the core framework in the next major release, so that everyone gets this out of the box.
I will merge this PR now and close this issue.

**Comment by gobozov** [comment]
In my case I was need to send file along with json body.

What I have done:

1) Controller 
`@ResponseBody
    public ResponseEntity<TranslationResponse> createTranslationRequest(
            @RequestPart(value = "createTranslationRequest") @Parameter(name = "createTranslationRequest")  CreateTranslationRequest createTranslationRequest,
            @RequestPart @Valid List<MultipartFile> attachments) {`


2) Scenario
...
"request": {
        "headers": {
          "Content-Type": "multipart/form-data"
        },
        "body": {
          "createTranslationRequest": "{\"request\":{\"repoKey\":\"fiber\",\"locales\":[\"en_US\",\"fr_FR\"],\"requestItems\":[{\"key\":\"key1\"},{\"key\":\"key2\"}],\"description\":\"Some description\"}}",
          "files": []
        }
      },
...
3) Create local copy of org.jsmart.zerocode.core.httpclient.utils.FileUploadUtils and put it in project java files along with tests to let classloader pick it up
Change PLAIN_TEXT content type to application/json

line 61:  multipartEntityBuilder.addPart(entry.getKey(), new StringBody((String) entry.getValue(), APPLICATION_JSON));
