### ISSUE TITLE
Array SIZE to support relational operator expression

### ISSUE THREAD

**Issue by authorjapps** [authorjapps/zerocode#117]
@harikachepuri04 in gitter-
During the assertion of array size with greater-than/less-than i am getting ClassCastException .. Eg "array.SIZE":"$GT.2"

Ans-
Yes, understood, that's a defect. We will fix it in the coming release(v 1.2.7). Currently "array.SIZE" can assert only an integer value not any expression.

Support(desired):
+ $GT.1
+ $LT.3

Support(nice to have):
+ $EQ.2
+ $NOT.EQ.5

This is not really a bug, this was never implemented, hence was not supported in earlier versions.

**Comment by nirmalchandra** [comment]
Initial fix is parked in the branch - `ISS-117_SIZE_EXPR`.

**Comment by authorjapps** [comment]
Look at the class:
>Class: org.jsmart.zerocode.core.engine.preprocessor.ZeroCodeJsonTestProcesorImpl
Method: #createAssertersFrom

**Comment by authorjapps** [comment]
@aghorpade , can you put the PR link here please?

**Comment by aghorpade** [comment]
ISSUE-117 #Array Size supports expression
Closed by aghorpade about 15 hours ago

**Comment by authorjapps** [comment]
Version **1.2.7** has the changes.
```
<dependency>
  <groupId>org.jsmart</groupId>
  <artifactId>zerocode-rest-bdd</artifactId>
  <version>1.2.7</version>
</dependency>
```
