### ISSUE TITLE
Create Zerocode logo

### ISSUE THREAD

**Issue by authorjapps** [authorjapps/zerocode#120]
A meaningful logo needs to be created for Zerocode.
Please suggest with ideas

**Comment by aghorpade** [comment]
Are we looking with some specific attributes, e.g. height,width, color combination?

**Comment by authorjapps** [comment]
<img width="62" height="91" alt="screen shot 2018-08-16 at 8 29 21 am" src="https://user-images.githubusercontent.com/12598420/44622070-39f38480-a8a9-11e8-95bf-862e69aa3b51.png">

<img width="82" height="122" alt="screen shot 2018-08-16 at 8 29 21 am" src="https://user-images.githubusercontent.com/12598420/44622070-39f38480-a8a9-11e8-95bf-862e69aa3b51.png">


<img width="124" height="183" alt="screen shot 2018-08-16 at 8 29 21 am" src="https://user-images.githubusercontent.com/12598420/44622070-39f38480-a8a9-11e8-95bf-862e69aa3b51.png">

**Comment by authorjapps** [comment]
<img width="69"  height="85" alt="screen shot 2018-08-16 at 8 29 23 am" src="https://user-images.githubusercontent.com/12598420/44622262-1cc0b500-a8ad-11e8-818d-66d23626a0f3.png">

<img width="92"  height="113" alt="screen shot 2018-08-16 at 8 29 23 am" src="https://user-images.githubusercontent.com/12598420/44622262-1cc0b500-a8ad-11e8-818d-66d23626a0f3.png">

<img width="139"  height="170" alt="screen shot 2018-08-16 at 8 29 23 am" src="https://user-images.githubusercontent.com/12598420/44622262-1cc0b500-a8ad-11e8-818d-66d23626a0f3.png">

**Comment by authorjapps** [comment]
<img width="67"  height="80" alt="screen shot 2018-08-16 at 8 29 24 am" src="https://user-images.githubusercontent.com/12598420/44622577-fef64e80-a8b2-11e8-9916-4b0e4a505676.png"> 

<img width="89"  height="106" alt="screen shot 2018-08-16 at 8 29 24 am" src="https://user-images.githubusercontent.com/12598420/44622577-fef64e80-a8b2-11e8-9916-4b0e4a505676.png"> 

<img width="134"  height="160" alt="screen shot 2018-08-16 at 8 29 24 am" src="https://user-images.githubusercontent.com/12598420/44622577-fef64e80-a8b2-11e8-9916-4b0e4a505676.png">

**Comment by authorjapps** [comment]
<img width="67"  height="80" alt="screen shot 2018-08-16 at 8 29 24 am" src="https://user-images.githubusercontent.com/12598420/44622577-fef64e80-a8b2-11e8-9916-4b0e4a505676.png"> Zerocode TDD and BDD
===
Welcome to the new simple, convenient and efficient way to test your APIs.

<img width="61"  height="78" alt="screen shot 2018-08-16 at 8 29 22 am" src="https://user-images.githubusercontent.com/12598420/44622223-5b09a480-a8ac-11e8-8b26-09a1859e221c.png"> Zerocode TDD and BDD
===
Welcome to the new simple, convenient and efficient way to test your APIs.

<img width="62" height="91" alt="screen shot 2018-08-16 at 8 29 21 am" src="https://user-images.githubusercontent.com/12598420/44622070-39f38480-a8a9-11e8-95bf-862e69aa3b51.png"> Zerocode TDD and BDD
===
Welcome to the new simple, convenient and efficient way to test your APIs.

**Comment by aghorpade** [comment]
First one looks ok. If we can have this as gray colored filled n dark black color as border line .I guess it will give more attention

**Comment by mailtoach79** [comment]
Agree, First one with dark colour back ground should get more attention.. should be unique as compared to others..

**Comment by authorjapps** [comment]
Many Thanks @aghorpade, @mailtoach79.

PICKED THE LAST ONE.

**Comment by santhoshTpixler** [comment]
zerocode-TDD deserves still a better logo. Will find someone to get it done.

**Comment by authorjapps** [comment]
Appreciate If someone could help us on this please 🙏

**Comment by authorjapps** [comment]
@dineshvish is happy to help us with this. 
> Tagged him

@BeTheCodeWithYou fyi-

**Comment by dineshvish** [comment]
Sure, will work over the weekend is that works for you.

**Comment by dineshvish** [comment]
![55](https://user-images.githubusercontent.com/5185159/51432924-a038c500-1c05-11e9-8be2-dcb5c2a119e4.png)
![11](https://user-images.githubusercontent.com/5185159/51432925-a038c500-1c05-11e9-8946-1ecb00b5de3b.png)
![22](https://user-images.githubusercontent.com/5185159/51432926-a038c500-1c05-11e9-8e3f-f905c09697fc.png)
![33](https://user-images.githubusercontent.com/5185159/51432927-a038c500-1c05-11e9-8174-742ad8b5e34a.png)
![44](https://user-images.githubusercontent.com/5185159/51432928-a038c500-1c05-11e9-808f-72beaea97a51.png)

**Comment by dineshvish** [comment]
![1](https://user-images.githubusercontent.com/5185159/51432932-b181d180-1c05-11e9-8d7a-f9099fd81930.png)

**Comment by dineshvish** [comment]
![66](https://user-images.githubusercontent.com/5185159/51432943-04f41f80-1c06-11e9-9a51-6decd123a257.png)

**Comment by dineshvish** [comment]
Let me know your view , I can make the changes or create the new one.

**Comment by authorjapps** [comment]
Thanks mate for your time 🙏. The last ine looks better.

Simple Black and white would be even better.

This font looks very nice.
![image](https://user-images.githubusercontent.com/12598420/51433262-b151f800-1c3e-11e9-9fcb-99d36bbafb83.png)

This below is another idea with black n white. Can you draw something like this using your professional tool ?
![image](https://user-images.githubusercontent.com/12598420/51433243-51f3e800-1c3e-11e9-84ac-c67e720b9819.png)
(This image has rough edges, circles are not placed correctly. Appreciate if you could redraw this and improve 🙏 with a bit of professional finishing)

**Comment by dineshvish** [comment]
![1](https://user-images.githubusercontent.com/5185159/51443000-b350a100-1ca8-11e9-957b-1d759ce31988.jpg)
![Uploading 2.jpg…]()
![Uploading 3.jpg…]()
![Uploading 4.jpg…]()
![Uploading 5.jpg…]()
![Uploading 6.jpg…]()

**Comment by dineshvish** [comment]
![2](https://user-images.githubusercontent.com/5185159/51443102-a54f5000-1ca9-11e9-8ad6-63acea820024.jpg)

**Comment by dineshvish** [comment]
![3](https://user-images.githubusercontent.com/5185159/51443104-ac765e00-1ca9-11e9-8df7-279ff180adb9.jpg)

**Comment by dineshvish** [comment]
![4](https://user-images.githubusercontent.com/5185159/51443108-b0a27b80-1ca9-11e9-9708-d510d4f2051c.jpg)

**Comment by dineshvish** [comment]
![5](https://user-images.githubusercontent.com/5185159/51443115-c021c480-1ca9-11e9-87d6-043d9974f201.jpg)

**Comment by dineshvish** [comment]
![6](https://user-images.githubusercontent.com/5185159/51443117-c3b54b80-1ca9-11e9-8d9a-fa168d0106a1.jpg)

**Comment by dineshvish** [comment]
![1](https://user-images.githubusercontent.com/5185159/51443129-da5ba280-1ca9-11e9-86ba-2cb9c9bc7b5b.jpg)

**Comment by BeTheCodeWithYou** [comment]
Fantastic work Dinesh. Appreciate your time.

Let's wait for feedabck and suggestions from everyone.

Just like the logo ...more likes for a logo goes to final round :-)

**Comment by authorjapps** [comment]
Just checking how the reduced size looks like-

<img height="200" width="200" alt="logo2" src="https://user-images.githubusercontent.com/5185159/51443117-c3b54b80-1ca9-11e9-8d9a-fa168d0106a1.jpg">

## Looks awesome actually. 🐼 

Couple of suggessions.
- The curly JSON braces(brackets) looks bit tall. Can you reduce(only the height) a bit?
- The size of the "zero" if reduced a bit might look more elegant. 
- _Outer circle looks perfect. Don't change anything please._

Let's see how it looks. When u get chance please. No hurry 🙏

**Comment by authorjapps** [comment]
@dineshvish, We are almost close to the final one, almost getting there.

Can you please place the dots properly with correct gap and in a straight line? It's somehow not aligned correctly. When u get chance please 👍 

Reduced size:
<img height="250" width="250" alt="logo2" src="https://user-images.githubusercontent.com/12598420/51566561-bdcb9000-1e8c-11e9-82cf-47a273dce0ab.jpg">

Original size:
<img height="600" width="600" alt="logolarge" src="https://user-images.githubusercontent.com/12598420/51566561-bdcb9000-1e8c-11e9-82cf-47a273dce0ab.jpg">

**Comment by santhoshTpixler** [comment]
I would suggest having a look at the following projects
https://github.com/thelounge/thelounge
https://github.com/teles/array-mixer
https://github.com/sindresorhus/pageres
https://github.com/sr6033/lterm

**Comment by santhoshTpixler** [comment]
If colors are introduced then I would recommend making use of pre-built color palette from sites like https://color.adobe.com/explore/?filter=most-popular&time=month

Using the pre-composed color palette will give the more elegant look. Or else a custom pallet has to composed.

**Comment by dineshvish** [comment]
With KAFKA text
![final_dotted_kafka_colored](https://user-images.githubusercontent.com/5185159/51633864-4a6f6000-1f18-11e9-85d7-e3ddc4fedbea.jpg)

**Comment by dineshvish** [comment]
with little bit shade
![final_dotted_kafka_colored_shade](https://user-images.githubusercontent.com/5185159/51634026-be116d00-1f18-11e9-9970-7b428077176c.jpg)

**Comment by aghorpade** [comment]
Looks good.Would like to suggest that do not add any text as this library is going to support multiple features n not only Kafka.
Do you feel that zero inside zero is not giving that professional look. What do you say

**Comment by authorjapps** [comment]
@aghorpade , understood your point of view. Good point actually.
If we remove the outer circle, it looks like below which is actually meaningful and even simpler.
![image](https://user-images.githubusercontent.com/12598420/51644373-d78dd580-1f67-11e9-8f41-495fd6048e1d.png)

And if we move the three dots to the peak, it looks like below,
![image](https://user-images.githubusercontent.com/12598420/51644440-191e8080-1f68-11e9-9145-f5fda6a911ec.png)

and the reduced size looks like below,
<img height="150" width="150" alt="logo2" src="https://user-images.githubusercontent.com/12598420/51644373-d78dd580-1f67-11e9-8f41-495fd6048e1d.png">

<img height="150" width="150" alt="logo2" src="https://user-images.githubusercontent.com/12598420/51644440-191e8080-1f68-11e9-9145-f5fda6a911ec.png">

**Comment by aghorpade** [comment]
I guess we are getting influenced by logo of swagger. We should do a rethink on it. Swagger looks similar to above options.

**Comment by authorjapps** [comment]
I don't think so. Nowhere even close by that. This is completely different I think. 

But yes, good point to keep in mind, by mistake we end of designing their logo 😄 

<img width="748" alt="screen shot 2019-01-24 at 12 32 39 am" src="https://user-images.githubusercontent.com/12598420/51646263-c47f0380-1f6f-11e9-93fb-f9bc1ad353bd.png">

Another one,
<img width="977" alt="screen shot 2019-01-24 at 12 32 51 am" src="https://user-images.githubusercontent.com/12598420/51646265-c779f400-1f6f-11e9-8e0d-ad4d2b1b4ba8.png">

**Comment by authorjapps** [comment]
After Amit's comment(becoming close to Swagger), I was thinking something like below image(needs to be drawn correctly)
![image](https://user-images.githubusercontent.com/12598420/51671071-08015e00-1fc0-11e9-8293-4e4904c3f8ca.png)

Reduced size look-
<img height="150" width="150" alt="logo2" src="https://user-images.githubusercontent.com/12598420/51671071-08015e00-1fc0-11e9-8293-4e4904c3f8ca.png">

> But the lines, bars etc to br drawn in correct proportion, this is just a rough sketch. Does it appear any good?

> Basicaly is the theme looking better?

**Comment by BeTheCodeWithYou** [comment]
@authorjapps  @aghorpade  Nice suggestions.
I was also thinking if we can design something like multiple zeros connecting to each other in curly braces pattern. Representing API's talking to each other with zero code.

@dineshvish  could you draw something on similar thought?

**Comment by BeTheCodeWithYou** [comment]
@dineshvish  this Z one looks super. Simple and elegant.  Great visual impression "Z char with 0 injected over the curly braces"
Fantastic @dineshvish

**Comment by dineshvish** [comment]
another with Z and zero
![z0](https://user-images.githubusercontent.com/5185159/51790097-93acf300-2156-11e9-80f0-01854e896ad3.jpg)

**Comment by dineshvish** [comment]
![4](https://user-images.githubusercontent.com/5185159/51791406-096d8a80-2168-11e9-8963-36b79751a8d5.jpg)

**Comment by authorjapps** [comment]
I liked the idea of Z and 0 👍 . The curly braces are bit better in the below.
![zero_mind4](https://user-images.githubusercontent.com/12598420/51798410-6a996a80-2209-11e9-8b67-738d5ec20bbf.png)

**Comment by dineshvish** [comment]
Here you go
![final_z0](https://user-images.githubusercontent.com/5185159/51806039-879a6180-223a-11e9-96e5-d222367b46a8.jpg)

**Comment by dineshvish** [comment]
Final width matches with the Z
![zerocodelogo](https://user-images.githubusercontent.com/5185159/51950763-63d04a80-23f7-11e9-892e-40f77adff8f2.jpg)

**Comment by dineshvish** [comment]
Final width matches with the Z

![zerocodelogo](https://user-images.githubusercontent.com/5185159/51950812-9ed27e00-23f7-11e9-8897-ce84cc018ec6.jpg)

**Comment by dineshvish** [comment]
Final width matches with the Z
![zerocodelogo](https://user-images.githubusercontent.com/5185159/51950853-d04b4980-23f7-11e9-9748-6aafe4f4cd2e.jpg)

**Comment by santhoshTpixler** [comment]
@dinesh76in  Good job. Neat and clean logo

**Comment by aghorpade** [comment]
Thanks @dinesh76in

**Comment by nirmalchandra** [comment]
Super Job @dineshvish !
Everyone like the logo due to its simplicity and neat looking. Great art 🙏

**Comment by dineshvish** [comment]
Thanks guys

**Comment by authorjapps** [comment]
@dineshvish , you have been added as a collaborator.
Please accept the invitation link here: https://github.com/authorjapps/zerocode/invitations
👍
