### ISSUE TITLE
Set up a twitter handle

### ISSUE THREAD

**Issue by authorjapps** [authorjapps/zerocode#123]
A twitter handle to be setup to publish new releases, features, bug fixes etc.

**Comment by aghorpade** [comment]
https://github.com/authorjapps/zerocode/pull/124 
please review it. we have zerocode official Twitter account  (https://twitter.com/ZeroCod55231349)

**Comment by aghorpade** [comment]
I will suggest below username for twitter account
1. zerocode4API
2. zerocode4APITesting
3. RESTInZeroCode
4. APITestWithZeroCode
5. TDDwithZeroCode

**Comment by mailtoach79** [comment]
ZerocodeEasyTDD
