### ISSUE TITLE
Create the Gradle versions of the quick-start repos

### ISSUE THREAD

**Issue by authorjapps** [authorjapps/zerocode#127]
This will be helpful for people using `gradle` to directly close and set up their IDEs.

**Comment by authorjapps** [comment]
#### High level Steps:

Simply add the necessary `gradle` file(s) to the root folder(same level as `POM.xml`). That's it
Let me explain the steps below, if it helps-
1. Fork the hello-world git repo `https://github.com/authorjapps/zerocode-hello-world.git`. That means, once you forked, you get this linked to your GitHub account.
1. Then clone this to your local disk and import/setup at your IDE(e.g. IntelliJ or Eclipse)
1. For sanity(optional step), do `mvn clean install -DskipTests` at the root folder(same level as POM)
1. Now add the necessary gradle file(s) to achieve the same as the above step what the `POM` does. That means, in the gradle file, add the necessary dependencies. You should/needto add exactly the same dependencies as of the POM.xml.
1. Then `compile/build/run` using gradle commands. It should work
1. That's it. Job done. _(No source code change is needed)_
1. Raise a PR against us and we will approve and merge to master.

**Comment by umangsingh123** [comment]
Hi ,
I have completed the task . Could have a quick look and see this is what is required.

**Comment by authorjapps** [comment]
PR approved n merged. Thanks @umangsingh123 👍
