### ISSUE TITLE
WireMock mocking repo via JUnit runners via IDE

### ISSUE THREAD

**Issue by officiallysameer** [authorjapps/zerocode#130]
Advantages-
+ Mock server will be running at a host or at local host i.e. a configurable host
+ Developer/Tester can add/remove/amend end point to it while the server is running

GIVEN- The interfacing end points (REST or SOAP)
WHEN- I start/run the MockMaker from my IDE
THEN- I will have the end point ready

GIVEN- The interfacing end points (REST or SOAP)
WHEN- I amend the end point and start/run the MockMaker from my IDE
THEN- I will have the new amended end point ready

GIVEN- The interfacing end points (REST or SOAP)
WHEN- I add a new end point and start/run the MockMaker from my IDE
THEN- I will have the new  end point ready along with old end point without stopping the WireMock server

GIVEN- The interfacing end points (REST or SOAP)
WHEN- I clean/delete/stop the end points via MockMaker runner
THEN- I will have no end points in the WireMock server

**Comment by authorjapps** [comment]
Couple of things we can set as objectives are follows:
+ In src/main/java
   + LocalHostMockMaker.java - This should bringup WireMock locally n mock the end points
   + DockerMockMaker.java - No need to bring up WireMock - Point to docker host/port
   + PcfMockMaker.java - No need to bringup WireMock - Point to the host/port
   + AwsMockMaker.java - No need to bringup WireMock - Point to the host/port

+ In src/test/java
   + LocalHostMockMakerTest.java - This should fire n assert to see mock has been set up
   + DockerMockMakerTest.java - This should fire n assert to see mock has been set up
   + PcfMockMakerTest.java - This should fire n assert to see mock has been set up
   + AwsMockMakerTest.java - This should fire n assert to see mock has been set up

**Comment by authorjapps** [comment]
Thanks everyone for participating. 👍 

This has been done. Examples has been added for REST(Get, Post, Put), SOAP services.

See this repo(clone or download) >> https://github.com/authorjapps/api-mock-maker

In a nutshell:

![wiremock_gif](https://user-images.githubusercontent.com/12598420/48665661-96ca9980-eaaa-11e8-82a8-064076825e2c.gif)
