### ISSUE TITLE
endpoint.port Injection validation not needed(make it optional)

### ISSUE THREAD

**Issue by dinesh76in** [authorjapps/zerocode#131]
GIVEN- the host properties without the `restful.application.endpoint.port`
WHEN- I fire the tests
THEN- framework should leave the port resolvance to the system or application 

**Explainations**
+ When there is http >> it's usually port 80(can be overriden by the same key)
+ When there is https >> it is usually 443(can be overriden by the same key)

But these values can be overwritten anyways. 
Hence leaving them empty should be allowed by the library.

This is not a super urgent, but nice to have feature.

**Comment by cooljavadev** [comment]
@authorjapps  @dinesh76in  - pull request has been raised - https://github.com/authorjapps/zerocode/pull/155 ,
NOw, restful.application.endpoint.port or web.application.endpoint.port field is optional, you can override in case of custom port number

**Comment by authorjapps** [comment]
https://github.com/authorjapps/zerocode/issues/159 has the fix in PR https://github.com/authorjapps/zerocode/pull/160
