### ISSUE TITLE
Extracting values from data base for assertions

### ISSUE THREAD

**Issue by Pulsar1224** [authorjapps/zerocode#132]
Hi Team,
Can you kindly pass me pointers on how to --
Connect to a remote sqlDB 
Query and assert responses from data base.
I am sure this is possible, but I am not able to figure it out how its done in this framework.

**Comment by aghorpade** [comment]
If an User-Journey scenario needs Oracle or PostGres DB sql execution and assertion during a REST API testing or an other Java method calls- It's quick n easy

Link:
https://github.com/authorjapps/zerocode#calling-java-methodsapis-for-doing-specific-tasks

**Comment by Pulsar1224** [comment]
Thank you very much sir ...
