### ISSUE TITLE
Instead of restful use web or http

### ISSUE THREAD

**Issue by dinesh76in** [authorjapps/zerocode#133]
e.g.
```
http.application.endpoint.host=http://localhost
http.application.endpoint.port=8888
http.application.endpoint.context=

-or-
web.application.endpoint.host=http://localhost
web.application.endpoint.port=8888
web.application.endpoint.context=
```
Currently it exists this way(np, but above way looks better)
```
restful.application.endpoint.host=http://localhost
restful.application.endpoint.port=8888
restful.application.endpoint.context=
```

**Comment by cooljavadev** [comment]
web.application.endpoint.host=http://localhost
web.application.endpoint.port=8888
web.application.endpoint.context=
this looks better as endpoint could be of restful service or soap service.
@dinesh76in  - what do you think?

**Comment by authorjapps** [comment]
Yeah, `web` sounds better and meaningful.
Can you pick this ticket n implement it?

I can give you some pointers if you need.
Looks like it affects just one class where the properties are injected.
But relevant tests can be `find/replace` fixed. 👍

**Comment by authorjapps** [comment]
PR https://github.com/authorjapps/zerocode/pull/140 raised by @cooljavadev 
- Under review

**Comment by authorjapps** [comment]
Pull Request https://github.com/authorjapps/zerocode/pull/140 has been merged now.
- Readme updated 👍 
- HelloWorld repo update - Pending
