### ISSUE TITLE
RAML file test case generation

### ISSUE THREAD

**Issue by dinesh76in** [authorjapps/zerocode#134]
Use RAML file to generate zerocode test cases. Just _Right Click -> Generate_ should be good enough.

But we love Given/When/Then :-) -
GIVEN a RAML file,
WHEN I run my test generation code
THEN I will have zerocode tests in my target folder.

Just _discuss or vote_ if this is useful or not before implementing it.
It's another NTH(nice to have feature) by it's category

**Comment by authorjapps** [comment]
This is being solved in #195 (OpenApi support).
No separate RAML support is needed.
