### ISSUE TITLE
[Check]- Showing tests run count 0 if if there is no http connection via PackageRunner

### ISSUE THREAD

**Issue by rppavan** [authorjapps/zerocode#136]
When connection timeout happens(service is not up) with _ZeroCodePackageRunner_ and _TestPackageRoot_ to run test cases from a resource directory the test doesn't fail instead it doesn't count the test case at all.
I'm seeing this message "{Oops! Not decided. Possibly due to non JSON content was encountered. See log for details}" with this result
[INFO] Results:
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

And here is the report from the logs
`{"timeStamp":"2018-10-11T20:53:52.045","results":[{"scenarioName":"workflow_life_cyle","steps":[{"name":"create_workflow","url":"http://localhost:9990/today-app/api/echo","correlationId":"645eee76-22f5-42d4-ab33-4ff0dc3e22ff","operation":"GET","requestTimeStamp":"2018-10-11T20:53:52.064","responseTimeStamp":"2018-10-11T20:53:52.398","responseDelay":334.0,"result":"FAILED","loop":0}],"loop":0}]}`

But when I run the testcase separately with @Test annotation it is failing as expected.

**Comment by albertosipov** [comment]
Hello @rppavan , You can put this kind of queries into gitter, you will get a quick response there.
Gitter link : https://gitter.im/zerocode-testing/help-and-usage

**Which version of the lib are you using?**

Coming back to the issue(please clone this helloworld n try yourself)-
- I just tried this in the cloned `zerocode-hello-world` project 
(The numbers look good, it wasn't `Tests run: 0, Failures: 0, Errors: 0, Skipped: 0`)

```
@TargetEnv("github_host.properties")
@RunWith(ZeroCodePackageRunner.class)
@TestPackageRoot("helloworld_github_REST_api") //<--- Root of the package to pick all tests including sub-folders
public class HelloWorldGitHubSuite {
}
```
> Note-
"helloworld_github_REST_api" folder has only 2 test cases
> - GitHub_REST_api_more_assertions.json
> - GitHub_REST_api_sample_assertions.json

and modified the the host/port to match yours,
```
# Web Server host and port
restful.application.endpoint.host=http://localhost
restful.application.endpoint.port=9990
restful.application.endpoint.context=
```

Then ran the suite by using below in the project root `zerocode-hello-world` folder,
> mvn clean test

what I saw is as follows-
```
2018-10-11 22:23:26,531 [main] INFO  org.jsmart.zerocode.core.engine.listener.ZeroCodeTestReportListener - ### ZeroCode: Test run completed for this runner. Generating test reports and charts. More help and examples are available at the README in GitHub
2018-10-11 22:23:26,643 [main] INFO  org.jsmart.zerocode.core.domain.builders.ExtentReportsFactory - Where were the tests fired? Ans: OS:Mac OS X, Architecture:x86_64, Java:1.8.0_60

Results :

Tests in error: 
  HelloWorldGitHubSuite.GitHub Version-Details REST API will GET, version and server details @@Emma » Runtime
  HelloWorldGitHubSuite.GitHub Version-Details REST API will GET, version, server details and more @@Alex » Runtime

Tests run: 2, Failures: 0, Errors: 2, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.971 s
[INFO] Finished at: 2018-10-11T22:23:27+01:00
[INFO] Final Memory: 23M/306M
[INFO] ------------------------------------------------------------------------
[
```
Also the target folder has the generated reports like below-

- Actual report files-
![reports](https://user-images.githubusercontent.com/36400587/46835660-cc42df80-cda6-11e8-8373-e8127e8c26c4.png)

- CSV report
<img width="1230" alt="csv-repor" src="https://user-images.githubusercontent.com/36400587/46835648-bf25f080-cda6-11e8-8bb6-aad2b4a5cefa.png">

- HTML report
<img width="1228" alt="html-report" src="https://user-images.githubusercontent.com/36400587/46835678-d5cc4780-cda6-11e8-8ab3-31617627a0b6.png">

**Comment by nirmalchandra** [comment]
@rppavan , there is no enough information you have provided, to understand the issue or reproduce the issue.
Please provide details what exactly you are trying to do with full details e.g. steps, logs etc, then someone in the forum will be happy to help you out.

**Comment by authorjapps** [comment]
Hello @rppavan, Basically we are doing a detective job here to figure out what's the issue.

We are helpless if we do not have enough details to reproduce the same.
Can you please provide details in terms of `logs` or `configurations`, to be able to come to the bottom of this issue?
How will we able to reproduce the issue if you provide bits n pieces of details, now n then?

Now you have revealed that you used `maven-failsafe-plugin` where you have hit with this issue ! Fair enough, what are you trying to achieve ?

> I'm using 'maven-failsafe-plugin' to run integration tests.

Are you doing an in-memory integration test from the same code base as production?

Still we are not sure what you want to achieve by using `maven-failsafe-plugin`. 

If you are running e2e type of tests you can simply bring up a test-suite n run it (unless you want to achieve something else locally via `failsafe-plugin`).

Can you **cut a branch** out from the [HelloWorld repo](https://github.com/authorjapps/zerocode-hello-world) n put your `maven-failsafe-plugin` config into the `POM` n update this ticket when ready? 

That will help us a lot to dig further into the details.
> You can even fork and do it without cutting a branch out.

**Comment by nirmalchandra** [comment]
Also in the mean time can you have a look at this repo where `maven-fail-safe` is configured as below and works perfectly fine(_done by one of our contributors_):
- Repo [Link](https://github.com/authorjapps/spring-boot-integration-test)
- POM [link](https://github.com/authorjapps/spring-boot-integration-test/blob/master/pom.xml)
> You can clone this repo and run in your laptop for your satisfaction.
> Command >> mvn clean install

```
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-failsafe-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                        <configuration>
                            <includes>
                                <include>integrationtests.IntegrationTestSuite.java</include>
                            </includes>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```
Note-
There is no surefire here, that means surefire is `implicit` here, but you can choose to configure it however you like.
Here the `fail-safe` plugin is configured to run only the `Integration Tests`, not the `unit tests`.

Hope this helps !
