### ISSUE TITLE
ssl enabled host with certificate issue

### ISSUE THREAD

**Issue by officiallysameer** [authorjapps/zerocode#14]
e.g.
`
GET: https://somehost:443/api/customers
`
Sometime works for certain hosts.  
Other times it fails with following exception, might be due to the Certificate issue.

`Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
`

or

`Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
`

What is the way out ?

Can you create a new client or change the http client to accept the certificate?

**Comment by authorjapps** [comment]
@officiallysameer , can you contribute and fix it?
How to do it? Create a branch -> Push your fixes -> Raise a Pull Request -> Merge it once approved.

**Comment by officiallysameer** [comment]
Please add me to the repo(branch) with write access.

**Comment by authorjapps** [comment]
Issue closed. Please use the below dependency version-
<dependency>
    <groupId>org.jsmart</groupId>
    <artifactId>zerocode-rest-bdd</artifactId>
    <version>1.1.20</version>
</dependency>

Usage:
- See here(section 16) how to Use SSL HttpClient : Using @UseHttpClient
[@UseHttpClient(SslTrustHttpClient.class)](https://github.com/authorjapps/zerocode#16)
- Or See java code here:
[Java code with SSL Client](https://github.com/authorjapps/zerocode/blob/master/src/test/java/org/jsmart/zerocode/core/verification/SslTrustUseHttpClientTest.java)
