### ISSUE TITLE
Support Content type "application/x-www-form-urlencoded" with sending KeyValue params

### ISSUE THREAD

**Issue by arunvelusamyd** [authorjapps/zerocode#141]
Content type "application/x-www-form-urlencoded" is not supported. Request body is always considered as Json or Multipart.

My rest controlled looks something like below, 
```
@POST
@Consumes({"application/x-www-form-urlencoded"})
public Response handleRequest(MultivaluedMap<String, String> params) {
}
```

I tried using the below format. But it was failing. 
```
"request": {
  "headers": {
    "Content-Type": "application/x-www-form-urlencoded"
  },
  "body": {
    "Name": "Larry Pg",
    "Company": "Amazon",
    "Title": "CEO"
  }
}
```

Like to change the method createRequestBuilder of the class BasicHttpClient.

**Comment by arunvelusamyd** [comment]
@authorjapps Updated the description . Is this fine?

BasicHttpClient class has the below method
```
private RequestBuilder createRequestBuilder(String httpUrl, String methodName, Map<String, Object> headers, String reqBodyAsString) throws IOException {
    RequestBuilder requestBuilder;
    if (hasMultiPartHeader(headers)) {
        requestBuilder = createFileUploadRequestBuilder(httpUrl, methodName, reqBodyAsString);
    } else {
        requestBuilder = createDefaultRequestBuilder(httpUrl, methodName, reqBodyAsString);
    }
    return requestBuilder;
}
```

like to change the method to support for "application/x-www-form-urlencoded" as well. can we add a new method createFormUrlEncodedRequestBuilder and do the below change as well?

```
private RequestBuilder createRequestBuilder(String httpUrl, String methodName, Map<String, Object> headers, String reqBodyAsString) throws IOException {
    String contentType = headers != null? (String) headers.get(CONTENT_TYPE) :null;
    if(contentType!=null){
        if(contentType.equals(MULTIPART_FORM_DATA)){
            return createFileUploadRequestBuilder(httpUrl, methodName, reqBodyAsString);
        } else if(contentType.equals(APPLICATION_FORM_URL_ENCODED)) {
            return createFormUrlEncodedRequestBuilder(httpUrl, methodName, reqBodyAsString);
        }
    }
    return createDefaultRequestBuilder(httpUrl, methodName, reqBodyAsString);
}
```

**Comment by authorjapps** [comment]
@arunvelusamyd , Issue description looks much better now. Thanks 👍 
Still it looks like this has been take care already. If you pass `"Content-Type": "application/x-www-form-urlencoded"`, it will supersede the default one. 

@nirmalchandra @macrocks, @dinesh76in , do you remember? can u check this in the code `BasicHttpClient.java`?

@arunvelusamyd , have you tested this ?
The situation which you explained can be easily tested and the test shd pass. See the code below-
```java
        RequestBuilder requestBuilder = createRequestBuilder(httpUrl, methodName, headers, reqBodyAsString);

        // ------------------
        // Handle the headers
        // ------------------
        handleHeaders(headers, requestBuilder);

```
then the `handleHeaders` calls
> processFrameworkDefault(headers, requestBuilder);

This takes care of duplication and then supersedes the headers sent by user(tests here).
```java
                removeDuplicateHeaders(requestBuilder, (String) key);
                requestBuilder.addHeader((String) key, (String) headersMap.get(key));
                LOGGER.info("Overridden the header key:{}, with value:{}", key, headersMap.get(key));
```

@arunvelusamyd, Please expose an end point n test it, then if the problem still exists, you can pick this ticket n implement it. 👍 

For this TDD, you can use the below test case(which shd fail until you implement the end point):
```javaScript
{
    "scenarioName": "Check issue - request www-form headers @@arunvelusamyd",
    "steps": [
        {
            "name": "post_www_form_header",
            "url": "/api/v1/issues/arunv",
            "operation": "POST",
            "request": {
                "headers": {
                    "Content-Type": "application/x-www-form-urlencoded"
                },
                "body": {
                    "name": "Elon",
                    "age": 25,
                    "emailId": "emusk@tesla.com"
                }
            },
            "assertions": {
                "status": 201
            }
        },
        {
            "name": "check_json_header",
            "url": "/api/v1/issues/arunv",
            "operation": "POST",
            "request": {
                "headers": {
                    "Content-Type": "application/json"
                },
                "body": {
                    "name": "Elon",
                    "age": 25,
                    "emailId": "emusk@tesla.com"
                }
            },
            "assertions": {
                "status" : 415  //<----- 'application/json' not supported
            }
        }

    ]
}

```

**Comment by nirmalchandra** [comment]
Check this test @arunvelusamyd please in the [HelloWorld repo](https://github.com/authorjapps/spring-boot-integration-test). You can clone and run it locally. It passes 👍 . _(Used the above test case for the sake of TDD)._

Link:
https://github.com/authorjapps/spring-boot-integration-test/blob/master/src/test/resources/integration_tests/post/post_www_form_header_test.json

Look for the log in the `spring boot` console:
```java
    @PostMapping(value = "/api/v1/issues/arunv", consumes = {"application/x-www-form-urlencoded"})
    public ResponseEntity handleRequest( @RequestParam Map<String, String> params, @RequestHeader HttpHeaders httpHeaders) {

        LOGGER.info("Request params received - " + params);
        LOGGER.info("Request httpHeaders received - " + httpHeaders);

        return new ResponseEntity<>("{\"working\": \"Well\"}", HttpStatus.CREATED);
    }
```

Log in the `spring boot` console-
```
2018-10-22 18:54:33.318  INFO 52697 --- [nio-8080-exec-5] c.s.controller.CustomerController        : Request params received - {{"name":"Elon","age":25,"emailId":"emusk@tesla.com"}=}
2018-10-22 18:54:33.319  INFO 52697 --- [nio-8080-exec-5] c.s.controller.CustomerController        : Request httpHeaders received - {content-type=[application/x-www-form-urlencoded], content-length=[52], host=[localhost:8080], connection=[Keep-Alive], user-agent=[Apache-HttpClient/4.5.5 (Java/1.8.0_91)], accept-encoding=[gzip,deflate]}

```
Hope it clarifies !

**Comment by nirmalchandra** [comment]
_FYI only-_

The full log in the log file(`target/logs` or `IDE Test console` folder)
- Request
- Response
- Assertions

```java
2018-10-22 22:25:52,645 [main] INFO org.jsmart.zerocode.core.runner.ZeroCodeMultiStepsScenarioRunnerImpl - 
--------- BDD: Scenario:Check issue - request www-form headers @@arunvelusamyd -------

--------- TEST-STEP-CORRELATION-ID: 69707390-3bf1-437c-8a58-6498c14db7ad ---------
*requestTimeStamp:2018-10-22T22:25:52.658
step:post_www_form_header
url:http://localhost:8080/api/v1/issues/arunv
method:POST
request:
{
  "headers" : {
    "Content-Type" : "application/x-www-form-urlencoded"
  },
  "body" : {
    "name" : "Elon",
    "age" : 25,
    "emailId" : "emusk@tesla.com"
  }
} 
--------- TEST-STEP-CORRELATION-ID: 69707390-3bf1-437c-8a58-6498c14db7ad ---------
Response:
{
  "status" : 201,
  "headers" : {
    "Date" : [ "Mon, 22 Oct 2018 21:25:53 GMT" ],
    "Content-Length" : [ "19" ],
    "Content-Type" : [ "text/plain;charset=UTF-8" ]
  },
  "body" : {
    "working" : "Well"
  }
}
*responseTimeStamp:2018-10-22T22:25:53.207 
*Response delay:549.0 milli-secs 
---------> Assertion: <----------
{
  "status" : 201
} 
-done-


--------- TEST-STEP-CORRELATION-ID: 2f127f38-6db4-4f44-9fb8-94ad246c38e9 ---------
*requestTimeStamp:2018-10-22T22:25:53.213
step:check_json_header
url:http://localhost:8080/api/v1/issues/arunv
method:POST
request:
{
  "headers" : {
    "Content-Type" : "application/json"
  },
  "body" : {
    "name" : "Elon",
    "age" : 25,
    "emailId" : "emusk@tesla.com"
  }
} 
--------- TEST-STEP-CORRELATION-ID: 2f127f38-6db4-4f44-9fb8-94ad246c38e9 ---------
Response:
{
  "status" : 415,
  "headers" : {
    "Date" : [ "Mon, 22 Oct 2018 21:25:53 GMT" ],
    "Transfer-Encoding" : [ "chunked" ],
    "Content-Type" : [ "application/json;charset=UTF-8" ]
  },
  "body" : {
    "timestamp" : "2018-10-22T21:25:53.230+0000",
    "status" : 415,
    "error" : "Unsupported Media Type",
    "message" : "Content type 'application/json' not supported",
    "path" : "/api/v1/issues/arunv"
  }
}
*responseTimeStamp:2018-10-22T22:25:53.244 
*Response delay:31.0 milli-secs 
---------> Assertion: <----------
{
  "status" : 415,
  "body" : {
    "error" : "Unsupported Media Type",
    "message" : "Content type 'application/json' not supported"
  }
} 
-done-

**FINISHED executing all Steps for [Check issue - request www-form headers @@arunvelusamyd] **.

Steps were:[post_www_form_header, check_json_header]
```

**Comment by arunvelusamyd** [comment]
@authorjapps  , @nirmalchandra 

It just took the whole body as a key and value as empty string. Let's see the log printed again.

```
Request params received - {{"name":"Elon","age":25,"emailId":"emusk@tesla.com"}=}
Request httpHeaders received - {content-type=[application/x-www-form-urlencoded], content-length=[52], host=[localhost:8080], connection=[Keep-Alive], user-agent=[Apache-HttpClient/4.5.5 (Java/1.8.0_91)], accept-encoding=[gzip,deflate]}
```

**{{"name":"Elon","age":25,"emailId":"emusk@tesla.com"}=}**

Here, key is {"name":"Elon","age":25,"emailId":"emusk@tesla.com"} and value is empty string.
It should be printed like {name=Elon, emailId=emusk@tesla.com, age=25} where keys are name, age, emailId and their respective values are Elon, 25, emusk@tesla.com

**Comment by arunvelusamyd** [comment]
#145

**Comment by nirmalchandra** [comment]
@arunvelusamyd @authorjapps , I have only put the tests how framework does and how server side app behaves(we don't have control on the server side as we are only invoking it).
See this link:
https://stackoverflow.com/questions/40574892/how-to-send-post-request-with-x-www-form-urlencoded-body
<img width="600" alt="stackof" src="https://user-images.githubusercontent.com/15079710/47422034-abe92c80-d779-11e8-8972-797573651f9c.png">
(I am not saying `StackOF` is correct or we should not process the `body` as `key-value` or as `text`)
Currently this works the following way-
- From Zerocode test-
![debug_testcase](https://user-images.githubusercontent.com/15079710/47422226-10a48700-d77a-11e8-8545-f0b398c421e1.png)

- Spring REST controller(server)-
![debug_kv](https://user-images.githubusercontent.com/15079710/47422271-24e88400-d77a-11e8-9306-0e0dd934192b.png)

So let's implement what's correct as well as what is needed. 👍 

Let's keep this opened for few days for other collaborator's input.

**Comment by authorjapps** [comment]
Guys, It looks we are missing something here. (Point No.5 of [Issue Guidelines](https://github.com/authorjapps/zerocode/wiki/Guidelines-for-raising-issues))
> 5. Clearly capture into the story/ticket what is actual and what is expected result

**Not working** 👍 
+ What is expected ?
   + `Content-Type` with `application/x-www-form-urlencoded` with request body should be sent as Key-Value? But sent as `text` ? Expected: The serve should receive or interpret this as Key-Value pairs?

+ What is actual?
   + It is sent as Text from client(zerocode)? And the server reads as text?

**Working** 👍 
+ What is expected ?
   + `Content-Type` with `application/x-www-form-urlencoded` - when sent in the URL like query params, the server receives as Key-Value param

+ What is actual?
   + It is sent like query params from client(zerocode)? and the server reads as Key-Value params?

Folks, fyi. I will be updating the ticket description soon to be transparent to all-
@arunvelusamyd , @macrocks , @officiallysameer @dinesh76in

**Comment by cooljavadev** [comment]
we need to look at http 1.1 specification what is a standard specification for content-type.

**Comment by aghorpade** [comment]
I will look into standard specification for content-type and will come back to you all.

**Comment by arunvelusamyd** [comment]
I had all my endpoints configured in Postman. I came across this situation, when trying to move all of them to zerocode. 
![postman-zerocode-test](https://user-images.githubusercontent.com/21174506/47434752-cb15a780-d7d5-11e8-9b81-c8c915cb3963.jpeg)


FYI
In postman, Body is send as key-value pair. It's also accepting query params & received as key-value pair. If we do not want to consider body, that's ok. But it'll make some confusion. In my case, key is a simple text and value is a big json ( Ex : address={"unit-no":"12-07""block-number":"33""apartment":"Flamingo Valley","state/region":"singapore north""country":"singapore""pincode":"87654321"} ). It's too hard to keep them in the url.

Anyway, let's decide by others thought and specifications. Thanks.

**Comment by authorjapps** [comment]
That sounds correct. 👍 This will make everyone's life a lot easy now. 
Postman accepts both as `key-value` and combines them if both are present(shown below).

Folks, Let's go with **PR review n approval** please !

![postmna_body](https://user-images.githubusercontent.com/12598420/47440299-c507d280-d7a5-11e8-9f3b-9bc795d9ef14.png)

- Then in server app-
![postman_rq_rcvd](https://user-images.githubusercontent.com/12598420/47440323-d4871b80-d7a5-11e8-9541-13b40de73d90.png)

If **same key** is present, they server receives as multivalue(means client also sends as multi value) - see below:
- postman client
![postman_2vals](https://user-images.githubusercontent.com/12598420/47440865-f503a580-d7a6-11e8-9679-6565a6417463.png)

- spring boot server
![postman_2vals_server](https://user-images.githubusercontent.com/12598420/47440892-fe8d0d80-d7a6-11e8-844f-a81142fd60dd.png)

@arunvelusamyd , Good job mate ! Have you taken care of the above(_same key situation_) in your PR ? If not can you please take care now ? 👍 

@macrocks , @cooljavadev @nirmalchandra - Please review n approve -or- express your view points if disagree or think any other way  🙏

**Comment by authorjapps** [comment]
@arunvelusamyd, if the current PR helps you to unblock your work, then we can proceed, and you can fix the `same key situation` later as a `Tech-Debt`(which I will raise evenually).  That's fine. 👍 

I have another suggestion and observation here I think worth giving a thought:
- Postman disables the body and enables the text-boxes to pass Key-Value when we choose `application/x-www-form-urlencoded`. 
- That's correct way, becaz with the `x-www...` header the `Key-Value`s are sent to server as params and server(e.g. Spring Boot app) receives them as multi-value map. So far so good
- Zerocode already allows `queryParams` section as below which accepts KeyValue pairs and sent to server as params and is received as Map. (Also same here not as multi-value map)
```
...
            "request": {
                "queryParams":{
                    "id": 1,
                    "name": "Emma",
                    "page": 6
                }
            }
...
```
- This should help you to pass your `KeyValue`s 
- This doesn't support `encoding` characters e.g. `"state/region":"singapore north"`. Both are issues here ie the `/` as well as the space after `singapore`. We were about to raise an issue for this, but not got any scope yet.
- So my suggestion would be you can reuse your code(PR) to fix his bit which will solve both the problems i.e. a)You will be unblocked as well as,  b)the special-char( slash, space etc) also will be taken care in the queryParams.

How does it sound? Give a thought !

**Comment by authorjapps** [comment]
Folks, all concerns have been taken care now in the PR. Please have a look, review n approve-
Overall the below things has been take care n will be available once merged - 
- Request `body` can be passed as key-value pair for this `header` type - let's keep this feature as this is a natural choice for users (we can add into readme 👍 @arunvelusamyd )
- `queryParams` also now has been enhanced to take care of special chars - the similar logic from the PR has been implemented
- BasicHttpClient some methods are `public` **intentionally** as they are already in use in the corporates, where put their custom logic/headers/request-builder/corporate-prosy etc via `@UseHttpClient`. Just a note of caution _not to make it private_
- Better test coverage now for both `body` and `queryParams` handling
- HelloWorld project has been verified with `1.2.9-SNAPSHOT` build 👍 

I will keep it open for a day and merge it. If it is super urgent, let me know ! 

@officiallysameer @dinesh76in @macrocks @cooljavadev FYA please.

**Comment by authorjapps** [comment]
PR merged and the feature released. Release version [1.2.9](https://mvnrepository.com/artifact/org.jsmart/zerocode-rest-bdd/1.2.8):
```xml
<!-- https://mvnrepository.com/artifact/org.jsmart/zerocode-rest-bdd -->
<dependency>
    <groupId>org.jsmart</groupId>
    <artifactId>zerocode-rest-bdd</artifactId>
    <version>1.2.9</version>
</dependency>
```

**Comment by authorjapps** [comment]
Thank to all for your precious time 🙏

**Comment by nameisjayant** [comment]
remove the last "/" from the end point request.
