### ISSUE TITLE
Choosing the new Artefact name

### ISSUE THREAD

**Issue by authorjapps** [authorjapps/zerocode#149]
After Kafka stream testing release, we want to rename the `artefact` to one of the below:
+ `z-testing`
   + `z` means zerocode
+ `z-test`
+ `zerocode-testing`
+ `z-testing-tools`
+ `z-dsl`
+ `zerocode-dsl`
+ `zerocode-tdd`
+ `ztest-dsl`

or

Please suggest if anything better you might come up with. 🙏

Note-
+ We will **not** release a new artefact only for Kafka testing, because both REST and Stream testing goes on hand in hand as a defacto standard for every project who use BigData or Streaming. 
+ Projects using only REST(SOAP/DB) will not be affected by streams anyway as they will not use this feature.

**Comment by aghorpade** [comment]
Zerocode-tdd looks better as it gives more simple solution  for TDD approach.

**Comment by authorjapps** [comment]
First trial version release with Kafka.
```xml
<dependency>
	<artifactId>zerocode-tdd</artifactId>
	<groupId>org.jsmart</groupId>
	<version>1.2.18</version>
</dependency>
```
