### ISSUE TITLE
Create Kafka docker containers and dockerise CI build

### ISSUE THREAD

**Issue by nirmalchandra** [authorjapps/zerocode#151]
GIVEN the docker-compose file 
WHEN I configure the yaml file to spin up `confluent-kafka`
THEN I will have the docker container running exposing kafka streaming services
with configured zoo-keeper

Repeat the above for:
- Single Kafka bootstrap, single ZK - See this >> [issue](https://github.com/authorjapps/zerocode-docker-factory/issues/1) - __Done__.
- Multi Kafka bootstraps, single ZK
  - Kafka cluster
- Multi Kafka bootstraps, multi ZK
  - ZK cluster

Fit into the `Kafka HelloWorld repo` or create a new repo for this so that anyone interested only in this Kafka-Zk setup(not zerocode), can clone and use.
  - Also check if any existing multi node cluster `open source` project can be reused

**Comment by authorjapps** [comment]
CI build PR has been raise by @santhoshTpixler i.e. PR https://github.com/authorjapps/zerocode/pull/175

It does the following -
+ Pulls the compose yaml from our `docker-factory` repo
+ Spins up the single node Kafka container
+ Fires all the tests via `mvn install`

Good work 👍 , Clean and simple !
All collaborators should be unblocked now for the Kafka contribution via CI feedback.
But of course we have the comfort of running the tests against local docker container prior to pushing to git-repo.

**Comment by authorjapps** [comment]
PR has been merged now after CI was Green as below-

See build No. [#882](https://travis-ci.org/authorjapps/zerocode/builds/472663928) - Passed.


<img width="776" alt="docker-ci-green" src="https://user-images.githubusercontent.com/12598420/50483170-70214c00-09e2-11e9-8bb7-0c7410fc0583.png">

**Note(For everyone's reference only)-**
+ See the last two scripts which was implicit by Travis 👍 . So they have been removed from the actual YAML file.

```
services
0.02s$ sudo service docker start
start: Job is already running: docker
git.checkout
0.89s$ git clone --depth=50 --branch=ISS-151-Travis-kafka https://github.com/authorjapps/zerocode.git authorjapps/zerocode
Resolving deltas: 100% (1108/1108), done.
$ cd authorjapps/zerocode

before_install.1
0.16s$ wget https://raw.githubusercontent.com/authorjapps/zerocode-docker-factory/master/compose/kafka-single-node.yml

Saving to: ‘kafka-single-node.yml’
100%[======================================>] 1,631       --.-K/s   in 0s      
2018-12-27 14:09:20 (393 MB/s) - ‘kafka-single-node.yml’ saved [1631/1631]

before_install.2
$ docker-compose -f kafka-single-node.yml up -d


install
19.17s$ mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building ZeroCode REST BDD 1.2.17-SNAPSHOT
[INFO] ------------------------------------------------------------------------


146.55s$ mvn test -B
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building ZeroCode REST BDD 1.2.17-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
```
+ The Kafka tests were reactivated already by @santhoshTpixler and they were Green in the build.
