### ISSUE TITLE
[Doc] Update Kotlin usage with example [Wiki] 

### ISSUE THREAD

**Issue by authorjapps** [authorjapps/zerocode#156]
- Provide Kotlin usages
- An end to end github repo with Sprig boot example
- Point to Mr @BethecodeWithyou public repo with gradle example
- Also provide a maven example

**Comment by BeTheCodeWithYou** [comment]
@authorjapps  - updated  [SpringBoot Kotlin Repo](https://github.com/BeTheCodeWithYou/SpringBoot-Kotlin) with below changes
1) enabled maven support for spring boot kotlin
2) readme updated

**Comment by BeTheCodeWithYou** [comment]
@authorjapps   Wiki page for testing api in Kotlin is completed. 👍 

Please review and share comments.  If all looks ok, ticket can be closed. 👍  

https://github.com/authorjapps/zerocode/wiki/Testing-Kotlin-Application-using-Zerocode

**Comment by authorjapps** [comment]
Good one. Precise and nice! 👍
