### ISSUE TITLE
Scenarios / examples on database assertions would help

### ISSUE THREAD

**Issue by Pulsar1224** [authorjapps/zerocode#158]
Hi Team,

Can we have scenarios related to db connection, and db assertion examples on the https://github.com/authorjapps/zerocode page. This will help a majority of users to get idea on how to work on db assertions.

**Comment by authorjapps** [comment]
@Pulsar1224 ,  Yes, we should do it soon with an example of executing the tests against `PostGress` DB and/or a `MySql` **DB** as they are free and Open Sourced (Oracle is licensed).  Sorry to see that you didn't find an working example on the README file yet. We will put an example soon and thanks for your patience. 🙏
The idea is to either to spin up some RDS instances on `AWS` and grant you access, as well as a `local docker`. Whichever helps you or quicker, we will sort that out soon.

In the mean time, please have a look at this code, which might also help you or unblock you-
```javaScript
{
    "scenarioName": "Execute DB SQL and assert rows as simple JSON array",
    "steps": [
        {
            "name": "execute_db_sql",
            "url": "org.jsmart.zerocode.zerocodejavaexec.DbSqlExecutor",
            "operation": "fetchDbCustomers",
            "request": "select id, name from customers",
            "assertions": {
                "results": [
                    {
                        "id": 1,
                        "name": "Elon Musk"
                    },
                    {
                        "id": 2,
                        "name": "Jeff Bezos"
                    }
                ]
            }
        }
    ]
}
```
Here is the sample for
+ [The JSON step](https://github.com/authorjapps/zerocode-hello-world/blob/master/src/test/resources/helloworldjavaexec/hello_world_java_method_return_assertions.json)
+ [my_web_app.properties](https://github.com/authorjapps/zerocode-hello-world/blob/master/src/test/resources/my_web_app.properties
) 
+ [DbSqlExecutor.java](https://github.com/authorjapps/zerocode-hello-world/blob/master/src/main/java/org/jsmart/zerocode/zerocodejavaexec/DbSqlExecutor.java) 

FYI-
Though, we have executed hundreds of TCs against Oracle DB inside our various Banking projects, we never had any need to spin up a local oracle server instance. Now _sounds like it's helpful to put an sample on the README_

**Comment by BeTheCodeWithYou** [comment]
@Pulsar1224 will take a look and share details once ready.  Cheers!

**Comment by BeTheCodeWithYou** [comment]
@Pulsar1224 , Please refer to sample java code for DB SQL executions and test scenario.

Clone the repo and run test as described below
https://github.com/BeTheCodeWithYou/SpringBoot-ZeroCode-Integration

**Running Integration TestCase which has DBExecutor example**
`mvn -Dtest=TestGetOperations test`

**Running the entire Integration test suite**
`mvn -Dtest=IntegrationTestSuite test`

**Please refer DB Executor example code here**
https://github.com/BeTheCodeWithYou/SpringBoot-ZeroCode-Integration/blob/master/src/main/java/com/xp/springboot/respository/DBSqlExecutor.java

please see quick reference here

```
public List<ParkRunner> executeSimpleSql(String simpleSql) throws  IllegalAccessException, InvocationTargetException, InstantiationException {
		
		LOGGER.info("DBSqlExecutor: executeSimpleSql :: simpleSql -> {} ", simpleSql);
		
		return  getJdbcTemplate().query(simpleSql, new BeanPropertyRowMapper<ParkRunner>(ParkRunner.class));
	}
	
	public List<ParkRunner> executeSqlWithParam(Map<String, String> sql) throws  IllegalAccessException, InvocationTargetException, InstantiationException {
		
		LOGGER.info("DBSqlExecutor: executeSqlWithParam :: sql with Param -> {}, {} ", sql.get("sqlQuery"), sql.get("paramValue"));
		
		return  getJdbcTemplate().query(sql.get("sqlQuery"), new Object[] {sql.get("paramValue")}, new BeanPropertyRowMapper<ParkRunner>(ParkRunner.class));
		
	}
```

**Please refer to test case here**
https://github.com/BeTheCodeWithYou/SpringBoot-ZeroCode-Integration/blob/master/src/test/resources/integration_tests/get/dbexecutor/get_parkrunners_using_db_executor.json


please see quick reference here

```
{
   "scenarioName":"DB Executor scenario",
   "steps":[
      {
         "name":"DB_Executor_test",
         "url":"com.xp.springboot.respository.DBSqlExecutor",
         "operation":"executeSimpleSql",
         "request":"select * from park_runner",
         "assertions":[
            {
              "parkRunId" : 1,
	      "firstName" : "NEERAJ",
	       "lastName" : "SIDHAYE",
		"gender" : "M",
		"homeRun" : "INDORE",
		"totalRuns" : "28"
            }
         ]
      },
      {
         "name":"DB_Executor_test",
         "url":"com.xp.springboot.respository.DBSqlExecutor",
         "operation":"executeSqlWithParam",
         "request":{
            "sqlQuery":"select * from park_runner where first_name=?",
            "paramValue":"NEERAJ"
         },
         "assertions":[
            {
              "parkRunId" : 1,
	       "homeRun" : "INDORE",
		totalRuns" : "28"
            }
         ]
      }
   ]
}
```

**Comment by authorjapps** [comment]
@Pulsar1224,
Updated `how to` doc is available at : https://github.com/authorjapps/zerocode/wiki/Sample-DB-SQL-Executor.

This issue can be close now.

Thanks @BeTheCodeWithYou.
