### ISSUE TITLE
HTTPResponse is decoded using default charset of the platform instead of charset specified in response header

### ISSUE THREAD

**Issue by santhoshTpixler** [authorjapps/zerocode#161]
When testing API's which sends a response in **UTF-16 charset is decoded improperly using UTF-8**. The charset header should be used to decode the response and if the charset header is not present, platform default can be used.

1) Current release displays UTF-16 response as below: 
` "rawBody" : "��\u0000{\u0000\"\u0000m\u0000e\u0000s\u0000s\u0000a\u0000g\u0000e\u0000\"\u0000:\u0000\"\u0000m\u0000o\u0000d\u0000e\u0`

2) It would also be nice to have not empty check on BasicHttpClient.java#196
recently we had empty queryParams block in our json which appends ? at the end of the URL. This caused us a problem. "queryParams": { },

**Comment by authorjapps** [comment]
Nice one ! We will put the same fix which looks. Until the release is done, you can override the `handleResponse` method in your custom client as below which has the above fix(so you are not blocked 👍 ).

```java
@Override
public Response handleResponse(CloseableHttpResponse httpResponse) throws IOException {
    ContentType type = ContentType.getOrDefault(httpResponse.getEntity());
    HttpEntity entity = httpResponse.getEntity();
    Response serverResponse = Response
            .status(httpResponse.getStatusLine().getStatusCode())
            .entity(entity != null ? IOUtils.toString(entity.getContent(), Charset.forName(type.getCharset().name())) : null)
            .build();

    Header[] allHeaders = httpResponse.getAllHeaders();
    Response.ResponseBuilder responseBuilder = Response.fromResponse(serverResponse);
    for (Header thisHeader : allHeaders) {
        String headerKey = thisHeader.getName();
        responseBuilder = responseBuilder.header(headerKey, thisHeader.getValue());

        handleHttpSession(serverResponse, headerKey);
    }

    return responseBuilder.build();
}
```

**Comment by authorjapps** [comment]
Also when you get chance, can you put an example into the `hello-world` repo please ? That will help others who might face similar issues. Probably you need to simulate this issue via WireMock server. This is not urgent.

**Comment by authorjapps** [comment]
Fixed n Released in the following version 👍 
```xml
<!-- https://mvnrepository.com/artifact/org.jsmart/zerocode-rest-bdd -->
<dependency>
    <groupId>org.jsmart</groupId>
    <artifactId>zerocode-rest-bdd</artifactId>
    <version>1.2.15</version>
</dependency>
```
