### ISSUE TITLE
Scenarios with finally steps

### ISSUE THREAD

**Issue by santhoshTpixler** [authorjapps/zerocode#170]
Also look at #167, if both can be clubbed 👍 

**Scenarios are a really good feature in zerocode**. But there was one requirement which was left behind. 
## Let me put my definition of scenario:
Scenarios are a sequence of step with should be executed in the defined order. Also, they make use of the response from the previous requests. Which means they are preserving state on the server side. 
# Problem:
If a step in a scenario breaks, then rest of the steps should not be executed. This is fine for the testing environment. But if we use it to test the production API, there will be left over data as a result of scenario failure. It is more like creating a user account at the beginning of the scenario and deleting it at the end. If the creation of account happens then, regardless of the execution of other steps, deletion of the account should happen at the end. It would be nice to have ***finally steps(Java kind of thing)*** in a scenario.

**Comment by santhoshTpixler** [comment]
This will also be useful for user login and logout. @authorjapps

**Comment by authorjapps** [comment]
For time being, we can live with the feature released in `1.2.16`.
Also we can user `@AfterClass` and try out for a runner, where we can release the resources.

Link to 1.2.6 release notes-
https://github.com/authorjapps/zerocode/releases/tag/zerocode-rest-bdd-1.2.16

**Comment by santhoshTpixler** [comment]
> For time being, we can live with the feature released in 1.2.16.
Also we can user @AfterClass and try out for a runner, where we can release the resources.

Agreed. I will close this issue. In the future, if we think for doing it more intuitive then we may consider finally steps.
