### ISSUE TITLE
zerocode http proxy server for generating test cases

### ISSUE THREAD

**Issue by santhoshTpixler** [authorjapps/zerocode#172]
At present we are writing **zerocode** test cases manually. This becomes a behemoth task when the number of requests is higher. This can be automated to some extent by having the **_zerocode HTTP proxy server_**. This server will capture the request and response which can be used for testing in zerocode. Even much better things can be done to make life easier.

This should be a viable option when compared to sticking to specific REST client like postman mentioned here #157 . The proxy server can be used by any REST client like the **postman, Insomnia, client web applications, client android applications** just by setting http proxy.

**Comment by santhoshTpixler** [comment]
Making some progress on this.

**Comment by authorjapps** [comment]
Cool. 👍 
- This pojo could be useful to generate the scenario JSONs
  - src/main/java/org/jsmart/zerocode/core/domain/ScenarioSpec.java

**Comment by santhoshTpixler** [comment]
Http Requests with support for JSON is done.
Multipart/form-data is in progress.

https://github.com/santhoshTpixler/zerocode-proxy-server

**Comment by santhoshTpixler** [comment]
Released v0.0.1  
Link --> https://gitlab.com/santhoshtpixler/zerocode-proxy-server/releases
