### ISSUE TITLE
Kafka - Produce to multiple topic one by one and consume from multi topics at once

### ISSUE THREAD

**Issue by authorjapps** [authorjapps/zerocode#179]
Explain an usecase and implement.

GIVEN multiple topic names,
WHEN I finish putting messages into multiple topics one by one
THEN I will be able to consume from all the topics at once

Raise a new ticket for
+ Producing to multiple topics at once (if Kafka supports) backed by an use-case (#355)

**Comment by nirmalchandra** [comment]
Separate the topics by `comma` e.g.

> "url" : "kafka-topics:topic1, topic2, topic3"

**Comment by oldtimerza** [comment]
Is this ticket still available to pick? I would like to use it to get my first open source contribution in.

**Comment by authorjapps** [comment]
Yes, Thanks @oldtimerza! 

Just to get this done effciently/cleaner(easier to review for the collaborators) - 
Can you implement this for _"consume from multi topics"_ first, which is(could be) a bit straight forward(meaning-- Kafka client provides API to the list of topics to deal with)
> org.apache.kafka.clients.consumer.Consumer#subscribe(java.util.Collection<java.lang.String>)

We can go for this work in one PR.

Producer work - We can do it in a separate PR or a separate ticket!

**Comment by oldtimerza** [comment]
Ok cool . Let me get started and see how it goes.Thank you

**Comment by vaibhavsdl** [comment]
Hi Guys, where can I find local setup instructions to start contributing to this ticket/project?

**Comment by nirmalchandra** [comment]
@vaibhavsdl , can you please check the `BUILDING.md` file near the README file?
If this doesn't help, we can create a special Wiki page for this.

What exactly you are lookin for... ?

**Comment by nawazbaba1993** [comment]
Hi I have bit knowledge on kafka can I take up this issue. To start with my first OSS contribution

**Comment by danish-007** [comment]
Hi ,Can i work on this as my first open source contribution?I have working knowledge of Kafka.

**Comment by vkjha2000** [comment]
It's great to know @danish-007, can you please check if you can pick any other Kafka related issue?
It seems like this issue has been already fixed and a PR is waiting for approval.
PR link: https://github.com/authorjapps/zerocode/pull/327

**Comment by authorjapps** [comment]
Available in `1.3.17` release
