### ISSUE TITLE
Static assertEquals for comparing two JSON contents

### ISSUE THREAD

**Issue by officiallysameer** [authorjapps/zerocode#18]
Is it possible to add the static methods for JSON comparison. There are many asserters already available in the open source communities, but by those not all of the below are covered, hence it will be useful to add these asserters.

e.g.
DEFAULT mode is FIELDS_ANY_ORDER_IGNORE_NULL
`JsonAsserter.assertEquals(actual, expected, mode); //<-- compare mode FIELDS_ANY_ORDER_IGNORE_NULL`
```
actual={"name": "Harry", "age": 20}, expected={"name": "Harry", "age": 20} : will **PASS**
actual={"name": "Harry", "age": 20}, expected={"age": 20,"name": "Harry"} : will **PASS**
actual={"name": "Harry", "age": 20}, expected={"name": "Harry"} : will **PASS**
actual={"name": "Harry", "age": null}, expected={"name": "Harry"} : will **PASS**
actual={"name": "Harry", "age": 20}, expected={"age": 20} : will **PASS**

```
JsonAsserter.assertEquals(actual, expected, mode); //<-- compare mode FIELDS_STRICT_ORDER_EXACT_MATCH
```
actual={"name": "Harry", "age": 20}, expected={"name": "Harry", "age": 20} : will **PASS**
actual={"name": "Harry", "age": 20}, expected={"name": "Harry", "age": "$NOT.NULL"} : will **PASS**
actual={"name": "Harry", "age": 20}, expected={"name": "$NOT.NULL", "age": "$NOT.NULL"} : will **PASS**
actual={"name": "Harry", "age": 20}, expected={"age": 20,"name": "Harry"} : will **FAIL**
actual={"name": "Harry", "age": 20}, expected={"name": "Harry"} : will **FAIL**

```
Any other scenarios needed?

**Comment by authorjapps** [comment]
There is already a similar library available called `JSONAssert` from skyscreamer in GitHub. That can be used. We can contribute to that library to improve or take care of this situation, that's better.
