### ISSUE TITLE
Host config properties to be accessible via the keys e.g. filename.key

### ISSUE THREAD

**Issue by authorjapps** [authorjapps/zerocode#183]

**Comment by authorjapps** [comment]
From Gitter @santhoshTpixler raised a feature request which will be helpful for manual testers as they don't need to deal much with the codes.
Currently the properties are available via the PropertyUtil class given in the HelloWorld example, which is good enough for developers/automation-testers.

But it will be convenient if this feature is implemented.

e.g.
`host_file1.new_url.host`
`host_file1.new_url.port`

In that way the keys will clash with each other. 👍

**Comment by santhoshTpixler** [comment]
It will benefit everyone. It is like defining common properties in the property file and accessing it across all the test without any method invocation. It will be global variables in a property file.

**Comment by authorjapps** [comment]
This is runtime properties reading, Google assisted Inject can be used here as below(but not limited to only this).

+ AssistedInject Wiki
https://github.com/google/guice/wiki/AssistedInject

**Comment by dinesh76in** [comment]
>e.g.
`host_file1.new_url.host`
`host_file1.new_url.port`

Not probably necessary because there is always one host file per env.
Hence, no need to prefix I think to keep it simple and easy.
> `new_url.host`
`new_url.port`

**Comment by authorjapps** [comment]
Fixed. PR https://github.com/authorjapps/zerocode/pull/185 under review now. Once done, this branch will be merged.

**Comment by authorjapps** [comment]
Implemented and released.
Please pick the below version.
```xml
<dependency>
    <groupId>org.jsmart</groupId>
    <artifactId>zerocode-rest-bdd</artifactId>
    <version>1.2.17</version> 
    <scope>test</scope>
</dependency>
```
