### ISSUE TITLE
Server Sent Event Automated Testing 

### ISSUE THREAD

**Issue by authorjapps** [authorjapps/zerocode#198]
GIVEN There are multiple clients connected to a Server over event-stream
WHEN an Event is generated at Server
THEN The client(s) should get notified of the Event
AND I will be able to assert that the Client has received the event via an automated test.

Manual Steps and Traditional Way:
- Open multiple Browsers which establishes the connections to the server
- Then generate an event on the Server by calling a REST point using Postman
- Then verify that the Browser(clients) has received this event successfully

**Comment by BeTheCodeWithYou** [comment]
@authorjapps  created SSE Test automation repository with step by step wiki

https://github.com/BeTheCodeWithYou/Spring-Boot-SSE

closing this issue.
