### ISSUE TITLE
Failure to find io.confluent:kafka-avro-serializer:jar

### ISSUE THREAD

**Issue by dinesh76in** [authorjapps/zerocode#199]
It's good to remove this dependency and move this to test repo along with Code/Test.
Because this is not inside maven realm. Let's have a thought !

>  Failure to find io.confluent:kafka-avro-serializer:jar:5.1.0

> :::Note::: There is a work around to this. But the point it how we can we keep it straight! 

`Can't we keep it optional to the users not-using AVRO. Avro users can add this explicitly`

```
$
...

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.994 s
[INFO] Finished at: 2019-02-04T14:07:20+00:00
[INFO] Final Memory: 9M/245M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project test-sandbox: Could not resolve dependencies for 
project org.jsmart:test-sandbox:jar:0.0.1-SNAPSHOT: 

Failure to find io.confluent:kafka-avro-serializer:jar:5.1.0 in 
https://artefactrepository.<mybank>.co.uk/repository/public/ was cached in the local repository,
 resolution will not be 
reattempted until the update interval of nexus has elapsed or updates are forced -> [Help 1]
[ERROR] 
http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
$ 
```

**Comment by authorjapps** [comment]
Linking to simillar Issue https://github.com/authorjapps/zerocode/issues/196.

> Can't we keep it optional to the users not-using AVRO. Avro users can add this explicitly

Yes, it will be bit painful from Framework-Development point of view.

**Comment by authorjapps** [comment]
Version 1.3.1 has been released with the fix.
- Confluent Avro has been removed from the POMs.
- Sill allows to add explicitly and test (explained in Hello Kafka Testing repo)
