### ISSUE TITLE
Allow body payload from external JSON resource

### ISSUE THREAD

**Issue by authorjapps** [authorjapps/zerocode#2]
Defined the new place holder structure here.
e.g.

```
{
    "name": "add_500_employees_load",
    "url": "/google-emp-services/home/employees",
    "operation": "PUT",
    "request": {
        "body": "${JSON.FILE:common_files/request/500_employees_each_with_5_addresses.json}"
    },
    "assertions": {
        "status": 200
    }
}
```

More:

**Comment by UmeshIghe** [comment]
Is this branch merged with master ?

**Comment by dinesh76in** [comment]
Not exactly. This was not a blocker and also it was argued that - the `independent-ness` of the test cases and the readability will be lost if allowed this way. Also one has to `traverse to n fro` via the IDE to know the payload structure. So it was paused.

Are you looking for **load** testing ? or stress testing aka performance testing? 
Framework recently developed this and enables loading the same test(s) number of times, in a particular interval of time and all these are configurable in a properties file.

**Comment by UmeshIghe** [comment]
I am doing Functional testing, I am also looking a way where we can parameterize a test using external data source like csv.
Having Json externalize can reduce the size of json, also it will avoid duplicate data, just a thought

**Comment by authorjapps** [comment]
@UmeshIghe , sounds good to reuse the payload from a JSON file, that's why this ticket was for 👍. But as mentioned in the earlier comment , the `traversing n independentness` will be lost, that's the trade-off of this approach.

Anyways, we will include this feature in our upcoming release(_a week or so_ - will try). 👍 
Please watch n follow our latest news/releases/features etc in [Twitter](https://twitter.com/ZercodeEasyTDD). 
Readme section - https://github.com/authorjapps/zerocode#latest-newsreleasesfeatures

Note-
Even now you can achieve this via calling a Java(Pojo), but JSON is better in my opinion in order to copy paste as it is like postman. Let's go for JSON file way.

**Comment by albertosipov** [comment]
Also this makes sense, doesn't it ?-
```
{
    "name": "update_address",
    "url": "/api/v1/addresses/AD-US-01",
    "operation": "PUT",
    "request": {
        "body": "${JSON.FILE:test_files/address_payload.json}"
    },
    "assertions": {
        "status": 200,
        "body"{
            "id": "AD-US-01"
         }
    }
}
```

and if you make a GET call(which of course is necessary to verify the result)
 then it should allow to `assert from a file` too ?
```
{
    "name": "Get the address",
    "url": "/api/v1/addresses/${$.update_address.response.id}",
    "operation": "GET",
    "request": {
    },
    "assertions": {
        "status": 200,
        "body": "${JSON.FILE:test_files/address_response.json}"
    }
}
```
What you think @UmeshIghe @macrocks @nirmalchandra @officiallysameer ?
Better ?

If we are allowing body JSON file, we should allow the response JSON file ?

I am leaving it **open** for discussion.

**Comment by aghorpade** [comment]
@UmeshIghe @albertosipov  .Yes it is a good feature to be pick it as an enhancement. It will help everyone to reuse json in multiple test cases.

**Comment by authorjapps** [comment]
Yeah, also the following too makes sense,
> Here, only the 'addresses' part of it is common and can be read from a Json file.

```
{
    "name": "update_addresses",
    "url": "/api/v1/addresses/emp_001",
    "operation": "PUT",
    "request": {
        "body": {
            "updatedDate": "2018-10-10",
            "addresses": "${JSON.FILE:test_files/common_addressses.json}"
        }
    },
    "assertions": {
        "status": 200,
        "body": {
            "addresses": "${JSON.FILE:test_files/common_addressses.json}"
        }
    }
}
```
and the `common_addressses.json` can be like below,
```
[
    {
        "type":"corp-office",
        "city":"Texas"
    },
    {
        "type":"hr-office",
        "city":"Newark"
    }
]
```
Basically, resolve the `JSON.FILE` in request and response(ie assertion) node by deep traversing.

Also `JSON.FILE` sounds meaningful than `JSON.PAYLOAD.FILE`.
I will update the description if there is no objections from anyone. 

@UmeshIghe, are you happy for these implementations?

**Comment by nirmalchandra** [comment]
fyi - PR raised n under review, PR No- https://github.com/authorjapps/zerocode/pull/138
Things pending-
- Update README file
- Add a wiki page for this feature

**Comment by UmeshIghe** [comment]
> Yeah, also the following too makes sense,
> 
> > Here, only the 'addresses' part of it is common(not the entire body payload) and can be read from a Json file.
> 
> ```
> {
>     "name": "update_addresses",
>     "url": "/api/v1/addresses/emp_001",
>     "operation": "PUT",
>     "request": {
>         "body": {
>             "updatedDate": "2018-10-10",
>             "addresses": "${JSON.FILE:test_files/common_addressses.json}"
>         }
>     },
>     "assertions": {
>         "status": 200,
>         "body": {
>             "addresses": "${JSON.FILE:test_files/common_addressses.json}"
>         }
>     }
> }
> ```
> and the `common_addressses.json` can be like below,
> 
> ```
> [
>     {
>         "type":"corp-office",
>         "city":"Texas"
>     },
>     {
>         "type":"hr-office",
>         "city":"Newark"
>     }
> ]
> ```
> Basically, resolve the `JSON.FILE` in request and response(ie assertion) node by deep traversing.
> 
> Also `JSON.FILE` sounds meaningful than `JSON.PAYLOAD.FILE`.
> I will update the description if there are no objections from anyone.
> 
> @UmeshIghe, are you happy for these implementations?

Yes , this is also good

**Comment by authorjapps** [comment]
Hello mate @UmeshIghe, When u get chance, can you say Hello in gitter chat room please? 🙏
Gitter link: https://gitter.im/zerocode-testing/help-and-usage

_Sounds like you are doing something interesting and will be nice if you publish a small write-up/article as a blog._
