### ISSUE TITLE
Getting Error reading XMLStreamReader: Unexpected character '"' when mocking soap endpoint

### ISSUE THREAD

**Issue by arunvelusamyd** [authorjapps/zerocode#202]
Getting Error reading XMLStreamReader: Unexpected character '"' when mocking soap response.

Below is the sample of how i mocked a soap endpoint

`{
            "name": "mocking_SOAP_to_get_device_details",
            "operation": "POST",
            "url": "/ws",
            "request": {
            },
            "response": {
              "status": 200,
              "body": "<SOAP-ENV:Envelope xmlns:SOAP-ENV=\"http://schemas.xmlsoap.org/soap/envelope/\"><SOAP-ENV:Header/><SOAP-ENV:Body><ns2:GetDeviceDetailsResponse xmlns:ns2=\"http://flexy.com/device\"><ns2:DeviceDetails><ns2:id>1</ns2:id><ns2:name>iPad</ns2:name><ns2:description>It is a tablet computers designed, developed and marketed by Apple.</ns2:description></ns2:DeviceDetails></ns2:GetDeviceDetailsResponse></SOAP-ENV:Body></SOAP-ENV:Envelope>"
            }
          }`

But I'm getting the below error,
Error reading XMLStreamReader: Unexpected character '"' (code 34) in prolog; expected '<'

**Comment by arunvelusamyd** [comment]
we can fix this by changing the below code in RestEndPointMocker.java

`String jsonBodyRequest = mockStep.getResponse().get("body").toString();`

to 

`JsonNode jsonNodeResponse = mockStep.getResponse();
JsonNode jsonNodeBody = jsonNodeResponse.get("body");
String jsonBodyRequest = (jsonNodeBody != null)?jsonNodeBody.toString():jsonNodeResponse.get("xmlBody").asText();`

Kindly help to review & fix this.

I have a example which can help to understand more, 
https://github.com/arunvelusamyd/spring-boot-rest-sample/blob/master/src/it/java/integrationtests/com/flexy/student/GetStudentIT.java

**Comment by authorjapps** [comment]
@arunvelusamyd , sounds great, Thanks!
Just let's get this validated via a PR.
@santhoshTpixler , @BeTheCodeWithYou and all folks please(when you get chance, please review).

**Comment by authorjapps** [comment]
@arunvelusamyd , sorry mate for the delay.
We are on it today.
+ Changes in PR looks good. 
+ Just we need to add couple of `unit tests` to make sure it's not breaking any existing mocking.

Once done, we will try to release by tonight. 👍

**Comment by arunvelusamyd** [comment]
No problem dude and it’s not a big delay.😊 Thanks for the update.

**Comment by authorjapps** [comment]
Fixed in the below version 
```xml
<dependency>
  <groupId>org.jsmart</groupId>
  <artifactId>zerocode-tdd</artifactId>
  <version>1.3.2</version>
</dependency>
```
