### ISSUE TITLE
Add lombok Library and make zerocode more user friendly and reduce no of lines

### ISSUE THREAD

**Issue by aghorpade** [authorjapps/zerocode#216]
Hi All,

Requesting a enhancement to zerocode library by adding Lombok library. this will not impact end user/consumer but it will help contributor to see user friendly code,reduced no of lines and add advantages which are provided by Lombok library.

https://projectlombok.org/ - add lombok maven depedency and replace getter/setter/toString/HashCode/Equals method with `@Data`
Getter Setter with `@Getter @Setter` annotation.

**Comment by aghorpade** [comment]
@authorjapps  @BeTheCodeWithYou @dinesh76in  - do you think this will add benefit to zerocode framework? if yes, then we can pickup this up.

**Comment by authorjapps** [comment]
@aghorpade , actually this might not add any value in my opinion. We have to maintain it with unnecessary overhead. Also we need to install  a plugin to work in the IDE to avoid compile-time error. 

Even now we don't write the getters/setters, toString, equals/hasCode etc manually, we use IDE to generate it for us.

Let's close this issue for now.

**Comment by BeTheCodeWithYou** [comment]
@aghorpade  good suggestion but I think for the zerocode, I don't see much benefits but rather overhead for maintenance.  Yes lombok is very good and I have used it but I think should be used for only private projects.  Debugging becomes difficult if you wish to put debug on equals() or hasCode.. you can't, as they are generated magically :-)
 
I just did quick scan on google for it's side effects, and this article really a must read before using  anywhere in general
lombok https://medium.com/@gabor.liptak/some-dangers-of-using-lombok-d759fc8f701f

@authorjapps  agree with you points.

**Comment by aghorpade** [comment]
Cool.. Just for everyone's life to be easy.. lets drop this idea to add Lombok. We can close this ticket
