### ISSUE TITLE
Mailing list

### ISSUE THREAD

**Issue by jaoseguera** [authorjapps/zerocode#217]
Greetings,

I want to contribute in the project. Do you have any mailing list?

Thanks.

**Comment by authorjapps** [comment]
Greetings and Welcome, Thanks for your interest in contributing. 👍 

+ Please visit this(2min read) CONTRIBUTION guidelines page
   + https://github.com/authorjapps/zerocode/blob/master/CONTRIBUTING.md

+ Gitter link acts as QnA forum currently
    + https://gitter.im/zerocode-testing/help-and-usage

+ Mailing list(It was long pending, created Yday, I will be inviting the members to join eventually)
   + https://groups.google.com/forum/#!forum/zerocode-automation

Cheers
