### ISSUE TITLE
Maven update to latest version of Jackson faster xml

### ISSUE THREAD

**Issue by authorjapps** [authorjapps/zerocode#218]
Objective
===
+ Please check if any Jackson API in use has been deprecated
   + Update with equivalent APIs
+ All tests should pass - Unit tests n Integration Tests basically
+ HelloWorld repo CI build should pass
   + please check first with SNAPSHOT version locally before pushing
+ (Optional) Check if we can use AutoDetect annotation instead of JsonPropery
   + Not super urgent. Do this only if this doesn't need massive code change.
   + We can do later as part of a new ticket too.

**Comment by jaoseguera** [comment]
Do you still need help with this? It's still an open issue and I want to help.

**Comment by authorjapps** [comment]
Thanks mate. Yes, please proceed. 👍 
Can you please assign the issue to you when you are ready?

_You are right, the problem kind of keeps popping up every now and then_

Jackson folks need to address this vulnerability.

**Comment by jaoseguera** [comment]
Ok. I'm proceeding. There are some things deprecated. I"m uptading them. I'll keep you posted.

**Comment by jaoseguera** [comment]
I have changed: **@JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)** 

for: **@JsonInclude(JsonInclude.Include.NON_NULL)**

And: **import org.apache.http.conn.ssl.SSLContextBuilder;**

for: **import org.apache.http.ssl.SSLContextBuilder;**

Can you help me with this part, please? I don't know how to do it: "HelloWorld repo CI build should pass
please check first with SNAPSHOT version locally before pushing"

**Comment by jaoseguera** [comment]
The annotation is @JsonAutoDetect an not @AutoDetect, right?

**Comment by authorjapps** [comment]
> The annotation is @JsonAutoDetect an not @AutoDetect, right?

> I'm investigating @JsonAutoDetect and @JsonProperty and they are not for the same purpose:

> The Jackson annotation @JsonAutoDetect is used to tell Jackson to include properties which are not public, both when reading and writing objects.

Understood mate. Thanks.
Let's not get into this change. This is not going to help us anyways.

**Comment by authorjapps** [comment]
> 
> And: **import org.apache.http.conn.ssl.SSLContextBuilder;**
> 
> for: **import org.apache.http.ssl.SSLContextBuilder;**
> 

Do we need this change? This gets tested in the CI repo, which I have put the details below.
If so, then we should be good if the build is Green.

> I have changed: **@JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)**
> 
> for: **@JsonInclude(JsonInclude.Include.NON_NULL)**

> Can you help me with this part, please? I don't know how to do it: "HelloWorld repo CI build should pass
> please check first with SNAPSHOT version locally before pushing"

That sounds cool. 
`HelloWorld repo CI build should pass` - This means you can put the snapshot build of your `zerocode-tdd` changes into the [HelloWorld repo](https://github.com/authorjapps/zerocode-hello-world).

Step1-
Clone/Fork the HelloWorld repo(2min). Here is the [link](https://github.com/authorjapps/zerocode-+ hello-world).

Step2-
Put your SNAPSHOT build as a dependency. Basically just update this line
> 		<zerocode-rest-bdd.version>1.3.4</zerocode-rest-bdd.version>

It would look like
> 		<zerocode-rest-bdd.version>1.3.5-SNAPSHOT</zerocode-rest-bdd.version>

Step3-
Run the maven command
> mvn clean install
See here [How to run HelloWorld](https://github.com/authorjapps/zerocode-hello-world#how-to-run-the-examples)

It sounds like a big deal, but it just needs only a couple of mins to get it running. Also this is just onetime set up.
This covers us for making it backward compatible testing, and doesn't break anything for existing customers/users.

**Comment by authorjapps** [comment]
Hello mate, Do not worry much about the "running the HelloWord with SNAPSHOT" stuff. We will take care of that when the PR is active.
If your changes are in a good state, you can please raise a PR or when you are ready.

**Comment by jaoseguera** [comment]
Sorry for the late reply, man. I understood the steps of the HelloWorld. I just trying to solve some issues. When I build the project some tests are failing and when I skipped the tests to build the project I get the same message.

**Comment by jaoseguera** [comment]
After running "mvn clean install":

Results :

Failed tests:   testReport_correct_scenariosAndSteps(org.jsmart.zerocode.core.domain.reports.ZeroCodeReportTest): (..)
  test_AllStepsAfterFailedStepExecuted(org.jsmart.zerocode.core.runner.ZeroCodeMultiStepsScenarioRunnerImplE2ETest): (..)
  willGenerateloopReportIfRunLoop2AllPassRun_twice(org.jsmart.zerocode.core.verification.loopreport.SmartJUnitNavigatorReportGenTest): (..)
  willGenerateloopReportIfRunLoop2OneFailRun_twice(org.jsmart.zerocode.core.verification.loopreport.SmartJUnitNavigatorReportGenTest): (..)

Tests in error:
  willResolveJsonPathOfJayWay(org.jsmart.zerocode.core.engine.preprocessor.ZeroCodeJsonTestProcesorImplTest): (..)
  willResolveJsonPathOfJayWayWith_SuppliedScenarioState(org.jsmart.zerocode.core.engine.preprocessor.ZeroCodeJsonTestProcesorImplTest): (..)
  willCaptureAllPlaceHolders(org.jsmart.zerocode.core.engine.preprocessor.ZeroCodeJsonTestProcesorImplTest): (..)
  testReadLineByLine_deser(org.jsmart.zerocode.core.kafka.send.KafkaSenderTest): java.io.FileNotFoundException: C:\Users\emxnew23196\Documents\Open%20Source%20%26%20Challenges\ZeroCode\core\target\test-classes\kafka\pfiles\unit_test_data_raw.json (The system cannot find the path specified)
  testReadLineByLine(org.jsmart.zerocode.core.kafka.send.KafkaSenderTest): java.io.FileNotFoundException: C:\Users\emxnew23196\Documents\Open%20Source%20%26%20Challenges\ZeroCode\core\target\test-classes\kafka\pfiles\unit_test_data_raw.json (The system cannot find the path specified)
  willGeneratReportLoopSceneMultiStepsLoop2_once(org.jsmart.zerocode.core.verification.loopreport.SmartJUnitNavigatorReportGenTest): No value present
  willPassIfEqualsToSame_number(org.jsmart.zerocode.core.verification.ZeroCodeUnitNumberEqualsTest): ZeroCode Step execution failed. Details:java.lang.RuntimeException: (..)
  test_fileBodyAndAssertions(org.jsmart.zerocode.filebody.ReuseFileBodyTest): ZeroCode Step execution failed. Details:java.lang.RuntimeException: (..)
  test_fileBodyAndAssertions(org.jsmart.zerocode.filebody.ReuseFileBodyTest)
  test_fileBody(org.jsmart.zerocode.filebody.ReuseFileBodyTest): ZeroCode Step execution failed. Details:java.lang.RuntimeException: (..)
  test_fileBody(org.jsmart.zerocode.filebody.ReuseFileBodyTest)
  testHelloWorld_AllApi(org.jsmart.zerocode.filebody.ReuseFileBodyTest): ZeroCode Step execution failed. Details:java.lang.RuntimeException: (..)
  testHelloWorld_AllApi(org.jsmart.zerocode.filebody.ReuseFileBodyTest)

Tests run: 228, Failures: 4, Errors: 13, Skipped: 15

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for ZeroCode TDD Parent 1.3.6-SNAPSHOT:
[INFO]
[INFO] ZeroCode TDD Parent ................................ SUCCESS [  1.768 s]
[INFO] Zerocode TDD Core .................................. FAILURE [02:52 min]
[INFO] Zerocode Http Testing Simple JSON DSL .............. SKIPPED
[INFO] Zerocode Kafka Testing Simple JSON DSL ............. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:54 min
[INFO] Finished at: 2019-04-01T09:27:43-06:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project zerocode-tdd: There are test failures.
[ERROR]
[ERROR] Please refer to C:\Users\emxnew23196\Documents\Open Source & Challenges\ZeroCode\core\target\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :zerocode-tdd

**Comment by jaoseguera** [comment]
I have a question @authorjapps.

In the HelloWorld repo, when I build the project with this property:

```
<properties>
    <zerocode-rest-bdd.version>1.3.5</zerocode-rest-bdd.version>
</properties>
```

Everything is alright. But when I change the version to 1.3.6-SNAPSHOT (I already build the project of ZeroCode and I have the .jar in my local repository) I get some errors:

`> mvn clean install`

[INFO] Results:
[INFO]
[ERROR] Failures: 
[ERROR]   HelloReuseJsonFileAsContentTest.testHelloWorld_jsonFileAsBody Multiple Failures (2 failures)
        ZeroCode Step execution failed. Details:java.lang.RuntimeException: 
JSON:/api/v1/employees/${$.create_emp.response.body.id}
Possibly comments in the JSON found or bad JSON path found: $.create_emp.response.body.id, Details: java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lan
g.String (java.lang.Integer and java.lang.String are in module java.base of loader 'bootstrap')
        <no message> in java.lang.NullPointerException
[ERROR]   HelloReuseJsonFileAsContentTest.testHello_jsonFileAsResponseBody Multiple Failures (2 failures)
        ZeroCode Step execution failed. Details:java.lang.RuntimeException: 
JSON:/api/v1/employees/${$.create_emp.response.body.id}
Possibly comments in the JSON found or bad JSON path found: $.create_emp.response.body.id, Details: java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lan
g.String (java.lang.Integer and java.lang.String are in module java.base of loader 'bootstrap')
        <no message> in java.lang.NullPointerException
[ERROR]   JustHelloWorldMoreTest.testHelloWorld_AllApi Multiple Failures (2 failures)
        ZeroCode Step execution failed. Details:java.lang.RuntimeException: 
JSON:/api/v1/google-uk/employees/${$.create_emp.response.body.id}
Possibly comments in the JSON found or bad JSON path found: $.create_emp.response.body.id, Details: java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lan
g.String (java.lang.Integer and java.lang.String are in module java.base of loader 'bootstrap')
        <no message> in java.lang.NullPointerException
[INFO]
[ERROR] Tests run: 26, Failures: 3, Errors: 0, Skipped: 2
[INFO]
[INFO]
[INFO] --- maven-failsafe-plugin:3.0.0-M3:verify (default) @ zerocode-hello-world ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  35.286 s
[INFO] Finished at: 2019-04-03T09:18:48-06:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:3.0.0-M3:verify (default) on project zerocode-hello-world: There are test failures.
[ERROR]
[ERROR] Please refer to C:\Users\emxnew23196\Documents\Open Source & Challenges\ZeroCode (Hello World)\target\failsafe-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by jaoseguera** [comment]
I've been checking the failures and I found this:

org.jsmart.zerocode.core.domain.reports.ZeroCodeRunTwoScenariosForReport
org.jsmart.zerocode.core.domain.reports.ZeroCodeRunTwoScenariosForReport#initializationError
Failed
9ms
Message:
N/A
Stack trace:
java.lang.ExceptionInInitializerError
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at org.junit.internal.requests.FilterRequest.getRunner(FilterRequest.java:36)
	at com.microsoft.java.test.runner.junit4.JUnit4RunnerUtil.getRequestForOneMethod(JUnit4RunnerUtil.java:59)
	at com.microsoft.java.test.runner.junit4.JUnit4RunnerUtil.createTestReferences(JUnit4RunnerUtil.java:44)
	at com.microsoft.java.test.runner.junit4.CustomizedJUnit4CoreRunner.run(CustomizedJUnit4CoreRunner.java:25)
	at com.microsoft.java.test.runner.junit4.JUnit4Launcher.execute(JUnit4Launcher.java:30)
	at com.microsoft.java.test.runner.Launcher.main(Launcher.java:53)
Caused by: java.lang.RuntimeException: YouTriedToSimulateNothingException: Check the (simulators) integration test repo folder(empty?). 
	at org.jsmart.simulator.impl.JsonBasedSimulator.getDeserializedApiSpecList(JsonBasedSimulator.java:467)
	at org.jsmart.simulator.impl.JsonBasedSimulator.<init>(JsonBasedSimulator.java:51)
	at org.jsmart.simulator.main.SimpleRestJsonSimulatorsMain.<init>(SimpleRestJsonSimulatorsMain.java:18)
	at org.jsmart.zerocode.core.tests.customrunner.TestOnlyZeroCodeUnitRunner.<clinit>(TestOnlyZeroCodeUnitRunner.java:15)
	... 16 more

That means that I have to mock a server?

**Comment by authorjapps** [comment]
Apologies mate for late reply, Build looks good 👍. In your case, I think it's an IDE issue spitting out some errors.
See below the command line maven build status - I only built 2 modules(not Kafka, but Kafka will get built in CI pipeline anyway)

```
Results :

Tests run: 225, Failures: 0, Errors: 0, Skipped: 15

[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ zerocode-tdd ---
[INFO] Building jar: /Users/nirmalchandra/dev/http_clone/github/zerocode_forked_prs/jaoseguera/zerocode/core/target/zerocode-tdd-1.3.6-SNAPSHOT.jar
[
[INFO] Installing /Users/nirmalchandra/dev/http_clone/github/zerocode_forked_prs/jaoseguera/zerocode/http-testing/pom.xml to /Users/nirmalchandra/.m2/repository/org/jsmart/http-testing/1.3.6-SNAPSHOT/http-testing-1.3.6-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Zerocode TDD Core .................................. SUCCESS [01:42 min]
[INFO] Zerocode Http Testing Simple JSON DSL .............. SUCCESS [  1.674 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:44 min
[INFO] Finished at: 2019-04-20T08:34:01+01:00
[INFO] Final Memory: 33M/339M
[INFO] ------------------------------------------------------------------------
$ pwd
.../github/zerocode_forked_prs/jaoseguera/zerocode

$ date
Sat Apr 20 08:35:10 BST 2019

$ git status
On branch ISS-218-Maven-Jackson-update

```

I don't see there are any other issues, but let's wait a while for other reviewer's feedback and the Kafka build feedback from travis.
Then we should be able to merge. 👍 

Thanks for the great work !

**Comment by authorjapps** [comment]
Yes, now the CI feedback is good(includes Kafka build). 👍 

```
2019-04-20 07:30:42,638 [main] INFO  org.jsmart.zerocode.core.domain.builders.ExtentReportsFactory - Where were the tests fired? Ans: OS:Linux, Architecture:amd64, Java:1.8.0_151

Results :

Tests run: 31, Failures: 0, Errors: 0, Skipped: 8

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] ZeroCode TDD Parent ................................ SUCCESS [  1.062 s]
[INFO] Zerocode TDD Core .................................. SUCCESS [02:17 min]
[INFO] Zerocode Http Testing Simple JSON DSL .............. SUCCESS [  1.969 s]
[INFO] Zerocode Kafka Testing Simple JSON DSL ............. SUCCESS [02:34 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 04:55 min
[INFO] Finished at: 2019-04-20T07:30:44Z
[INFO] Final Memory: 28M/360M
[INFO] ------------------------------------------------------------------------

```

CI Build link(in case you want to have a look): 
https://api.travis-ci.org/v3/job/522416660/log.txt

**Comment by authorjapps** [comment]
Release version 1.3.7 and onwards.

**Comment by authorjapps** [comment]
This has been release now. Thanks @jaoseguera for your hardwork! 🙏 
```xml
<dependency>
  <groupId>org.jsmart</groupId>
  <artifactId>zerocode-tdd</artifactId>
  <version>1.3.7</version>
</dependency>
```
Release Notes-
https://github.com/authorjapps/zerocode/releases/tag/zerocode-tdd-parent-1.3.7
