### ISSUE TITLE
Oracle DB executor please

### ISSUE THREAD

**Issue by dinesh76in** [authorjapps/zerocode#22]
Can you have a DB executor to execute a SQL query on a DB e.g. `Oracle` and return result in a `HashMap`, but translated to `JSON` format.
e.g.
`
select ID, NAME from CUSTOMERS where SALARY < 40000;
 `

If it returns **result**-

| ID | NAME|
|---|-------|
|1   | Tom |
|2   | Harry|

The response should be translated to-
```
"response": [
   {
       "ID": "1",
       "NAME": "Tom"
   },
   {
       "ID": "2",
       "NAME": "Harry"
   }
]
```

**Comment by authorjapps** [comment]
Solved in the issue https://github.com/authorjapps/zerocode/issues/158
