### ISSUE TITLE
Need support for delay between steps

### ISSUE THREAD

**Issue by hpriyankajuniper** [authorjapps/zerocode#221]
For some operations to complete before checking for a value in the response, a delay is required between the execution of 2 steps in a scenario.

Example: Waiting for 3 minutes to check the status of a job (goes to SUCCESS or FAILURE which needs to be asserted)

**Comment by nirmalchandra** [comment]
It's very easy.
Just execute a java function for how much delay you need in which unit. e.g. in secs, or minutes or milliseconds etc.

e.g. 
```
public class Delay {

    public void minutes(int min) throws InterruptedException {
        Thread.sleep(min*60*1000);
    }

    // But you can add your own flavoured delay function if you want
    // and just call the same function as below
}
```

The step looks like below calling the above delay-
> Gives us 5 seconds delay.

```
        {
            "name": "delay_in_seconds",
            "url": "org.jsmart.utils.Delay", //<---- Put your class name basically
            "operation": "seconds", //<--- function name
            "request": 5,  //<--- function parameter
            "assertions": {
            }
        }

```

That's it, done.
***


You see or verify the result like below in your console as well as log file.

```
--------- TEST-STEP-CORRELATION-ID: 1f1ddf49-ad13-41e3-a90e-b55d18a7320c ---------
*requestTimeStamp:2019-03-21T07:06:08.317
step:delay_seconds
url:org.jsmart.utils.Delay
method:seconds
request:
5 
--------- TEST-STEP-CORRELATION-ID: 1f1ddf49-ad13-41e3-a90e-b55d18a7320c ---------
Response:
null
*responseTimeStamp:2019-03-21T07:06:13.322 
*Response delay:5005.0 milli-secs 
---------> Assertion: <----------
{ } 
-done-
```

Let's verify as matter of evidence we got 5 second delay or not.
Observe in the pretty print step as below.
```
*requestTimeStamp:2019-03-21T07:06:08.317
*responseTimeStamp:2019-03-21T07:06:13.322 
*Response delay:5005.0 milli-secs <------- We got it. Happy days !
```

Now to get 3mins delay, you can do this way
```
       {
            "name": "delay_minutes",
            "url": "org.jsmart.utils.Delay",
            "operation": "minutes",  <----- calling the minutes function now.
            "request": 3,
            "assertions": {
            }
        }
```

**Comment by hpriyankajuniper** [comment]
Thanks a lot!

**Comment by BeTheCodeWithYou** [comment]
@authorjapps  details helpful. 
It would be nice if we have this delay support as part of framework so consumer don't have to create a class.  yeah?

**Comment by marcelo-xavier-bl** [comment]
This doesn't work for kafka tests : ( It would be great to add the same think for event tests
