### ISSUE TITLE
Asset a specific message when multiple messages flowing through the brokers or topics

### ISSUE THREAD

**Issue by nirmalchandra** [authorjapps/zerocode#222]
Created from #220 

**2. When testing in real environment, there will be multiple messages flowing through the brokers/topics. How can zerocode validate/asset a specific response?
Ans: Use Json Path to look for a perticular message or a record key or value. Very easy!
e.g.**

When you have consume multiple records from a topic, that means you receive an array of records as the response.
Then you can assert this way explained in the readme-file.

_Where is this JSON path is applied ? In JUNIT or within Zerocode JSON config ?_

For example, my test below keeps on failing. In the log, instead of just consuming the messages with the ids I have specified below. It consumes the whole array of 10 messages.

```
{
    "scenarioName": "consume a JSON message with id_5 & id_9 out of 10 messages produced on topic_A",
    "steps": [

        {
            "name": "consume_step",
            "url": "kafka-topic:topic_A",
            "operation": "consume",
            "request": {
                "consumerLocalConfigs": {
                    "recordType": "JSON",
                    "commitSync": true,
                    "showRecordsConsumed": true,
                    "maxNoOfRetryPollsOrTimeouts": 3
                }
            },
            "assertions": {
                "records": [
                    {
                        "key": "id_5",
                        "value": {

                            "TEST": "Test Val0"
                        }
                    },
                    {
                        "key": "id_9",
                        "value": {

                            "TEST": "Test Val9"
                        }
                    }
                ]
            }
        }
    ]
}
```

**Comment by authorjapps** [comment]
Hello @tghani93, Do you still want us to look at it?

**Comment by tghani93** [comment]
@authorjapps - thank you for your help so far. Just one more question: security. Could you point me to some resources / documentation where I can read about library (zerocode's) security?

TIA

**Comment by authorjapps** [comment]
Just trying to understand -
Are you looking for how Zerocode supports/invokes secured APIs e.g. `Https` /  `OAuth2` /  SAML / `Kafka` etc?
or anything else in general ?

If you could be specific, then we can try to answer...

**Comment by tghani93** [comment]
Yes secure APIs as you mentioned and in general as well :)
I am planning on doing a blog about Zerocode also, so wanted to obtain a deeper understanding as well.

**Comment by tghani93** [comment]
And please excuse my ignorance & naivety, how does Zerocode compares to: https://www.testcontainers.org/ 
The reason I am asking is as above that I an trying to push zerocode as first preference and would like an expert opinion. TIA

**Comment by authorjapps** [comment]
> Yes secure APIs as you mentioned and in general as well :)
> I am planning on doing a blog about Zerocode also, so wanted to obtain a deeper understanding as well.

That sounds cool. 👍 

- For Oauth2 one of our contributor(and user) has shared a very short and precise blog in the [DZone Security Zone](https://dzone.com/articles/oauth2-authentication-in-zerocode).
I am tagging him(@santhoshTpixler ) here in case you need more details on this.
- For Corporate Proxy configuration, you can follow the README section [here](https://github.com/authorjapps/zerocode#soap-method-invocation-where-corporate-proxy-enabled)
  - This is for any Http api invocation, for instance REST, SOAP etc
- SAML/JWT are very straight forward - working examples are [here - HelloWorld](https://github.com/authorjapps/zerocode#using-any-properties-file-key-value-in-the-steps) repo
- If tokens are dynamic, it's still easy to inject them into header in runtime.
   - @santhoshTpixler has explained in his blog
- If you use OpenAM or RedHat SSO or Simple Basic Auth
   - You can refer the examples in readme-file [here](https://github.com/authorjapps/zerocode#http-basic-authentication-step-using-zerocode)
   - You can manually use per test-case wise or embed it to the HttpClient which is oneoff( and less maintenance overhead)

- Currently Zerocode's Http Client supports Http and Https connections.
   - But you can override and add/remove security features to match your project requirement.
   - See example [here - in HelloWorld](https://github.com/authorjapps/zerocode-hello-world/blob/master/src/main/java/org/jsmart/zerocode/zerocodejavaexec/httpclient/CustomHttpClient.java#L46)
```
    @Override
    public CloseableHttpClient createHttpClient() throws NoSuchAlgorithmException, KeyManagementException, KeyStoreException {
        LOGGER.info("###Used SSL Enabled Http Client for http/https/TLS connections");

       // Add your own security flavour and return the client, 
       // then all test-cases will start using this client.
       // That's it really!

        return HttpClients.custom()
                .setSSLContext(sslContext)
                .setSSLHostnameVerifier(new NoopHostnameVerifier())
                .setDefaultCookieStore(cookieStore)
                .build();
    }
```   

- Then it's very simple and straight forward to use like below-
> Just annotate your test class or suite class.

```
@UseHttpClient(CustomHttpClient.class)
```

- In similar fashion, you can inject any custom headers you need. [Explained here](https://github.com/authorjapps/zerocode-hello-world/blob/master/src/main/java/org/jsmart/zerocode/zerocodejavaexec/httpclient/CustomHttpClient.java#L67)
e.g.
```
    @Override
    public Map<String, Object> amendRequestHeaders(Map<String, Object> headers) {
        // ----------------------------------------------------
        // Add your custom headers here(if any).
        // e.g. Your auth tokens, client_id or client_secret etc
        // ----------------------------------------------------
        if (headers != null) {
            addCustomHeaders(headers);
        } else {
            headers = new HashMap<>();
            addCustomHeaders(headers);
        }

        return headers;
    }
```

**Comment by authorjapps** [comment]
> And please excuse my ignorance & naivety, how does Zerocode compares to: https://www.testcontainers.org/
> The reason I am asking is as above that I an trying to push zerocode as first preference and would like an expert opinion. TIA

These two are very different tools for different purposes not worth comparing.
> testcontainers.org >>Mostly for anything ... that can run in a Docker container.

Zerocode is for 
+ Application Integration Testing
+ End to End testing
+ System Integration testing
+ Load/Stress testing
+ API Mock making (using wiremock JSON DSLs)

in a declarative way reducing the hassles to zero for Developers/Testers.

But on the feature-comparison front-
We are in the process of collecting the feedback/data from our customers to capture why they are migrating from their existing tools to Zerocode e.g. 
1. From Postman to Zerocode 
1. From other Step-Definition based BDD tools to Zerocode etc.

We will spin up a Wiki page or a Google doc once that's ready. That might throw some light on this line.

But our advise will be choose a tool/lib/framework
- Which is easy to use
- Less syntax overhead
- Easy dealing with payload
- Easy to extend the test runners
- easy to add custom security featured
- Easy for manual testers to understand the test flow

Hope this helps!

Also we are excited to see your blog when it's ready ❗️ 

and wish you good luck 🙏

**Comment by tghani93** [comment]
@authorjapps , very grateful for your responses and pointers. Will have keep you posted on the blog! :)

**Comment by tghani93** [comment]
@authorjapps, just letting you know that I will be recycling some of your awesome pointers above in the blog!! :)

**Comment by authorjapps** [comment]
Sounds cool mate. 👍 
Please try to keep the blog precise/short, easily understandable for first timers as well as experience developer/testers :-)
Good luck!
