### ISSUE TITLE
Step externalise and reuse

### ISSUE THREAD

**Issue by saurabhvalsangkar** [authorjapps/zerocode#224]
Given: Scenario step in json file format
When: Used in multi step json test case
Then: I should be able to use the step from external json file 

Example:

```
{
    "scenarioName": "GitHub GET API and more @@Alex",
    "steps": [
        {
            "id" : "step1",
            "stepFile": "${JSON.FILE:steps/step1.json}"

        },
        {
            "id": "step2",
            "stepFile": "${JSON.FILE:steps/step2.json}"
        }
    ]
}
```
e.g.
step1.json
----------

```json
        {
            "name": "get_user_details",
            "url": "/users/octocat",
            "operation": "GET",
            "request": { },
            "assertions": {
                "status": 200
            }
        }
```

**Comment by saurabhvalsangkar** [comment]
I am picking up this issue

**Comment by authorjapps** [comment]
PR approved and merged to master.
This is included in the coming release.
```
<!-- https://mvnrepository.com/artifact/org.jsmart/zerocode-tdd -->
<dependency>
    <groupId>org.jsmart</groupId>
    <artifactId>zerocode-tdd</artifactId>
    <version>1.3.6</version>
</dependency>
```

**Comment by authorjapps** [comment]
@saurabhvalsangkar, 

Could you please 
- Join the collaborators mailing list 
https://groups.google.com/forum/#!members/zerocode-automation

- Join Gitter room
https://gitter.im/zerocode-testing/help-and-usage

- Accept this invitation?
https://github.com/authorjapps/zerocode/invitations

Thanks
