### ISSUE TITLE
Adding support for JUnit 5 

### ISSUE THREAD

**Issue by dmuravov** [authorjapps/zerocode#226]
Currently Zerocode works in combination with JUnit 4. 
It would be very good to introduce possibility to run with JUnit 5.

I have tried to use maven-dependency "junit-vintage-engine" to simulate jUnit 4 behavior but it did not work out. Otherwise if there is a project-wide decision to use JUnit 5 then it is not good to implement hacks to "downgrade" the tests to JUnit 4.

**Comment by aghorpade** [comment]
If JUnit5  has specific feature of functionality whih we are expecting in current project structure then it make sense to upgrade to JUnit5 else it will be burden to get new version n code changes too.

**Comment by authorjapps** [comment]
> if there is a project-wide decision to use JUnit 5 then it is not good to implement hacks to "downgrade" the tests to JUnit 4.

Makes sense @dmuravov .
Already created a project for this just now. Let's kickoff from there.

> If JUnit5 has specific feature of functionality whih we are expecting in current project structure then it make sense to upgrade to JUnit5 

Fully agree with you @aghorpade .

Therefore with this we need to-
+ keep the support up for JUnit4 - For existing customers
+ Add JUnit5 integration in a new maven module
+ List out IDE supports warnings
   + Some(old) version of IntelliJ/Eclipse doesn't have JUnit5 support
   + List which IDE vesrions version supporting JUnit5

**Comment by authorjapps** [comment]
> Currently Zerocode works in combination with JUnit 4.
> It would be very good to introduce possibility to run with JUnit 5.
> 
> I have tried to use maven-dependency "junit-vintage-engine" to simulate jUnit 4 behavior but it did not work out. Otherwise if there is a project-wide decision to use JUnit 5 then it is not good to implement hacks to "downgrade" the tests to JUnit 4.

In the mean time, while we provide `extensions` for JUnit5, which is a bit involving work, you can still use JUnit5 as explained below(this is not a hack, you can still have both JUnit4 and JUnit5 tests and run them at the same time, - not a blocker). See [HelloWorld branch - junit5_working](https://github.com/authorjapps/zerocode-hello-world/tree/junit5_working/src/test/java/org/jsmart/zerocode/testhelp/tests) with newly added JUnit5 tests. Look inside `junit5` package.

That's not really an issue to maintain both tests, as explained here [JUnit5 user-guide](https://junit.org/junit5/docs/current/user-guide/#migrating-from-junit4)
> Since all classes and annotations specific to JUnit Jupiter reside under a new org.junit.jupiter base package, having both JUnit 4 and JUnit Jupiter in the classpath does not lead to any conflicts.

Now coming back to-
> I have tried to use maven-dependency "junit-vintage-engine" to simulate jUnit 4 behavior

Which version you were experimenting with? We tried this `5.4.1`(which has `junit 4.12` inside it) adding to HelloWorld repo. The existing tests(annotated with `@Test` of  `org.junit.Test` are running fine) as well as the Jupiter tests(annotated with `@Test` of  `org.junit.jupiter.api.Test`) also.
+ Existing JUnit4 tests - See [JustHelloWorldTest](https://github.com/authorjapps/zerocode-hello-world/blob/junit5_working/src/test/java/org/jsmart/zerocode/testhelp/tests/helloworld/JustHelloWorldTest.java).

> Note- This is important. This @Test annotation decides which JUnit runner to pick. So please make sure you use `import org.junit.Test;` for zerocode tests.

For clarity, you can clone [this repo](https://github.com/authorjapps/zerocode-hello-world/tree/junit5_working) and run from your IDE as well as maven command line.

+ New JUnit5 Tests - See [FirstTest](https://github.com/authorjapps/zerocode-hello-world/blob/junit5_working/src/test/java/org/jsmart/zerocode/testhelp/tests/junit5/FirstTest.java)
   + org.jsmart.zerocode.junit5.FirstTest
https://search.maven.org/artifact/org.junit.vintage/junit-vintage-engine/5.4.1/jar

```xml
<?xml version="1.0" encoding="UTF-8"?>
  ...
  <groupId>org.junit.vintage</groupId>
  <artifactId>junit-vintage-engine</artifactId>
  <version>5.4.1</version>
  <name>JUnit Vintage Engine</name>
  <description>Module "junit-vintage-engine" of JUnit 5.</description>
  <url>https://junit.org/junit5/</url>
  ...
  ...
  <dependencies>
      ...
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.12</version>
      <scope>runtime</scope>
    </dependency>
  </dependencies>
</project>
```

Now, just to clarify, when you use `junit-jupiter` with `junit.vintage` like below,
> where - `junit-jupiter = junit-jupiter-engine + junit-jupiter-api`
 
```xml
	<properties>
		<junit.jupiter.version>5.4.1</junit.jupiter.version>
		<junit.vintage.version>5.4.1</junit.vintage.version>
	</properties>

...
                <dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter</artifactId>
			<version>${junit.jupiter.version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.junit.vintage</groupId>
			<artifactId>junit-vintage-engine</artifactId>
			<version>${junit.vintage.version}</version>
		</dependency>
```

then, make sure you annotate your `zerocode` test methods with 
> org.junit.Test

e.g.
```java
import org.jsmart.zerocode.core.domain.JsonTestCase;
import org.jsmart.zerocode.core.domain.TargetEnv;
import org.jsmart.zerocode.core.runner.ZeroCodeUnitRunner;
import org.junit.Test;  //<--------------- Important
import org.junit.runner.RunWith;

@TargetEnv("github_host.properties")
@RunWith(ZeroCodeUnitRunner.class)
public class JustHelloWorldTest {

    @Test
    @JsonTestCase("helloworld/hello_world_status_ok_assertions.json")
    public void testGet() throws Exception {
    }

}
```

Hope this helps!

As mentioned earlier, in the meantime, we will be creating the `JUnit5` extensions and keep you posted 👍

**Comment by siddhagalaxy** [comment]
Basically, the point here is to use

1. #### JUnit 4 tests either existing or new ones

> `@Test`  which is => import org.junit.Test;

2. #### JUnit Jupiter tests either existing or new ones

> `@Test`  which is => import org.junit.jupiter.api.Test

e.g.

1
===

```
import org.jsmart.zerocode.core.domain.JsonTestCase;
import org.jsmart.zerocode.core.domain.TargetEnv;
import org.jsmart.zerocode.core.runner.ZeroCodeUnitRunner;
import org.junit.Test;  //<--------------- Important
import org.junit.runner.RunWith;

@TargetEnv("github_host.properties")
@RunWith(ZeroCodeUnitRunner.class)
public class JustHelloWorldTest {

    @Test
    @JsonTestCase("helloworld/hello_world_status_ok_assertions.json")
    public void testGet() throws Exception {
    }

}

```

2
===
```
import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;  //<--------------- Important
import org.junit.jupiter.api.TestInfo;

@Tag("fast")
class FirstTest {

	@Test
	@DisplayName("My 1st JUnit 5 test! 😎")
	void myFirstTest(TestInfo testInfo) {
		Calculator calculator = new Calculator();
		assertEquals(2, calculator.add(1, 1), "1 + 1 should equal 2");		
	}

}
```

And they can co-exist without any conflict as explained in the earlier comment. 👍

**Comment by dmuravov** [comment]
Gentlemen, thank you very much for your time and recommendations! I'll try it out.
D. Muravov

**Comment by authorjapps** [comment]
Understood your issue now. Good that you have put exact details 👍 

Basically the tests not only co-habited, but also married :-)

This setup won't work until JUnit5 is supported. _You were right in the beginning._
Below explains why it won't-
```
import org.junit.jupiter.api.Test;  <------- This is JUnit5 (Jupiter)
import org.junit.runner.RunWith; <------- This is JUnit4

@RunWith(ZeroCodeUnitRunner.class) <------- This is JUnit4 runner
public class PdfSingleCallsTest {

    @Test <------- This is JUnit5 (Jupiter)
    public void testThumbnailApache_ComplexPdf() {
        // checks some functionality ABC
    }

    @Test
    public void testThumbnailQoppa_ComplexPdf() {
        // checks some functionality XYZ
    }
    ....
```
JUnit5 tests cases can not be run via JUnit4 runners.

But what can we run(which you already might be knowing) is-
_The following is just for clarification for readers only._ 

- In the same project, we can have JUnit4 and JUnit 5 tests separately and run them.

But what we can't run is-
- Junit5 tests(methods annotated with Juiter `@Test`) via JUnit4 runner.

**Comment by authorjapps** [comment]
We are in the process of creating the `JUnit5 Jupiter extension` for the load generation.
An example PR is here for preview.
https://github.com/authorjapps/performance-tests/pull/3/files

It's much more flexible than before due to JUnit5 engine flexibility.

Please have a look at the below parallel load examples-
+ JUnit5LoadTest.java
+ JUnit5LoadCommonLoadTest.java
+ JUnit5LoadDifferentLoadTest.java

We are almost there and the PR is still under review by the collaborators.
We will release it soon(in a week types) 👍

**Comment by dmuravov** [comment]
@authorjapps thank you a lot for your time & efforts!

**Comment by authorjapps** [comment]
Thanks @dmuravov , It's a pleasure for us!

Could you please (when u get chance)

Join the collaborators mailing list
https://groups.google.com/forum/#!forum/zerocode-automation

Join Gitter room
https://gitter.im/zerocode-testing/help-and-usage

Cheers 👍

**Comment by authorjapps** [comment]
Wiki Page link:
https://github.com/authorjapps/zerocode/wiki/JUnit5-Jupiter-Parallel-Load-Extension
