### ISSUE TITLE
Test suite - Select tests by cherry-picking from test resources

### ISSUE THREAD

**Issue by siddhagalaxy** [authorjapps/zerocode#229]
GIVEN I have scenario tests organized/maintained in the resources as usual
WHEN I cherry-pick to run some/subset of the tests by their relative paths
THEN I should be able to run them as a Suite

e.g.
I am looking for something like below to be supported for my test run.
```java
@TargetEnv("server_dev1.properties")
@RunWith(ZeroCodePackageRunner.class)
@JsonTestCases({
        @JsonTestCase("path1/scenario1.json"), //cherry-picked
        @JsonTestCase("path2/scenario-2.json"), //cherry-picked
})
public class MySelectedCherryPickedSuite {
}
```

### Why/When this is useful?
Currently the framework provides two different way of running the tests as a suite
+ Selecting a package - Picks tests from folders and subfolders of this folder
+ Usual JUnit Suite - Select Test classes
> This is great and covers 99% of the scenarios

But my use case is when I identify some tests e.g. I want to fire some tests against the `GateWays` or some tests to check the `Security` aspects of my server, or a couple of tests to validate the `Kafka pipeline` is up and running(kind of health check).

Then, I should be able to pick the tests directly(straight forward by their path) and spin up a Test-Suite and run them. 

At the same time I don't want the overhead/round-about-way of going to the tests and tagging them and pick the tests by their tag names, then bring up a runner for the tags etc.

**Comment by nirmalchandra** [comment]
Initial implementation done.
PR link: https://github.com/authorjapps/zerocode/pull/230

**Comment by nirmalchandra** [comment]
PR has been approved and merged to master.
This will be included in the coming release.
```xml
<!-- https://mvnrepository.com/artifact/org.jsmart/zerocode-tdd -->
<dependency>
    <groupId>org.jsmart</groupId>
    <artifactId>zerocode-tdd</artifactId>
    <version>1.3.6</version>
</dependency>
```

**Comment by authorjapps** [comment]
Visit HelloWorld example repo for a sample `Suite` at the below location.
```
.../zerocode-hello-world/src/test/java/org/jsmart/zerocode/testhelp/tests/HelloWorldSelectedCherryPickedTestSuite.java
```
