### ISSUE TITLE
Create short duration YouTube video Template - 3 to 5mins

### ISSUE THREAD

**Issue by authorjapps** [authorjapps/zerocode#231]
A video explanation or presentation of various features of Zerocode will certainly help the community who starts their journey with Zerocode or migrate to Zerocode.

Create a sample YouTube video which can be used as an example (or template) for other future videos in this line.
Basically once the video has been created it can be uploaded to not only YouYube, but also other video supporting/streaming portals.

### What to cover in the video and when?
> Basically what will be the structure/pattern of this video?

+ Keep the video short - 3 to 5mins only
+ 1st min - Highlight the testing challenge during API development - Pick REST for easiness
+ 2nd min - Challenges met by Auto-Testers/Developers as well as by the available testing frameworks
+ 3rd min - How Zerocode approaches the problem and solves it
+ 4th min - Provide Code example and explain how to run from a IDE
+ 5th min - Show reports and logs generated to trace/filter a failure/failed step

**Comment by BabiNick** [comment]
Hi @authorjapps, I'm a little confused as to what you're asking for. 
1. A video to explain the challenges of API Development and Zerocode's solution to the challenges faced.
2. Video template that can be re-used. Does that mean making clips of slides that are generic with different themes along with a folder of suitable royalty free music to be used for the video?

**Comment by tripleratamacue** [comment]
This guy created one, that covers some areas mentioned: https://www.youtube.com/watch?v=YCV1cqGt5e0

**Comment by authorjapps** [comment]
> This guy created one, that covers some areas mentioned: https://www.youtube.com/watch?v=YCV1cqGt5e0

This video doesn't seem very structured, though it explains some aspects of the framework. Also, the video is a bit longer(around 15min+). A `5 min type` video is better if created.

I think we need some kind of template(btw I am not too sure if it is even possible to create a video template at all or not), so that we can keep the template and fit new contents to create new videos(basically reuse the template). I might be totally wrong here.... but open for ideas from video-makers or experts in this subject.

Or simply create a 5min video which addresses [these points](https://github.com/authorjapps/zerocode/issues/231#issue-435451991)

**Comment by hmellin97** [comment]
Hello! We are two people who would like to resolve this issue.

**Comment by PaulLowenstrom** [comment]
@authorjapps Me and @hmellin97 would like to give this issue a go

**Comment by authorjapps** [comment]
Thanks @PaulLowenstrom @hmellin97 for your interest. Please go ahead. 👍 
It would be nice if you could share a draft version of this when you are ready.

**Comment by PaulLowenstrom** [comment]
Hi, here is our first draft. We took inspiration from your motivation wiki. This draft contains the main structure of the video and our interpretation of the task. So if there is anywhere misunderstood you can help correct us. The document also contains some questions where we are unsure about the task.

Do you prefer a video with text or a voice explaining the video?

Here is a link to the document
https://docs.google.com/document/d/1d9IsQyDxUCdttnRSlPWRTC49Vb3cXCxNhDjB6jyaD74/edit?usp=sharing

**Comment by hmellin97** [comment]
https://youtu.be/t-Q4690n2GQ

A short example of how the video could look like.

**Comment by hmellin97** [comment]
https://www.youtube.com/watch?v=J4MbfB17JjU&feature=youtu.be

Here is the final result of our work. Enjoy!

**Comment by authorjapps** [comment]
Thanks for your hard work. I have seen the content you have nicely captured into the Google Slides fed into the YouTube.
Appreciate the effort and creativity!
