### ISSUE TITLE
Unable to compile and install zerocode

### ISSUE THREAD

**Issue by chaitra1604** [authorjapps/zerocode#240]
Have downloaded the master version of zerocode
when running below, seeing error as

mvn clean install -DskipTests

Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-enforcer-plugin/1.2/maven-enforcer-plugin-1.2.pom
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for ZeroCode TDD Parent 1.3.8-SNAPSHOT:
[INFO]
[INFO] ZeroCode TDD Parent ................................ FAILURE [02:07 min]
[INFO] Zerocode TDD Core .................................. SKIPPED
[INFO] Zerocode Http Testing Simple JSON DSL .............. SKIPPED
[INFO] Zerocode Kafka Testing Simple JSON DSL ............. SKIPPED
[INFO] Zerocode JUnit5 Jupiter Testing .................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:08 min
[INFO] Finished at: 2019-05-13T14:26:26+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Plugin org.apache.maven.plugins:maven-enforcer-plugin:1.2 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-enforcer-plugin:jar:1.2: Could not transfer artifact org.apache.maven.plugins:maven-enforcer-plugin:pom:1.2 from/to central (https://repo.maven.apache.org/maven2): Connect to repo.maven.apache.org:443 [repo.maven.apache.org/151.101.120.215] failed: Connection timed out (Connection timed out) -> [Help 1]
[ERROR]

**Comment by authorjapps** [comment]
@chaitra1604 , the error message shows the cause-
> Connect to repo.maven.apache.org:443 [repo.maven.apache.org/151.101.120.215] failed: Connection timed out (Connection timed out) 

Please check your `.m2` settings.

Gitter is the best forum for this kind of question. You get a better response there.

Could you please

Join the collaborators mailing list
https://groups.google.com/forum/#!forum/zerocode-automation

Join Gitter room
https://gitter.im/zerocode-testing/help-and-usage

Cheers 👍
