### ISSUE TITLE
Console Report missing assertions section for failed step

### ISSUE THREAD

**Issue by siddhagalaxy** [authorjapps/zerocode#241]
Hello Folks, 
It seems like there is a minor bug introduced while printing the correlated test results/assertions.

### Reproduction
- Fail a test step in the scenario/journey
- See the console and look for the failed step
- After request/response section we used to see the `assertions` section.
  - > it used to be handy
- Now we don't see that. But we see all mismatches as usual(no changes)
- FYI- We see this `assertions` section for the passed steps.
Hence looks like a minor one.

Could you please check?

**Comment by jneate** [comment]
@authorjapps - I've fixed the issue raised here but some clarification on the implementation approach would be good, the code logs the "assertions" payload on success and the "assertion" errors on failure; this appears to be the original intention.

Proposed Options/Solutions:

Option 1)
Output both the expected/assumed payload along with the errors:
![image](https://user-images.githubusercontent.com/14006260/58133497-e0439f00-7c1b-11e9-95ce-99a2b64e01f7.png)

Pros:- Both the payload and error are displayed
Cons:- The raw test JSON generated isn't strictly valid JSON for the field "assumptions"
![image](https://user-images.githubusercontent.com/14006260/58133582-1a14a580-7c1c-11e9-87ef-93afcc61c246.png)

Option 2)
Change the code to output only the expected/assumed payload

Pros:- Output is as it was before
Cons:- Assertion errors are hidden from the user and only visible at the top of the log
![image](https://user-images.githubusercontent.com/14006260/58133836-e1290080-7c1c-11e9-9e86-c63d5c89aba5.png)
![image](https://user-images.githubusercontent.com/14006260/58133817-d2424e00-7c1c-11e9-8f32-da7696684517.png)

Option 3)
Leave the code as it is currently

Pros:- User can see the assertion errors
Cons:- User is missing the expected/assumed payload (and rightly raising an issue)

Option 4)
Same as Option 1 except we have a field for the assertionPayload and another for the assertionErrors

assertionPayload contains JSON Object
assertionErrors contains an Array of Strings

Personally I'd go for 1 or 4 but happy to follow whichever.

Thanks,
James

**Comment by authorjapps** [comment]
Thanks mate, that's very very neat explanations. Cool stuff!
> Personally I'd go for 1 or 4 but happy to follow whichever.

I am with you on this.

Just one thing we need to regress here is-
The list of failures which are printed to console, are also displayed in the html result.
This was just done recently by one of our committer for their containerized(dockerized) build, as they were loosing the log files in the CI-Pipeline(hence wanted those failures in the HTML report).

IMHO we can go for Option-1 now i.e. how originally it was. Also same time we need to make sure the HTML report should contain the failures-list(existing behaviour basically). A screen shot is here-

![image](https://user-images.githubusercontent.com/12598420/58165864-8b863f80-7c80-11e9-8d98-f2e2cfdd8aa0.png)

FYI- You can fail a test from your IDE and view the HTML report `zerocode-junit-interactive-fuzzy-search.html` in the target folder. Just expand the failed step.

**Comment by jneate** [comment]
@authorjapps This is how Option 1 appears in the HTML report

![image](https://user-images.githubusercontent.com/14006260/58166462-ca68c500-7c81-11e9-9727-a903a1e023d5.png)

If you're happy then I'll raise a PR after work.

**Comment by authorjapps** [comment]
This looks fantastic 👍 and much better now.

**Comment by authorjapps** [comment]
Thanks James.
Overall it looks great. I have put some minor comments to take care please.

Also added couple of more collaborators to review it.
We should be able to merge it soon after that.

Thanks for the clean code, test coverage n appreciate your time! 

@santhoshTpixler @BeTheCodeWithYou @officiallysameer @siddhagalaxy - For your review pls.

**Comment by jneate** [comment]
@authorjapps Refactored based on review comments 👍

**Comment by authorjapps** [comment]
Released version
```xml
<dependency>
  <groupId>org.jsmart</groupId>
  <artifactId>zerocode-tdd</artifactId>
  <version>1.3.8</version>
</dependency>
```
