### ISSUE TITLE
Cleanup unused maven-depencencies

### ISSUE THREAD

**Issue by dmuravov** [authorjapps/zerocode#244]
After installing/using zerocode-tdd-jupiter-1.3.7 in our build-pipeline we have detected some useless dependencies like this one (commons-httpclient stemms from 2008):
                <exclusion>
                    <groupId>commons-httpclient</groupId>
                    <artifactId>commons-httpclient</artifactId>
                </exclusion>

Proposal: cleanup such senseless dependencies since they have impact on the classpath in the test-setup thus influencing indirectly the software under test.

**Comment by nirmalchandra** [comment]
@dmuravov , understood. We will sort this out for you soon.
Looks like the dependent lib brings in the other libs(unwanted) transitively e.g. `httpclient` etc.

Exclusion of that lib manually may not be a good fix, but for temporarily you can do that to make your build happy(until we provide a fix/release).
```
        <dependency>
            <groupId>org.jsmart</groupId>
            <artifactId>zerocode-tdd-jupiter</artifactId>
            <version>1.3.7</version>
            <exclusions>
                <exclusion> 
                    <groupId>org.apache.httpcomponents</groupId>
                    <artifactId>httpclient</artifactId>
                </exclusion>
                <!-- Dependency to exclude. Version number is not needed. -->
            </exclusions>
        </dependency>

```

Thanks for understanding ✌

We have plans of making these dependencies strictly managed, which will make things lot cleaner.

**Comment by dmuravov** [comment]
@nirmalchandra thanks for the comment. Yes, I do use exclusion-mechnism of maven. For ex., in my case (a spring-boot back-end app with jUnit5-tests only) we have the following constellation (s. below). 

>          
>         <dependency>
>             <groupId>org.jsmart</groupId>
>             <artifactId>zerocode-tdd-jupiter</artifactId>
>             <version>1.3.7</version> 
>             <scope>test</scope>
>             <exclusions>
>                 <exclusion>
>                     <groupId>com.fasterxml.jackson.datatype</groupId>
>                     <artifactId>jackson-datatype-jdk8</artifactId>
>                 </exclusion>
>                 <exclusion>
>                     <groupId>org.apache.kafka</groupId>
>                     <artifactId>kafka-clients</artifactId>
>                 </exclusion>
>                 <exclusion>
>                     <groupId>com.google.code.gson</groupId>
>                     <artifactId>gson</artifactId>
>                 </exclusion>
>                 <exclusion>
>                     <groupId>com.google.inject</groupId>
>                     <artifactId>guice</artifactId>
>                 </exclusion>
>                 <exclusion>
>                     <groupId>com.google.classpath-explorer</groupId>
>                     <artifactId>classpath-explorer</artifactId>
>                 </exclusion>
>                 <exclusion>
>                     <groupId>com.google.guava</groupId>
>                     <artifactId>guava</artifactId>
>                 </exclusion>
>                 <exclusion>
>                     <groupId>junit</groupId>
>                     <artifactId>junit</artifactId>
>                 </exclusion>
>                 <exclusion>
>                     
>                     <groupId>javax.activation</groupId>
>                     <artifactId>activation</artifactId>
>                 </exclusion>
>                 <exclusion>
>                     <groupId>javax.annotation</groupId>
>                     <artifactId>jsr250-api</artifactId>
>                 </exclusion>
>                 <exclusion>
>                     <groupId>commons-httpclient</groupId>
>                     <artifactId>commons-httpclient</artifactId>
>                 </exclusion>
>                 <exclusion>
>                     <groupId>aopalliance</groupId>
>                     <artifactId>aopalliance</artifactId>
>                 </exclusion>
>                 <exclusion>
>                     <groupId>aopalliance</groupId>
>                     <artifactId>aopalliance</artifactId>
>                 </exclusion>
>                 <exclusion>
>                     <groupId>org.junit.vintage</groupId>
>                     <artifactId>junit-vintage-engine</artifactId>
>                 </exclusion>
>                 <exclusion>
>                     <groupId>org.junit.platform</groupId>
>                     <artifactId>junit-platform-runner</artifactId>
>                 </exclusion>
>                 <exclusion>
>                     <groupId>com.aventstack</groupId>
>                     <artifactId>extentreports</artifactId>
>                 </exclusion>
>                 <exclusion>
>                     <groupId>org.skyscreamer</groupId>
>                     <artifactId>jsonassert</artifactId>
>                 </exclusion>
>                 <exclusion>
>                     <groupId>com.jayway.jsonpath</groupId>
>                     <artifactId>json-path</artifactId>
>                 </exclusion>
>                 <exclusion>
>                     <groupId>com.github.tomakehurst</groupId>
>                     <artifactId>wiremock</artifactId>
>                 </exclusion>
>                 <exclusion>
>                     <groupId>ch.qos.logback</groupId>
>                     <artifactId>*</artifactId>
>                 </exclusion>
>             </exclusions>
>         </dependency>

**Comment by authorjapps** [comment]
Oh! That's painful indeed. So sorry to see that.
We will sort that out soonish!

We will prioritize this issue soon.
Thanks for your patience.

**Comment by authorjapps** [comment]
Before fix(current):
[before_fix_dependency_tree_.txt](https://github.com/authorjapps/zerocode/files/3244968/before_fix_dependency_tree_.txt)

After fix:
[after_fix_dependency_tree_.txt](https://github.com/authorjapps/zerocode/files/3244967/after_fix_dependency_tree_.txt)

**Comment by authorjapps** [comment]
Released version
```xml
<dependency>
  <groupId>org.jsmart</groupId>
  <artifactId>zerocode-tdd-jupiter</artifactId>
  <version>1.3.8</version>
</dependency>
```
