### ISSUE TITLE
Apache Http Client With Configurable Retry count

### ISSUE THREAD

**Issue by dinesh76in** [authorjapps/zerocode#246]
Hello,
Can we configure the(a) `retry court` or override the retry count ?
My usecase is to retry the Http call for a configurable value only if the assertions fail.
Otherwise I don't need retry count.

e.g. if my data write has some delay, then my read should try for few retries.

That means I should be able to retry `n` times with `x` time gap between the retries.
 
Please provide us
+ Global retries
   + Meaning - Applies to all test steps(scenarios)
+ Local retries
   + Meaning - Applies to only this specific test step(s)

**Comment by BartRobeyns** [comment]
Hi @dinesh76in, I've tried to cover the second part: 'Local retries'. PR #263 would allow you to add
`"retry": {"max": 12, "delay": 100}`
at each step.
In the sample, the request would be retried 12 times at most, with 100ms waiting time in between. As soon as the assertions succeed, the step is succesfully ended. If based on the 12th request the assertions still fail, the step is marked as failing.

I don't see the use case for a global (scenario-level) retry; could you explain when you'd want to do that?

**Comment by authorjapps** [comment]
Available in release `1.3.12`
