### ISSUE TITLE
H2DBTest fails on authentication

### ISSUE THREAD

**Issue by BartRobeyns** [authorjapps/zerocode#251]
The test fails with:
org.h2.jdbc.JdbcSQLException: Wrong user name or password [28000-191]

AFAIK the default username for h2db is "sa" (with blank password); the test doesn't set any username on connecting to the db.

**Comment by BartRobeyns** [comment]
My mistake: if there's already a test-database in the user's home folder with a password set, if fails. This was my situation. So the problem isn't a wrong username/password, rather it's writing outside of the project-folder.
Changing the db-path from ~/test to ./target/test would ensure the db is private to the zerocode tests.

**Comment by authorjapps** [comment]
Version 1.3.9
