### ISSUE TITLE
WireMock is not correctly restarted between tests

### ISSUE THREAD

**Issue by BartRobeyns** [authorjapps/zerocode#255]
The current implementation tries to stop a previously existing WireMock instance, before starting a new one. However, the previously existing one is overwritten by the new before the stop-method is called.

**Comment by authorjapps** [comment]
@BartRobeyns , Thanks for the PR. 

We are goign through the PR.
Just for everyone's benefit , can you please put some light on the below.
_(Also it will help the users to understand its usage)_
```
"body":{
    "fixed_date_time": "${LOCAL.DATETIME.NOW:uuuu-MM-dd HH:mm:ss.SSS}",
    "dynamic_oneMinuteAgo": "{{now offset='-1 minutes' format='yyyy-MM-dd HH:mm:ss.SSS'}}",
    "dynamic_oneMinuteAhead": "{{now offset='+1 minutes' format='yyyy-MM-dd HH:mm:ss.SSS'}}",
    "ucparam": "{{upper request.query.param[0]}}"
}

```
from the PR [file](https://github.com/authorjapps/zerocode/pull/259/files#diff-4221aab085d448fba1cb91c5a0610fe9)

Also
```
            "assertions": {
                "status": 200,
                "body": {
                    "ucparam": "LOWERTOUPPER"
                    // Once PR#249 is accepted, "fixed_date_time": "$DATE.AFTER${$.GetTemplate.response.dynamic_oneMinuteAgo}"
                    // and "fixed_date_time": "$DATE.BEFORE${$.GetTemplate.response.dynamic_oneMinuteAhead}"
                    // should work
                }
            }
```

**Comment by authorjapps** [comment]
Version 1.3.9
