### ISSUE TITLE
response time delay in millisec

### ISSUE THREAD

**Issue by nirmalchandra** [authorjapps/zerocode#26]
@authorjapps , Currently the time difference between the `requestTimeStamp` and `responseTimeStamp` seems like done on the `millisecs` part only.

e.g.
```
requestTimeStamp: "2018-02-05T19:46:31.631"
responseTimeStamp: "2018-02-05T19:46:32.731"
```
Then the response time delay should be:
```
responseTimeDelay: 1100 milli seconds 
ie (32-31=1sec=1000 millisec) + (731-631=100 millisec) = 1100 milli sec
```

But it prints(`I think so`):
```
responseTimeDelay: 100 milli seconds 
```

**Comment by authorjapps** [comment]
Fixed.
Available in version `1.1.23` or higher. 
See [Maven Central](http://search.maven.org/#search%7Cga%7C1%7Czerocode) for the latest release.
