### ISSUE TITLE
Modification of random number implementation

### ISSUE THREAD

**Issue by santhoshTpixler** [authorjapps/zerocode#279]
At present `${RANDOM.NUMBER}` is replaced by `System.currentMilliSecs`.
Due to this implementation, multiple occurrences of the place holder in the same step are replaced with the same value. It is also misleading the users.

**Problem:** A step cannot have multiple distinct random numbers.
**Solution:** Modify the implementation to produce a random number using System library.

A new place holder can be introduced for `currentMilliSecs`

**Comment by authorjapps** [comment]
@santhoshTpixler , can you please pick this ticket(when you get chance)? Thanks 👍

**Comment by authorjapps** [comment]
Wiki Page updated for usage and limit which provides a mechanism for various random number generation.
https://github.com/authorjapps/zerocode/wiki/Placeholders-Usage-and-Limits
