### ISSUE TITLE
ZeroCodeReportGeneratorImpl makes deadlock while load testing

### ISSUE THREAD

**Issue by ivlahek** [authorjapps/zerocode#281]
ZeroCodeReportGeneratorImpl makes deadlock when writing the CSV report to file.
I am referring to your test LoadExistingJUnitRestTest.

For example, if you set in your properties files following properties
number.of.threads=20
ramp.up.period.in.seconds=10

You will make a deadlock. 
In the end, all threads will try to write a CSV report to the same file. The first thread will write, then second will try to write, third will try to write etc...  
and you will encounter that all ExecutorService in ExecutorServiceRunner.class has 20 threads, all working something, but all have executed the test method ....

When you remove @RunWith(ZeroCodeUnitRunner.class) from the LoadExistingJUnitRestTest everything works fine.

**Comment by santhoshTpixler** [comment]
@ivlahek I couldn't find the test mentioned 
> I am referring to your test LoadExistingJUnitRestTest.

**Comment by ivlahek** [comment]
Hi,

I was referring to this test https://github.com/authorjapps/performance-tests/blob/master/src/test/java/org/jsmart/zerocode/samples/load/samplejunit/LoadExistingJUnitRestTest.java.

**Comment by vkjha2000** [comment]
We ran with your config just now.
PFA the results here. All were fine 👍 

I would suggest- Can you please clean(`mvn clean`) your `target` folder and rerun the load test from IDE or via maven command?
or/and
Close the CSV report file first(if opened already), then run the load test with removing the target folder(`mvn clean`).

<img width="1163" alt="load csv" src="https://user-images.githubusercontent.com/12785019/62182946-9d701700-b382-11e9-8fe2-e894e068244d.png">

<img width="671" alt="load gen" src="https://user-images.githubusercontent.com/12785019/62182947-9d701700-b382-11e9-8b76-ccbb296cf521.png">

<img width="859" alt="load test" src="https://user-images.githubusercontent.com/12785019/62182949-9e08ad80-b382-11e9-863e-4f0b0511d6eb.png">

<img width="974" alt="load prop" src="https://user-images.githubusercontent.com/12785019/62182948-9e08ad80-b382-11e9-93f6-56c797df29ee.png">

**Comment by ivlahek** [comment]
Hey, 

can you please increase the loop count? I did run the mvn clean (target was deleted).

I increased the loop count to 4 and here is what happened and how long the test lasted. (5:15)


![image](https://user-images.githubusercontent.com/4062750/62208365-ea5de880-b396-11e9-95ea-7e3b422bef02.png)

During the first loop count everything is ok. You get normal output, like shown in the picture:

![image](https://user-images.githubusercontent.com/4062750/62208528-77a13d00-b397-11e9-9da5-ea388f38c2cf.png)

But in the end you get output like this. Executor is receiving tasks, but it does not complete them because there are no available threads in the tread pool.

![image](https://user-images.githubusercontent.com/4062750/62208574-999abf80-b397-11e9-9ca3-5042d4636c2c.png)

And this is how the output ends:

![image](https://user-images.githubusercontent.com/4062750/62208745-0a41dc00-b398-11e9-945e-ec4d57152cc0.png)

I attached log file and csv file. Maybe it has something to do with my internet connection or with my pc processing power but either way, the tests should not last 5 minutes. It should last 60 seconds max.

I hope the attached files help.

[logs.zip](https://github.com/authorjapps/zerocode/files/3451646/logs.zip)

**Comment by vkjha2000** [comment]
@ivlahek , These are sample tests provided for demo purpose only.
The actual load should be generated against a known server to measure the benchmarking.

I have couple of Qn here. 

Do you have ideas on how GitHub Gateways are configured?

What's the purpose of generating load against GitHub server?

Do you know when you get 200 and when 403 from GitHub ?

Do you know how GitHub has configured its `rate-limiting` for a logged-in user vs guest-user?

Which type of user did you use?

Did you finally stop the tests(pressing the red button) or did it automatically got completed?

`It should last 60 seconds max.` <--- How did you arrive at this number 60 ?
As per the below log - there are many tests which has taken more than `2 sec` each

```
*requestTimeStamp:2019-07-31T13:22:16.694, 
*responseTimeStamp:2019-07-31T13:22:18.902,  <--- around 2 secs

Log:
2019-07-31 13:22:16,694 [pool-2-thread-20] INFO  org.jsmart.zerocode.core.runner.ZeroCodeUnitRunner - JUnit *requestTimeStamp:2019-07-31T13:22:16.694, 
JUnit Request:
--------- TEST-STEP-CORRELATION-ID: 55402924-8b2e-4067-86bd-b4ee3b44d349 ---------
2019-07-31 13:22:18,902 [pool-2-thread-20] WARN  org.jsmart.zerocode.core.runner.ZeroCodeUnitRunner - JUnit test failed due to : java.lang.AssertionError: 
Expected: is <200>
     but: was <403>,  passed = false
2019-07-31 13:22:18,902 [pool-2-thread-20] INFO  org.jsmart.zerocode.core.runner.ZeroCodeUnitRunner - JUnit test run completed. See the results in the console or log.  passed = false
2019-07-31 13:22:18,902 [pool-2-thread-20] INFO  org.jsmart.zerocode.core.runner.ZeroCodeUnitRunner - JUnit *responseTimeStamp:2019-07-31T13:22:18.902, 
JUnit Response:
--------- TEST-STEP-CORRELATION-ID: 55402924-8b2e-4067-86bd-b4ee3b44d349 ---------
```

IMHO instead of generating load against GitHub server you should generate load on your own project server where you have an idea how the server should behave `vs` how it actually behaves. i.e. `expected behaviour `vs `actual behaviour`.

There is a chance that IO operations(HTML UI Report) are taking time more than deadlock issue.  Just check in your own application server and let us know the result - Is it happenning everytime or randomly?

We might have to suppress the HTML report generation if you encounter this more often.

**Comment by ivlahek** [comment]
@vkjha2000 
Hey,
It seems it is linked with HTML report generation.

**Comment by ivlahek** [comment]
@vkjha2000 
It seems it has something to do with HTML report generation ...

When I put interactive.html.report.disabled=true in a property file (@TargetEnv annotation) everything is working fine.
When I remove it, I encounter the problem.
I think it is not a deadlock issue. I think it has something to do with html report generation. In the ZeroCodeReportGeneratorImpl class, method generateExtentReport runs very long.

Even if you execute LoadExistingJUnitTest (which is simple) with the following parameters 
number.of.threads=20
ramp.up.period.in.seconds=10
loop.count=3
you will encounter the similiar behaviour.

You can close the issue, this flag solves my issue.

**Comment by officiallysameer** [comment]
@ivlahek, can you please join our Zerocode mailing list/Slack

https://groups.google.com/forum/#!forum/zerocode-automation

https://join.slack.com/t/zerocode-workspace/shared_invite/enQtNzIyNDUwOTg2NDUzLWQ3ZTM1YTBhNjJmNzY3NmU0Y2I4NWIwZDVjYjk4M2JhYWY5NzA3ZWEwMWIwOTIwOWFjNTg2YzFmNzZhYTUyYzI

**Comment by ivlahek** [comment]
@officiallysameer , can you please recreate invitation for slack ...
It is not longer active.

**Comment by authorjapps** [comment]
> Sorry, the other link somehow has been expired.

@ivlahek, Can you try this link?
https://join.slack.com/t/zerocode-workspace/shared_invite/enQtNzYxMDAwNTQ3MjY1LTA2YmJjODJhNzQ4ZjBiYTQwZDBmZmNkNmExYjA3ZDk2OGFiZWFmNWJlNGRkOTdiMDQ4ZmQyNzcyNzVjNWQ4ODQ
