### ISSUE TITLE
Local date for today with date formatter at runtime

### ISSUE THREAD

**Issue by dinesh76in** [authorjapps/zerocode#29]
Does it have any `LocalDate` or `LocalDateTime` to generate current date which can work as below-
```
"date_today": "${LOCAL.DATE.TODAY:yyyy-MM-dd}",   //<---- should translate to e.g. 2018-02-11
"year_day": "${LOCAL.DATE.NOW:yyyy}" //<---- should translate to e.g. 2018
```
and it should support the **official Java format** given in the spec link below
https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html

**Comment by authorjapps** [comment]
@dinesh76in , Please watch the PR. This has been now released in version `1.1.25`.
Usage and examples here: https://github.com/authorjapps/zerocode#22
