### ISSUE TITLE
The author sees and replies

### ISSUE THREAD

**Issue by pengzhengfa** [authorjapps/zerocode#292]
Hello, can you help me write a simple performance test case, has tested Google as an example, the project of POM files, please send me my email: pengzhengfa@aliyun

**Comment by vkjha2000** [comment]
Hello @pengzhengfa , There a quick-start HelloWorld repo precisely for this.

Can you please check if it helps you?

Repo to setup in local-IDE : [Quick start - Performance testing - Varying Load/Stress generation](https://github.com/authorjapps/performance-tests)

**Comment by authorjapps** [comment]
@pengzhengfa , can you please explain with more details what exactly you are looking for in terms of performance testing?
We should be able to help you if we get to know your requirement properly. 👍

**Comment by authorjapps** [comment]
Can you please check this link and see if it helps...
https://github.com/authorjapps/zerocode/wiki/Load-or-Performance-Testing-(IDE-based)#in-essence-the-performance-testing-is-all-about-

**Comment by authorjapps** [comment]
Hello, did you get what you were looking for?
