### ISSUE TITLE
JayWay JSON Path - Picking Single Element Matching Value from Array

### ISSUE THREAD

**Issue by authorjapps** [authorjapps/zerocode#296]
_From Slack discussion with @santhoshTpixler_

Usually, the Jayway JSON Path returns an array even for one element match.
This may not be a design flaw, this works beautifully when validating SIZE of the matching elements returned as an array.
So far it's fine.

But it will be better to pick that element as a single value(not an array) and reuse it in the subsequent steps. 

Refer https://github.com/authorjapps/zerocode-hello-world/issues/16

### Solution

> "${$....DomainList[(@.name=='Retail_BILLING')].id.$VALUE}"

or

> "${$....DomainList[(@.name=='Retail_BILLING')].id.$VALUE[0]}"

should be a simple one to overcome the extra step.

Note the ending `.$VALUE` or $VALUE[0]
which will pick the  one element(1st one) from the array

**Comment by nirmalchandra** [comment]
Wiki update:
https://github.com/authorjapps/zerocode/wiki/When-JSON-Path-Matching-returns-value-or-values-as-an-array

**Comment by authorjapps** [comment]
Available in release `1.3.13` and higher.
