### ISSUE TITLE
Got error Integer cannot be cast to java.lang.String when trying to get autogenerated id from POST request

### ISSUE THREAD

**Issue by warademilind** [authorjapps/zerocode#302]
I am doing automation of REST API using ZeroCode.
**Created employee using POST request successfully.**

In response I have received:
>Sceanrio :1 
> (for "name": "POST_create_employee",)

```json
Response:
{
  "status" : 200,
  "headers" : {
    "Date" : [ "Fri, 23 Aug 2019 08:12:06 GMT" ],
    "Expires" : [ "0" ],
    "Transfer-Encoding" : [ "chunked" ],
    "X-XSS-Protection" : [ "1; mode=block" ],
    "X-Content-Type-Options" : [ "nosniff" ],
    "X-Frame-Options" : [ "SAMEORIGIN" ],
    "Content-Type" : [ "application/json;charset=UTF-8" ],
    "Cache-Control" : [ "no-store, no-cache, must-revalidate, post-check=0, pre-check=0" ]
  },
  "body" : {
    "httpStatusCode" : null,
    "responseCode" : 0,
    "responseMessege" : null,
    "id" : 123,
    "employeeName" : "pTdRexrIij 1566557405261",
    "pingBackTime" : 1
  }
}
```

**Now, I have to update the created Employee.**
So I need to send employee id and employee name in PUT request.
```json
{
	"name": "PUT_update_employee",
	"url": "/employee",
	"operation": "PUT",
	"request": {
		"headers": {
			"Authorization": "Bearer eyJhbGciOiJSUzI1NiIsIn",
			"userName": "milindwarade"
		},
		"body": {
			"id":  "${$.POST_create_employee.response.body.id}",
			"employeeName": "${$.POST_create_employee.response.body.employeeName}"
		}
	},
	"assertions": {
		"status": 200,
		"headers": {
			"Date": [
				"$NOT.NULL"
			],
			"Transfer-Encoding": [
				"chunked"
			],
			"Content-Type": [
				"application/json;charset=UTF-8"
			]
		},
		"body": {
			"httpStatusCode": "OK",
			"id": "${$.PUT_update_employee.request.body.id}",
			"employeeName": "${$.PUT_update_employee.request.body.employeeName}"
		}
	}
}
```

**After execution, got an error as -**
```java
java.lang.RuntimeException: 
JSON:{"headers": {"Authorization": "Bearer eyJhbGciOiJSUzI1NiIsIn","userName": "milindwarade"},"body": {"id":  "${$.POST_create_employee.response.body.id}","employeeName": "${$.POST_create_employee.response.body.employeeName}"}}
Possibly comments in the JSON found or bad JSON path found: $.POST_create_employee.response.body.id,
Details: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
	at org.jsmart.zerocode.core.engine.preprocessor.ZeroCodeAssertionsProcessorImpl.lambda$1(ZeroCodeAssertionsProcessorImpl.java:150)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.jsmart.zerocode.core.engine.preprocessor.ZeroCodeAssertionsProcessorImpl.resolveJsonPaths(ZeroCodeAssertionsProcessorImpl.java:116)
	at org.jsmart.zerocode.core.engine.preprocessor.ZeroCodeAssertionsProcessorImpl.resolveStringJson(ZeroCodeAssertionsProcessorImpl.java:87)
```

Can someone please help to solve/tell me solution for this issue??
Here, **id is required to update the employee.**

>Scenario :2
I have tried with this also (removed <body> from "id": and "employeeName": - 
```json
{
	"name": "PUT_update_employee",
	"url": "/employee",
	"operation": "PUT",
	"request": {
		"headers": {
			"Authorization": "Bearer eyJhbGciOiJSUzI1NiIsIn",
			"userName": "milindwarade"
		},
		"body": {
			"id":  "${$.POST_create_employee.response.id}",
			"employeeName": "${$.POST_create_employee.response.employeeName}"
		}
	},
	"assertions": {
		"status": 200,
		"headers": {
			"Date": [
				"$NOT.NULL"
			],
			"Transfer-Encoding": [
				"chunked"
			],
			"Content-Type": [
				"application/json;charset=UTF-8"
			]
		},
		"body": {
			"httpStatusCode": "OK",
			"id": "${$.PUT_update_employee.request.id}",
			"employeeName": "${$.PUT_update_employee.request.employeeName}"
		}
	}
}
```

but then also facing error as -
```java
Possibly comments in the JSON found or bad JSON path found: $.POST_create_employee.response.id,
Details: com.jayway.jsonpath.PathNotFoundException: No results for path: $['POST_create_employee']['response']['id']
	at org.jsmart.zerocode.core.engine.preprocessor.ZeroCodeAssertionsProcessorImpl.lambda$1(ZeroCodeAssertionsProcessorImpl.java:150)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.jsmart.zerocode.core.engine.preprocessor.ZeroCodeAssertionsProcessorImpl.resolveJsonPaths(ZeroCodeAssertionsProcessorImpl.java:116)
	at org.jsmart.zerocode.core.engine.preprocessor.ZeroCodeAssertionsProcessorImpl.resolveStringJson(ZeroCodeAssertionsProcessorImpl.java:87)
```

Please do needful help.
Thanks a lot.

**Comment by vkjha2000** [comment]
Hello @warademilind, we will look into it...

Can you paste your run log with test `CORRELATION-ID`? sample below:
`--------- TEST-STEP-CORRELATION-ID: 547ca3f6-22c6-42a3-b243-cc4cdc3172c7 ---------`
> _You can strip out your business specific details_

The `time stamp wise log` will help us to figure out the issue better!

**Comment by warademilind** [comment]
Thanks @vkjha2000 for quick reply.
Please find attached run log for Scenario#1 and Scenario#2.
[Scenario_1.txt](https://github.com/authorjapps/zerocode/files/3536844/Scenario_1.txt)
[Scenario_2.txt](https://github.com/authorjapps/zerocode/files/3536845/Scenario_2.txt)

Waiting for your reply.

**Comment by authorjapps** [comment]
Hello mate,

#### Scenario_2.txt
Had a look at the `Scenario_2.txt`
As the below error is displayed in the log-
> `bad JSON path found: ${$.POST_create_employee.response.id},`

The correct path should be as below-
```java
${$.POST_create_employee.response.body.id}
```

i.e. missing the `.body`

Hope it helps!

***

_LOG from `Scenario_2.txt`:_
```java
--------- TEST-STEP-CORRELATION-ID: 6780f795-f947-4e53-af90-995d4d763ad7 ---------
...
...
...
java.lang.RuntimeException: 
JSON:{"headers":{"Authorization":"Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUI","userName":"testmilind"},"body":{"id":"${$.POST_create_employee.response.id}","employeeName":"${$.POST_create_employee.response.employeeName}","pingBackTime":"5"}}
Possibly comments in the JSON found or bad JSON path found: ${$.POST_create_employee.response.id},
Details: com.jayway.jsonpath.PathNotFoundException: No results for path: $['POST_create_employee']['response']['id']

```

**Comment by santhoshTpixler** [comment]
@warademilind Which version you are using. It is working in 1.3.12
```15:30:01,869 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
15:30:01,869 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
15:30:01,869 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/home/local/ZOHOCORP/santhosh-6524/.m2/repository/org/jsmart/zerocode-tdd/1.3.12/zerocode-tdd-1.3.12.jar!/logback.xml]
15:30:01,892 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@3b81a1bc - URL [jar:file:/home/local/ZOHOCORP/santhosh-6524/.m2/repository/org/jsmart/zerocode-tdd/1.3.12/zerocode-tdd-1.3.12.jar!/logback.xml] is not of type file
15:30:01,975 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
15:30:01,986 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.FileAppender]
15:30:01,994 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [fileAppender]
15:30:02,043 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
15:30:02,120 |-INFO in ch.qos.logback.core.FileAppender[fileAppender] - File property is set to [target/logs/zerocode_rest_bdd_logs.log]
15:30:02,121 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
15:30:02,123 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [consoleAppender]
15:30:02,134 |-WARN in ch.qos.logback.core.ConsoleAppender[consoleAppender] - This appender no longer admits a layout as a sub-component, set an encoder instead.
15:30:02,134 |-WARN in ch.qos.logback.core.ConsoleAppender[consoleAppender] - To ensure compatibility, wrapping your layout in LayoutWrappingEncoder.
15:30:02,134 |-WARN in ch.qos.logback.core.ConsoleAppender[consoleAppender] - See also http://logback.qos.ch/codes.html#layoutInsteadOfEncoder for details
15:30:02,134 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
15:30:02,134 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [fileAppender] to Logger[ROOT]
15:30:02,135 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [consoleAppender] to Logger[ROOT]
15:30:02,135 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
15:30:02,138 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@64616ca2 - Registering current configuration as safe fallback point

2019-08-24 15:30:02,200 [32m[main][0;39m [34mINFO[0;39m org.jsmart.zerocode.core.utils.RunnerUtils - [34m### testClass : class JustHelloWorldTest
[0;39m2019-08-24 15:30:02,780 [32m[main][0;39m [34mINFO[0;39m org.jsmart.zerocode.core.utils.RunnerUtils - [34m### testClass : class JustHelloWorldTest
[0;39m2019-08-24 15:30:02,851 [32m[main][0;39m [34mINFO[0;39m org.jsmart.zerocode.core.utils.RunnerUtils - [34m### testClass : class JustHelloWorldTest
[0;39m2019-08-24 15:30:02,870 [32m[main][0;39m [34mINFO[0;39m org.jsmart.zerocode.core.runner.ZeroCodeUnitRunner - [34mSystem property zerocode.junit=null
[0;39m2019-08-24 15:30:02,993 [32m[main][0;39m [34mINFO[0;39m org.jsmart.zerocode.core.runner.ZeroCodeMultiStepsScenarioRunnerImpl - [34m
-------------------------- BDD: Scenario:hello -------------------------

[0;39m2019-08-24 15:30:03,020 [32m[main][0;39m [34mINFO[0;39m org.jsmart.zerocode.core.runner.ZeroCodeMultiStepsScenarioRunnerImpl - [34m
-------------------------------------------------------------------------
     Executing Scenario Count No. or parameter No. or Row No. | 0 | 
-------------------------------------------------------------------------
[0;39m2019-08-24 15:30:03,020 [32m[main][0;39m [34mINFO[0;39m org.jsmart.zerocode.core.runner.ZeroCodeMultiStepsScenarioRunnerImpl - [34m
### Executing Step -->> Count No: 0
[0;39m2019-08-24 15:30:03,110 [32m[main][0;39m [34mINFO[0;39m org.jsmart.zerocode.core.httpclient.ssl.SslTrustHttpClient - [34m###Used SSL Enabled Http Client for http/https/TLS connections
[0;39m2019-08-24 15:30:04,275 [32m[main][0;39m [34mINFO[0;39m org.jsmart.zerocode.core.runner.StepNotificationHandler - [34m
***Step PASSED:hello->POST_create_employee
[0;39m2019-08-24 15:30:04,278 [32m[main][0;39m [34mINFO[0;39m org.jsmart.zerocode.core.runner.ZeroCodeMultiStepsScenarioRunnerImpl - [34m
--------- TEST-STEP-CORRELATION-ID: 587367ca-1491-452d-96ad-2e1fad5e1f03 ---------
*requestTimeStamp:2019-08-24T15:30:03.064
step:POST_create_employee
id:null
url:http://localhost:3000/get/a/json/body
method:GET
request:
{ } 
--------- TEST-STEP-CORRELATION-ID: 587367ca-1491-452d-96ad-2e1fad5e1f03 ---------
Response:
{
  "status" : 200,
  "headers" : {
    "Date" : [ "Sat, 24 Aug 2019 10:00:04 GMT" ],
    "Content-Length" : [ "131" ],
    "X-Powered-By" : [ "Express" ],
    "Content-Type" : [ "application/json; charset=utf-8" ],
    "ETag" : [ "W/\"83-RXu1VeZBI695n82UQHV/OLYA/yw\"" ],
    "Connection" : [ "keep-alive" ]
  },
  "body" : {
    "httpStatusCode" : null,
    "responseCode" : 0,
    "responseMessege" : null,
    "id" : 123,
    "employeeName" : "pTdRexrIij 1566557405261",
    "pingBackTime" : 1
  }
}
*responseTimeStamp:2019-08-24T15:30:04.269 
*Response delay:1205.0 milli-secs 
---------> Assertion: <----------
{
  "status" : 200
} 
-done-

[0;39m2019-08-24 15:30:04,280 [32m[main][0;39m [34mINFO[0;39m org.jsmart.zerocode.core.runner.ZeroCodeMultiStepsScenarioRunnerImpl - [34m
### Executing Step -->> Count No: 0
[0;39m2019-08-24 15:30:04,284 [32m[main][0;39m [34mINFO[0;39m org.jsmart.zerocode.core.httpclient.ssl.SslTrustHttpClient - [34m###Used SSL Enabled Http Client for http/https/TLS connections
[0;39m2019-08-24 15:30:05,195 [32m[main][0;39m [34mINFO[0;39m org.jsmart.zerocode.core.runner.StepNotificationHandler - [34m
***Step PASSED:hello->Fetch_bots_in_backendautomation
[0;39m2019-08-24 15:30:05,197 [32m[main][0;39m [34mINFO[0;39m org.jsmart.zerocode.core.runner.ZeroCodeMultiStepsScenarioRunnerImpl - [34m
--------- TEST-STEP-CORRELATION-ID: 6a581994-f8a8-45e7-83d0-c0a92299e3e5 ---------
*requestTimeStamp:2019-08-24T15:30:04.283
step:Fetch_bots_in_backendautomation
id:null
url:http://localhost:3000/post/a/json/body
method:POST
request:
{
  "body" : {
    "id" : "123",
    "employeeName" : "pTdRexrIij 1566557405261"
  }
} 
--------- TEST-STEP-CORRELATION-ID: 6a581994-f8a8-45e7-83d0-c0a92299e3e5 ---------
Response:
{
  "status" : 200,
  "headers" : {
    "Date" : [ "Sat, 24 Aug 2019 10:00:05 GMT" ],
    "Content-Length" : [ "43" ],
    "X-Powered-By" : [ "Express" ],
    "Content-Type" : [ "application/json; charset=utf-8" ],
    "ETag" : [ "W/\"2b-6CC5McsMsZ+DKajgsXsbHz0lIu4\"" ],
    "Connection" : [ "keep-alive" ]
  },
  "body" : {
    "message" : "You have successfully posted."
  }
}
*responseTimeStamp:2019-08-24T15:30:05.192 
*Response delay:909.0 milli-secs 
---------> Assertion: <----------
{
  "status" : 200
} 
-done-

[0;39m2019-08-24 15:30:05,349 [32m[main][0;39m [34mINFO[0;39m org.jsmart.zerocode.core.runner.ZeroCodeUnitRunner - [34m
**FINISHED executing all Steps for [hello] **.
Steps were:[POST_create_employee, Fetch_bots_in_backendautomation]
[0;39m2019-08-24 15:30:05,353 [32m[main][0;39m [34mINFO[0;39m org.jsmart.zerocode.core.engine.listener.ZeroCodeTestReportListener - [34m### ZeroCode: Test run completed for this runner. Generating test reports and charts. More help and examples are available at the README in GitHub
[0;39m2019-08-24 15:30:05,462 [32m[main][0;39m [34mINFO[0;39m org.jsmart.zerocode.core.domain.builders.ExtentReportsFactory - [34mWhere were the tests fired? Ans: OS:Linux, Architecture:amd64, Java:1.8.0_222
[0;39m```

**Comment by warademilind** [comment]
> Hello mate,
> 
> #### Scenario_2.txt
> Had a look at the `Scenario_2.txt`
> As the below error is displayed in the log-
> 
> > `bad JSON path found: ${$.POST_create_employee.response.id},`
> 
> The correct path should be as below-
> 
> ```java
> ${$.POST_create_employee.response.body.id}
> ```
> 
> i.e. missing the `.body`
> 
> Hope it helps!
> 
> _LOG from `Scenario_2.txt`:_
> 
> ```java
> --------- TEST-STEP-CORRELATION-ID: 6780f795-f947-4e53-af90-995d4d763ad7 ---------
> ...
> ...
> ...
> java.lang.RuntimeException: 
> JSON:{"headers":{"Authorization":"Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUI","userName":"testmilind"},"body":{"id":"${$.POST_create_employee.response.id}","employeeName":"${$.POST_create_employee.response.employeeName}","pingBackTime":"5"}}
> Possibly comments in the JSON found or bad JSON path found: ${$.POST_create_employee.response.id},
> Details: com.jayway.jsonpath.PathNotFoundException: No results for path: $['POST_create_employee']['response']['id']
> ```

Hello @authorjapps ,
I have tried with the solution which gave. Then also issue happen -
Possibly comments in the JSON found or bad JSON path found: $.POST_create_employee.response.body.id,
Details: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
	at org.jsmart.zerocode.core.engine.preprocessor.ZeroCodeAssertionsProcessorImpl.lambda$1(ZeroCodeAssertionsProcessorImpl.java:150)
	at java.util.ArrayList.forEach(ArrayList.java:1249)

I have already added all log in above comment (Scenario #1 attachment).

I am using below version-
    <parent>
        <artifactId>zerocode-tdd-parent</artifactId>
        <groupId>org.jsmart</groupId>
        <version>1.3.13-SNAPSHOT</version>
    </parent>

**Comment by warademilind** [comment]
> @warademilind Which version you are using. It is working in 1.3.12
> 
> ```
> 15:30:01,869 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
> 15:30:01,869 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/home/local/ZOHOCORP/santhosh-6524/.m2/repository/org/jsmart/zerocode-tdd/1.3.12/zerocode-tdd-1.3.12.jar!/logback.xml]
> 15:30:01,892 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@3b81a1bc - URL [jar:file:/home/local/ZOHOCORP/santhosh-6524/.m2/repository/org/jsmart/zerocode-tdd/1.3.12/zerocode-tdd-1.3.12.jar!/logback.xml] is not of type file
> 15:30:01,975 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
> 15:30:01,986 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.FileAppender]
> 15:30:01,994 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [fileAppender]
> 15:30:02,043 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
> 15:30:02,120 |-INFO in ch.qos.logback.core.FileAppender[fileAppender] - File property is set to [target/logs/zerocode_rest_bdd_logs.log]
> 15:30:02,121 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
> 15:30:02,123 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [consoleAppender]
> 15:30:02,134 |-WARN in ch.qos.logback.core.ConsoleAppender[consoleAppender] - This appender no longer admits a layout as a sub-component, set an encoder instead.
> 15:30:02,134 |-WARN in ch.qos.logback.core.ConsoleAppender[consoleAppender] - To ensure compatibility, wrapping your layout in LayoutWrappingEncoder.
> 15:30:02,134 |-WARN in ch.qos.logback.core.ConsoleAppender[consoleAppender] - See also http://logback.qos.ch/codes.html#layoutInsteadOfEncoder for details
> 15:30:02,134 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
> 15:30:02,134 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [fileAppender] to Logger[ROOT]
> 15:30:02,135 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [consoleAppender] to Logger[ROOT]
> 15:30:02,135 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
> 15:30:02,138 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@64616ca2 - Registering current configuration as safe fallback point
> 
> 2019-08-24 15:30:02,200 �[32m[main]�[0;39m �[34mINFO�[0;39m org.jsmart.zerocode.core.utils.RunnerUtils - �[34m### testClass : class JustHelloWorldTest
> �[0;39m2019-08-24 15:30:02,780 �[32m[main]�[0;39m �[34mINFO�[0;39m org.jsmart.zerocode.core.utils.RunnerUtils - �[34m### testClass : class JustHelloWorldTest
> �[0;39m2019-08-24 15:30:02,851 �[32m[main]�[0;39m �[34mINFO�[0;39m org.jsmart.zerocode.core.utils.RunnerUtils - �[34m### testClass : class JustHelloWorldTest
> �[0;39m2019-08-24 15:30:02,870 �[32m[main]�[0;39m �[34mINFO�[0;39m org.jsmart.zerocode.core.runner.ZeroCodeUnitRunner - �[34mSystem property zerocode.junit=null
> �[0;39m2019-08-24 15:30:02,993 �[32m[main]�[0;39m �[34mINFO�[0;39m org.jsmart.zerocode.core.runner.ZeroCodeMultiStepsScenarioRunnerImpl - �[34m
> -------------------------- BDD: Scenario:hello -------------------------
> 
> �[0;39m2019-08-24 15:30:03,020 �[32m[main]�[0;39m �[34mINFO�[0;39m org.jsmart.zerocode.core.runner.ZeroCodeMultiStepsScenarioRunnerImpl - �[34m
> -------------------------------------------------------------------------
>      Executing Scenario Count No. or parameter No. or Row No. | 0 | 
> -------------------------------------------------------------------------
> �[0;39m2019-08-24 15:30:03,020 �[32m[main]�[0;39m �[34mINFO�[0;39m org.jsmart.zerocode.core.runner.ZeroCodeMultiStepsScenarioRunnerImpl - �[34m
> ### Executing Step -->> Count No: 0
> �[0;39m2019-08-24 15:30:03,110 �[32m[main]�[0;39m �[34mINFO�[0;39m org.jsmart.zerocode.core.httpclient.ssl.SslTrustHttpClient - �[34m###Used SSL Enabled Http Client for http/https/TLS connections
> �[0;39m2019-08-24 15:30:04,275 �[32m[main]�[0;39m �[34mINFO�[0;39m org.jsmart.zerocode.core.runner.StepNotificationHandler - �[34m
> ***Step PASSED:hello->POST_create_employee
> �[0;39m2019-08-24 15:30:04,278 �[32m[main]�[0;39m �[34mINFO�[0;39m org.jsmart.zerocode.core.runner.ZeroCodeMultiStepsScenarioRunnerImpl - �[34m
> --------- TEST-STEP-CORRELATION-ID: 587367ca-1491-452d-96ad-2e1fad5e1f03 ---------
> *requestTimeStamp:2019-08-24T15:30:03.064
> step:POST_create_employee
> id:null
> url:http://localhost:3000/get/a/json/body
> method:GET
> request:
> { } 
> --------- TEST-STEP-CORRELATION-ID: 587367ca-1491-452d-96ad-2e1fad5e1f03 ---------
> Response:
> {
>   "status" : 200,
>   "headers" : {
>     "Date" : [ "Sat, 24 Aug 2019 10:00:04 GMT" ],
>     "Content-Length" : [ "131" ],
>     "X-Powered-By" : [ "Express" ],
>     "Content-Type" : [ "application/json; charset=utf-8" ],
>     "ETag" : [ "W/\"83-RXu1VeZBI695n82UQHV/OLYA/yw\"" ],
>     "Connection" : [ "keep-alive" ]
>   },
>   "body" : {
>     "httpStatusCode" : null,
>     "responseCode" : 0,
>     "responseMessege" : null,
>     "id" : 123,
>     "employeeName" : "pTdRexrIij 1566557405261",
>     "pingBackTime" : 1
>   }
> }
> *responseTimeStamp:2019-08-24T15:30:04.269 
> *Response delay:1205.0 milli-secs 
> ---------> Assertion: <----------
> {
>   "status" : 200
> } 
> -done-
> 
> �[0;39m2019-08-24 15:30:04,280 �[32m[main]�[0;39m �[34mINFO�[0;39m org.jsmart.zerocode.core.runner.ZeroCodeMultiStepsScenarioRunnerImpl - �[34m
> ### Executing Step -->> Count No: 0
> �[0;39m2019-08-24 15:30:04,284 �[32m[main]�[0;39m �[34mINFO�[0;39m org.jsmart.zerocode.core.httpclient.ssl.SslTrustHttpClient - �[34m###Used SSL Enabled Http Client for http/https/TLS connections
> �[0;39m2019-08-24 15:30:05,195 �[32m[main]�[0;39m �[34mINFO�[0;39m org.jsmart.zerocode.core.runner.StepNotificationHandler - �[34m
> ***Step PASSED:hello->Fetch_bots_in_backendautomation
> �[0;39m2019-08-24 15:30:05,197 �[32m[main]�[0;39m �[34mINFO�[0;39m org.jsmart.zerocode.core.runner.ZeroCodeMultiStepsScenarioRunnerImpl - �[34m
> --------- TEST-STEP-CORRELATION-ID: 6a581994-f8a8-45e7-83d0-c0a92299e3e5 ---------
> *requestTimeStamp:2019-08-24T15:30:04.283
> step:Fetch_bots_in_backendautomation
> id:null
> url:http://localhost:3000/post/a/json/body
> method:POST
> request:
> {
>   "body" : {
>     "id" : "123",
>     "employeeName" : "pTdRexrIij 1566557405261"
>   }
> } 
> --------- TEST-STEP-CORRELATION-ID: 6a581994-f8a8-45e7-83d0-c0a92299e3e5 ---------
> Response:
> {
>   "status" : 200,
>   "headers" : {
>     "Date" : [ "Sat, 24 Aug 2019 10:00:05 GMT" ],
>     "Content-Length" : [ "43" ],
>     "X-Powered-By" : [ "Express" ],
>     "Content-Type" : [ "application/json; charset=utf-8" ],
>     "ETag" : [ "W/\"2b-6CC5McsMsZ+DKajgsXsbHz0lIu4\"" ],
>     "Connection" : [ "keep-alive" ]
>   },
>   "body" : {
>     "message" : "You have successfully posted."
>   }
> }
> *responseTimeStamp:2019-08-24T15:30:05.192 
> *Response delay:909.0 milli-secs 
> ---------> Assertion: <----------
> {
>   "status" : 200
> } 
> -done-
> 
> �[0;39m2019-08-24 15:30:05,349 �[32m[main]�[0;39m �[34mINFO�[0;39m org.jsmart.zerocode.core.runner.ZeroCodeUnitRunner - �[34m
> **FINISHED executing all Steps for [hello] **.
> Steps were:[POST_create_employee, Fetch_bots_in_backendautomation]
> �[0;39m2019-08-24 15:30:05,353 �[32m[main]�[0;39m �[34mINFO�[0;39m org.jsmart.zerocode.core.engine.listener.ZeroCodeTestReportListener - �[34m### ZeroCode: Test run completed for this runner. Generating test reports and charts. More help and examples are available at the README in GitHub
> �[0;39m2019-08-24 15:30:05,462 �[32m[main]�[0;39m �[34mINFO�[0;39m org.jsmart.zerocode.core.domain.builders.ExtentReportsFactory - �[34mWhere were the tests fired? Ans: OS:Linux, Architecture:amd64, Java:1.8.0_222
> �[0;39m```
> ```

Hello @santhoshTpixler ,

I am using below version - 
    <parent>
        <artifactId>zerocode-tdd-parent</artifactId>
        <groupId>org.jsmart</groupId>
        <version>1.3.13-SNAPSHOT</version>
    </parent>

**Comment by authorjapps** [comment]
@warademilind, can you try the same with version `1.3.12` ?

**Comment by warademilind** [comment]
@authorjapps ,

Yes. Tried with version 1.3.12 for both scenario 1 and 2 . Facing same issue.

**Comment by authorjapps** [comment]
Interesting...
Why we are unable to reproduce... Just checking which JDK are you using?

Will it be possible to attach here your Scenario-Json file just to look at anything special there?

**Comment by warademilind** [comment]
Hello @authorjapps ,

I am using jdk1.8.0_131 version (installed on my pc).

Please find attached Scenario-json file for ref.
[resource_json.txt](https://github.com/authorjapps/zerocode/files/3537805/resource_json.txt)

Please find result log file for ref.
[result_log.txt](https://github.com/authorjapps/zerocode/files/3537806/result_log.txt)

Nothing different, when I an trying same scenario with Postman then its working. 

Please find attached POM file for ref. -
[pomFile.txt](https://github.com/authorjapps/zerocode/files/3537808/pomFile.txt)

**Comment by authorjapps** [comment]
> I am using jdk1.8.0_131 version (installed on my pc).

I mean which JDK vendor? Oracle or OpenJDK or any other ?

**Comment by warademilind** [comment]
> I mean which JDK vendor? Oracle or OpenJDK or any other ?

I am using JDK of Oracle.

> Also, can you please join our slack-channel (as well as mailing list)?

Sure

**Comment by authorjapps** [comment]
Sorted.
The project was rebuilt using
> mvn clean install -DskipTests 

and there were no issues after that.

**Comment by warademilind** [comment]
Thanks a lot.
Its working now.
