### ISSUE TITLE
Is JIRA integration possible using Zerocode

### ISSUE THREAD

**Issue by warademilind** [authorjapps/zerocode#309]
Hello all,

I am able to use Zerocode for Rest API testing properly as of now (mainly ref. Hello World and Performance/Load testing examples). Now, I need to add results of Rest API testing in JIRA.

In cucumber,(which are executing using Junit only). I am creating html report and XML report. (I am using Selenium, Cucumber based framework for UI testing).
```
plugin={
    "com.cucumber.listener.ExtentCucumberFormatter:target/cucumber-reports/Automation_Report.html",
    "junit:target/cucumber-reports/Cucumber.xml"
}
```

Here in Zerocde, we are already using `extentReport for HTML` report creation. Is it possible to create XML report also, as those will be helpful to send results in JIRA?

**Comment by BeTheCodeWithYou** [comment]
Hi @warademilind  thanks mate for raising this issue here.

please could you provide more details around this:- 

1) is there any specific xml structure you are looking after for jira integration?
 if yes, any sample xml would be helpful.

2) can you direct us for any examples of this test report(xml) with jira integration, so that we can also look into details how best we can serve this issue.

thanks mate. 👍

**Comment by warademilind** [comment]
Hello @BeTheCodeWithYou ,

Yes, it isjunit plugin, 
https://github.com/jenkinsci/junit-plugin/tree/master/src/test/resources/hudson/tasks/junit

Need to have xml is this format:
```
<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<testsuite>
<testcase classname="Scanario Name 1" time="12000">
<system-out>Pass</system-out></testcase>
<testcase classname="Scanario Name 2" time="20000">
<system-out>Pass</system-out></testcase>
<testcase classname="Scanario Name 3" time="20000">
<failure>Fail</failure></testcase>
</testsuite>
```

**Note:** time="XXXX" if it was available with us, then it will be good.

**Comment by authorjapps** [comment]
Hey @warademilind , The JUnit reports are generated via `maven sure-fire` (or `fail-safe plugin` if you are using). This should be already available at your target folder.

> Have you tried to find them?

Please check the target folder,
![image](https://user-images.githubusercontent.com/12598420/65050997-37564800-d960-11e9-96f4-4dfcc2ba7fc1.png)

or

![image](https://user-images.githubusercontent.com/12598420/65050964-286f9580-d960-11e9-97fc-af09dcae823a.png)

This works even for `HelloWorld` project.
See the screenshot below-
![image](https://user-images.githubusercontent.com/12598420/65051587-45589880-d961-11e9-8d29-7985dc53f857.png)

**Comment by warademilind** [comment]
Thanks all.
I am able to get reports.
