### ISSUE TITLE
provide PATCH & DELETE method support in mockmaker

### ISSUE THREAD

**Issue by BeTheCodeWithYou** [authorjapps/zerocode#310]
Currently Zerocode In-Scenario wiremock maker supports.. supports GET, PUT & POST
this issue is to provide support of PATCH and DELETE method as well.

**Comment by BeTheCodeWithYou** [comment]
@authorjapps 
PR raised. All Travis checks passing.
Merged to master.
closing issue.

**Comment by authorjapps** [comment]
Some more things to take care(not major) please 👍 -
https://github.com/authorjapps/zerocode/pull/315#issuecomment-536616882

A new PR will do.

**Comment by authorjapps** [comment]
Available in version `1.3.16`.
