### ISSUE TITLE
Merging README and Wiki - Removing duplicate contents

### ISSUE THREAD

**Issue by authorjapps** [authorjapps/zerocode#314]
Any suggestions? Thanks in advance. 

TODO--
- Move lengthy instructions/steps to a new Wiki page
- Remove similar/contents, merge and make one
- Provide `code/yaml/json` as text (image not preferable as it makes it difficult to copy-paste for a developer/tester)
- Sections
  - Mainly these 4 sections(but can extend depending on a usecase)
  - Problem statement/Introduction
  - Solution
  - Conslusion/Code reference(helloword Github ref if available)

**Comment by authorjapps** [comment]
@vkjha2000 @officiallysameer, if you get chance, can you tidy up these and make it easily searchable/maintainable ?

**Comment by vkjha2000** [comment]
Done.
