### ISSUE TITLE
Generate Cucumber Gherkin steps using Zerocode DSL

### ISSUE THREAD

**Issue by vkjha2000** [authorjapps/zerocode#320]
> Use case  - Why do we need this?

Our test-engineers as well as developers often struggle to come up with `Given-When-Then` scenarios/steps for the API testing. Also to get these feature-file steps agreeable among the devs or testers is sometimes difficult as, the statements or implementations(step-definitions) varies from dev to dev `or` from tester to tester. This is because everyone wants to write in their specific way, which becomes difficult to maintain in the long run.

We are thinking if Zerocode can provide some kind of code-generator or maven-plugin to auto-generate these steps from the `scenario JSON/YAML files` as, writing the scenario files in Zerocode is very easy and intuitive.

> AC1

Given an API for automation-testing,
When I write a step(or multiple steps) using Zerocode DSL(YAML or JSON)
Then I will be able to generate the Gherkin BDD scenario and step(s) as a feature-file for this API

**Comment by authorjapps** [comment]
Not in scope
