### ISSUE TITLE
New beginner, can this run in Katalon? 

### ISSUE THREAD

**Issue by lovelyplanet2019** [authorjapps/zerocode#325]
We are using katalon to test API. Can we use zerocode in Katalon to perform kafka message validation?

**Comment by officiallysameer** [comment]
@lovelyplanet2019 
Is Katalon an opensource product? what kind of tool is this?  Is it maven based?

**Comment by lovelyplanet2019** [comment]
> @lovelyplanet2019
> Is Katalon an opensource product? what kind of tool is this? Is it maven based?

It is free tool, UI based to test API or UI, similiar like selenium but developed by Katalon. Not maven based.

**Comment by drizztDo** [comment]
There is more than one Katalon product. Which one is you mentioned? Is that Katalium?
