### ISSUE TITLE
ZeroCodeUnitRunner throws NoSuchMethodException

### ISSUE THREAD

**Issue by Kloe2257** [authorjapps/zerocode#326]
Hello,

I am trying to use ZeroCode v1.3.16 for load tests on simple Junit 4 tests.

But while using class **ZeroCodeUnitRunner**, I am facing a **NoSuchMethodException** on **isIgnored** (by the way, the exception is catched and hidden by the **ParentRunner** class, I lost lot of time and finally found it by debugging the lib classes).

It prevents the loader from working or generating the report.

ZeroCodeUnitRunner.class
```java
@Override
    protected void runChild(FrameworkMethod method, RunNotifier notifier) {

        final Description description = describeChild(method);
        JsonTestCase jsonTestCaseAnno = method.getMethod().getAnnotation(JsonTestCase.class);
        if(jsonTestCaseAnno == null){
            jsonTestCaseAnno = evalScenarioToJsonTestCase(method.getMethod().getAnnotation(Scenario.class));
        }

        if (isIgnored(method)) { <-- This does not exist anymore

            notifier.fireTestIgnored(description);

        } else if (jsonTestCaseAnno != null) {

            runLeafJsonTest(notifier, description, jsonTestCaseAnno);

        } else {
            // =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
            // It is an usual Junit test, not the JSON test case
            // =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
            runLeafJUnitTest(methodBlock(method), description, notifier);
        }

    }
```

ParentRunner.class
```java
    @Override
    public void run(final RunNotifier notifier) {
        EachTestNotifier testNotifier = new EachTestNotifier(notifier,
                getDescription());
        try {
            Statement statement = classBlock(notifier);
            statement.evaluate();
        } catch (AssumptionViolatedException e) {
            testNotifier.fireTestIgnored();
        } catch (StoppedByUserException e) {
            throw e;
        } catch (Throwable e) {
            testNotifier.addFailure(e);  <-- Don't know why, this is hidding the exception
        }
    }
```

I overrided **ZeroCodeUnitRunner** to remove the code where **isIgnored** method is called, and it is working like a charm now.

Could you fix this ?
Thank you, Kloe.

**Comment by authorjapps** [comment]
Hello @Kloe2257 , thanks for reporting this, we will take a look soon and put necessary fix!
If you can, please try to contribute and fix this(via a PR please) !

**Comment by ragcrix** [comment]
Hi @authorjapps! 

If this task is still open, I can look at this.

**Comment by authorjapps** [comment]
Thanks @ragcrix !

**Comment by ragcrix** [comment]
Hi @Kloe2257,
I didn't reproduce the issue. 
Could you please write your steps for this error?

Thank you.

**Comment by robertotru** [comment]
I have the same issue `NoSuchMethodException` with version 1.3.17.

I have the same problem using JUnit 4.12.
The problem seems to be that the `ZeroCodeLoadRunner` describes the method appending the prefix `<<Load>>`, which won't let the test method to be run inside JUnit `Filter` class when method `matchMethodDescription` does
```java
                if (description.isTest()) {
                    return desiredDescription.equals(description);
                } else {
```
So, if the test method is called foo, the id of the two descriptions will be `foo(com.my.TestClass)` and `<<Load>>.foo(com.my.TestClass)` resulting in no matching test.

Removing the label made everything work.

**Comment by Kloe2257** [comment]
Hello @ragcrix ,
I tried again with the new release 1.3.24 and JUnit 4.11 (i am also using mockito and assertJ) :
`<dependency>
			<groupId>org.jsmart</groupId>
			<artifactId>zerocode-tdd</artifactId>
			<version>1.3.24</version>
			<scope>test</scope>
		</dependency>
<dependency>
			<groupId>org.mockito</groupId>
			<artifactId>mockito-core</artifactId>
			<version>2.28.2</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.assertj</groupId>
			<artifactId>assertj-core</artifactId>
			<version>3.12.1</version>
			<scope>test</scope>
		</dependency>
`

And the issue is still present while running mvn install (or run as Junit in Eclipse).

With such imports in the Pom, if I take the class `ZeroCodeUnitRunner ` in my own code, the line 125 do not compile at all, just like if the method isIgnored does not exist.
`if (isIgnored(method)) {`

Where does this method isIgnored is declared on your side ?

Regards, Kloe.

**Comment by Kloe2257** [comment]
Ok, I finally find out that minimum Junit version to be used is 4.12 (where isIgnored method was added to BlockJUnit4ClassRunner).
**ZeroCode is not compatible with Junit 4.11.**
Maybe this should be documented somewhere.

Regards, Kloe.

**Comment by authorjapps** [comment]
Updated:
[Minimum System Requirements](https://github.com/authorjapps/zerocode/wiki/Getting-Started#minimum-system-requirements)
