### ISSUE TITLE
Send headers while producing to a Kafka topic

### ISSUE THREAD

**Issue by authorjapps** [authorjapps/zerocode#330]
https://github.com/authorjapps/hello-kafka-stream-testing/issues/1

Background
===
From Slack:
Question from: Kushagra
@authorjapps is it possible to send a message to a Kafka topic with a particular header? I know we can do that in http. Please advise!

AC1:
===
As a developer or SDET
I want to produce a record with header(s) to a desired Kafka topic
So that I verify the business flow related to the headers.
e.g.
```JSON
                "records":[
                    {
                        "key": "${RANDOM.NUMBER}",
                        "value": "Hello World",
                          "headers": {
                                  "key1" : "value1",
                                  "key2" : "value2",
                          }
                          ...
                    }
```

AC2:
===
As a developer or Test Engineer
I want a help page or a Wiki to learn the usage of the producing and consuming of a Kafka record with headers
So that I can easily implement this into the test automation in my project.
Wiki todo(Ask for edit permission) : 
https://github.com/authorjapps/zerocode/wiki/Kafka-records-with-headers

> SDET: Software Developer Engineer in Test

**Comment by kt09** [comment]
**Use case @authorjapps :**
Send a message to a Kafka Topic on a particular partition and Header. For enterprise applications, this feature will provide the capability to test the code behind/micro service listening to a particular header. This can look something similar to http implementation where ZeroCode has the feature of specifying header. Example produce JSON can look like:

```
 {
            "name": "load_kafka",
            "url": "kafka-topic:demo-Kafka-Topic",
            "operation": "produce",
            "request": {
                "records":[
                    {
                        "key": "${RANDOM.NUMBER}",
                        "value": "Hello World",
                        "partition": 0,
                          **"headers": {
                                  "Key": "Sample.Key",
                                  "Value": "Sample.Value"
                          },**
                    }
                ]
            },
            "assertions": {
                "status" : "Ok",
                "recordMetadata" : {
                    "topicPartition" : {
                        "partition" : 0,
                          **"headers": {
                                  "Key": "Sample.Key",
                                  "Value": "Sample.Value"
                          },
                        "topic" : "demo-Kafka-Topic"
                    }
                }
            }
        }
```

**Comment by kt09** [comment]
@authorjapps - just touching base on this. Is there anything else I can provide here? When can I expect this feature to be available? Please advise.

**Comment by kt09** [comment]
@authorjapps Please review and approve the PR 
https://github.com/authorjapps/zerocode/pull/391

**Comment by authorjapps** [comment]
To be available in `V 1.3.20`

**Comment by kt09** [comment]
@authorjapps when will v 1.3.20 be available

**Comment by authorjapps** [comment]
@kt09 , Please check our release frequency [details(click me)](https://github.com/authorjapps/zerocode#quick-links) on the readme page.
Next one is around 21st May... Not too far from now.

But it would be great if you could take care of all the ACs prior to that. `AC2` seems like still pending. The ticket is with you currently and hoping it would be done asap if this is urgent!

Give us a shout here once done ✌️

**Comment by kt09** [comment]
@authorjapps apologies for the late response and sorry for not getting to AC2 before 21st. 
I will look into the AC2 and will reach out once I'm on it. And yes it is important! :)
Many thanks!

**Comment by authorjapps** [comment]
Hello @kt09 , Just checking... did you get chance to complete the AC2?
