### ISSUE TITLE
TestMethodOrder for load/stress junit5 test

### ISSUE THREAD

**Issue by jahluwalia** [authorjapps/zerocode#332]
I'm using your tool to load/stress test a java application using Junit5. If i have a single test class, is there a way to randomize the order in which each thread executes the tests? I tried prefacing the test class with `@TestMethodOrder(MethodOrderer.Random.class)` but that didn't seem to help.

My LoadClass is as follows:

```java
@ExtendWith({ParallelLoadExtension.class})
public class LoadTest {

    @Test
    @LoadWith("load_config.properties")
    @TestMappings({
            @TestMapping(testClass = CalculatorTests.class, testMethod = "addsTwoNumbers"),
            @TestMapping(testClass = CalculatorTests.class, testMethod = "subtractTwoNumbers")
    })
    public void testLoad() {
        /* No code needed here */
    }

}
```
 My test class is as follows:

```java
@TestMethodOrder(MethodOrderer.Random.class)
class CalculatorTests {


	@Test
	@DisplayName("1 + 1 = 2")
	void addsTwoNumbers() {
		Calculator calculator = new Calculator();
		assertEquals(2, calculator.add(1, 1), "1 + 1 should equal 2");
		System.out.println("a");
	}

	@Test
	@DisplayName("2 - 1 = 1")
	void subtractTwoNumbers() {
		Calculator calculator = new Calculator();
		assertEquals(1, calculator.subtract(2, 1), "2 - 1 should equal 1");
		System.out.println("b");
	}


}
```

It seems to always execute the methods in that order. Any suggestions? Also, can i assume that before, beforeeach, after, aftereach, will still work in the testclass?

thanks,
jas

**Comment by authorjapps** [comment]
@jahluwalia , we will have a look at this soon. Thanks for your patience.

**Comment by officiallysameer** [comment]
Hi @jahluwalia,
Do you have this code shared somewhere in a public repo. We can have a look.

Also, can you explain your use case for this requirement

**Comment by nirmalchandra** [comment]
@jahluwalia 
Are you lookin for something like below, where the order is not guaranteed?

<img width="1121" alt="image" src="https://user-images.githubusercontent.com/15079710/67872796-639de080-fb2a-11e9-8875-27a7cbd37193.png">

**Comment by jahluwalia** [comment]
Hi guys, 

I actually went with a different approach. I built up my class and put it in a container. So then i just spin up multiple instances of the container using --scale in docker compose. This simulates users hitting the machine. 

thanks,
jas

**Comment by officiallysameer** [comment]
@jahluwalia , sounds ok. Glad to know that.

I found this question also answered in StackOverflow([link to -Zerocode JUnit5 Load Testing](https://stackoverflow.com/questions/57849469/rest-api-load-tesing-zerocode-tdd-giving-error-message))

```
ramp.up.period.in.seconds=0 

Makes the order random. ~Sidd Gautama Oct 31 at 1:39
```

I am putting the below for everyone's benefit.
Docker `--scale` is fine, but my suggestion is more generic i.e. there is no need for Docker installation at the environment level (e.g. local laptop).

But when we are out of options we can go via --scale. Also easy if you already have containerised application setup.

Can you please add your dockerised code here for everyone's benefit?
