### ISSUE TITLE
How to store a value from a response from one step and reinject it in another step

### ISSUE THREAD

**Issue by schhor** [authorjapps/zerocode#344]
Hi,

I looking for this feature.

Read a value from a response of a step (API call) and reinject this value in a request of another step (API), because this value is a random uuid.

I have not found it in the documentation, but may be I have miss it.

thanks

**Comment by anishjha93** [comment]
Hey schhor,
See this example.

{
  "scenarioName": "customer Details",
  "steps": [
      {
             "name": "login",
            "url": "http://localhost:8080/login",
            "operation": "POST"
            "request": {
               "user":"anish",
               "password":"anish"
            },
            "assertions": {
            }
     },
    {
            "name": "get_customer",
            "url": "http://localhost:8080/login",
            "operation": "GET"
            "request": {
                 "headers":{
                     "${$.login.response.body.access_token}"    //response of login step (access_token)
                     } 
            },
            "assertions": {
            }
     }
  ]
}

**Comment by schhor** [comment]
@anishjha93 thanks so much
