### ISSUE TITLE
Ability to print custom log.

### ISSUE THREAD

**Issue by anishjha93** [authorjapps/zerocode#348]
Hi, There should be an option to print some custom log based on steps.

Suppose there will be the scenarios where user want to print their own log for particular step.

**Comment by authorjapps** [comment]
Thanks, sounds good. The PR is under review. 

Can you please update the below Wiki Page please with this(optional) field when you get chance?
[Wiki : What-is-Zerocode-testing](https://github.com/authorjapps/zerocode/wiki/What-is-Zerocode-testing)

**Comment by anishjha93** [comment]
Hi,
I will be happy to do this. please let me know how i will do that.
Because i am not getting any edit option there and also not able to commit the changes into  https://github.com/authorjapps/zerocode.wiki.git

**Comment by authorjapps** [comment]
Please check now. You need to accept the invitation before that(check your email please).

**Comment by anishjha93** [comment]
Hi,
added in step section.
https://github.com/authorjapps/zerocode/wiki/What-is-Zerocode-testing#customlog

**Comment by authorjapps** [comment]
This will be available in `v 1.3.17`.

_Due to end-of-year and X-mas time, we are experiencing a slight delay in the review and release processes.  We are trying our best to get the fixes released by early 2020._
