### ISSUE TITLE
Write a Wiki help-page on the usage of the system env variables and properties

### ISSUE THREAD

**Issue by authorjapps** [authorjapps/zerocode#361]
### AC
As an automation engineer or developer
I want a `Wiki Help Page` on the usages of the System Properties or System Env Variables and how they are accessed in the Zerocode steps
So that I can use them in my project when I have a use case to do so e.g. assigning a random port or using a random host or parameterized host from the system properties.

### Things to do
+ Visit these related issues 
  + #273 
  + #282 
  + #248 
+ Gather information
+ Organize and fill the below Wiki Page 👍 

Edit this page and add more details:
https://github.com/authorjapps/zerocode/wiki/Reading-System-Properties-and-Environment-Variables-in-Zerocode-Test-Steps

Please request for edit-access if you are facing any issues or finding it read-only.

**Comment by Rinita-De** [comment]
@authorjapps  - can I work on this ?

**Comment by authorjapps** [comment]
@Rinita-De , yes . Thanks! 
Can you check whether you have edit access to the Wiki page?

**Comment by Rinita-De** [comment]
@authorjapps  - No I dont have edit rights, can you please grant me the same?

**Comment by authorjapps** [comment]
ok.
Sen you an invitation.
Can you pls accept it and then check?

**Comment by Rinita-De** [comment]
Thanks, I have edit access now.

**Comment by Rinita-De** [comment]
@authorjapps  - I have updated the wiki. Please review and let me know your comments.

**Comment by authorjapps** [comment]
Thank you. Looks Fantastic! Great job.
Have you joined our [Slack](https://join.slack.com/t/zerocode-workspace/shared_invite/enQtNzYxMDAwNTQ3MjY1LTA2YmJjODJhNzQ4ZjBiYTQwZDBmZmNkNmExYjA3ZDk2OGFiZWFmNWJlNGRkOTdiMDQ4ZmQyNzcyNzVjNWQ4ODQ) and [Mailing-List](https://groups.google.com/forum/#!forum/zerocode-automation).
It will be nice to have a quick chat and if you can help us to improve other WIki Pages and other high priority issues.

**Comment by Rinita-De** [comment]
@authorjapps - I have joined both Slack and the mailing list. I would like to contribute to the project. We can catch up on slack.
