### ISSUE TITLE
Can i run on command line (CI/CD) without JUnit  ?

### ISSUE THREAD

**Issue by seebosmile** [authorjapps/zerocode#369]
Can i run on command line without JUnit  ?
So , I need test to RestAPI (Asp.net Core/OpenAPI/ Swagger)

**Comment by authorjapps** [comment]
@seebosmile , yes, you can. But we need to know more details around it. Will come back on this. 

Are you on Slack?

If not, can you please join [Slack](https://join.slack.com/t/zerocode-workspace/shared_invite/enQtNzYxMDAwNTQ3MjY1LTA2YmJjODJhNzQ4ZjBiYTQwZDBmZmNkNmExYjA3ZDk2OGFiZWFmNWJlNGRkOTdiMDQ4ZmQyNzcyNzVjNWQ4ODQ) and our [mailing-list](https://groups.google.com/forum/#!forum/zerocode-automation)?

**Comment by seebosmile** [comment]
@authorjapps  i join to Slack already , thank you
