### ISSUE TITLE
Can we ignore specific failing step

### ISSUE THREAD

**Issue by PrabaharanK** [authorjapps/zerocode#370]
Description: 

I'm writing zero code tests, 5-6 steps in the scenario. I assuming 3rd step could be failed. Because of 3rd step I don't want to say entire scenario is failed but what My expectation is runner should proceed to next steps. Any fails on 1st, 2nd, 4th, 5th and 6th step considered to be scenario failure except step 3rd. 

Any solution for this ?

**Comment by authorjapps** [comment]
Linked to https://github.com/authorjapps/zerocode/issues/339(Hover your mouse for details).

**Comment by sparrowV** [comment]
@PrabaharanK I guess the question is answered, hence closing this one. If you have other questions, please join our  [Slack](https://join.slack.com/t/zerocode-workspace/shared_invite/enQtNzYxMDAwNTQ3MjY1LTA2YmJjODJhNzQ4ZjBiYTQwZDBmZmNkNmExYjA3ZDk2OGFiZWFmNWJlNGRkOTdiMDQ4ZmQyNzcyNzVjNWQ4ODQ) , or open another issue.
