### ISSUE TITLE
Reports are being generated in subdirectories and zerocode-junit-interactive-fuzzy-search.html is not being genrated

### ISSUE THREAD

**Issue by gaurav1thakur** [authorjapps/zerocode#371]
AC: As a automation tester/developer reports must be generated for all scenarios 
**Note** ```/``` special characters including in scenario name for instance ```Scenario Test Pass/Fail```

**use-case example**
So I have multiple scenarios including one scenario "Scenario Test Pass/Fail" 
This creates a reports in different target directory structure with format
 ```zerocode-test-reports/Scenario Test Pass/FailTestID.json```
despite ```zerocode-junit-interactive-fuzzy-search.html``` extent report file is not being generated in this case

Scenario: "Verify Pass\/Fail with valid info..."
<img width="1437" alt="Target_Folder_Report_Generation" src="https://user-images.githubusercontent.com/38386418/77144959-3fc54200-6aad-11ea-9d62-77396b6fc4e8.png">

**Comment by authorjapps** [comment]
@gaurav1thakur , can you try to run this command from the `command line`?
> mvn clean

Then run your test from the `IntelliJ IDE` and see if it resolves.

**Comment by gauravkrthakur1** [comment]
hi @authorjapps tried to run after ```mvn clean```  , but no luck

**Comment by authorjapps** [comment]
@gaurav1thakur, Can you please put more details? Follow the guidelines link here [How to log an issue](https://github.com/authorjapps/zerocode/wiki/Guidelines-for-raising-issues)

**Comment by anishjha93** [comment]
Hi @gaurav1thakur,
Can you please try running with terminal 
 command :  mvn clean test -Dtest={you_test_class_name}
