### ISSUE TITLE
COVID-19 FAQs

### ISSUE THREAD

**Issue by authorjapps** [authorjapps/zerocode#373]
As a user
I want to know some DOs and DONTs in a day to day activities
So that I continue to do my job efficiently

Background
===
In the interest of the _Health and Safety_ of our users and all people, a simple FAQs page is needed to capture the best practices, DOs and DONTs etc.

Things to do
===
- List down the common FAQs
- List some healthy tips do at home e.g. 30min exercise tips
- List some healthy food habits to boost immunity
- List some healthy breathing practices
- Any more suggestions/advices...

**Comment by rafaelbalanquet** [comment]
Hello! My group and I would like to get working on this right away. Let me know if we can be assigned and if there are any more specifics regarding what you're looking for.

**Comment by authorjapps** [comment]
@rafaelbalanquet , thanks for your interest. You can please continue right away. Also kindly note down your approach here for everyone's benefit, please. Thanks

**Comment by griffinh1** [comment]
Hi @authorjapps, I am working with @rafaelbalanquet on this issue. I believe the plan would be to gather information from credible sources that fulfill some of the "Things to do" section. Should this be added to the end of the [README.md](https://github.com/authorjapps/zerocode/blob/master/README.md) file or a separate file?

**Comment by authorjapps** [comment]
Hi @griffinh1 , Thanks for your interest. I am also thinking on the simillar line. Let's put the contents into a separate page and link it from the README file.
I have created a page here for you to add those contents: [COVID19-FAQ](https://github.com/authorjapps/zerocode/wiki/COVID19-FAQ)

You can please add the contents, amend/delete/reorganize the titles to make it useful... 👍 

Once done, we can link it to the **readme** page.

**Comment by griffinh1** [comment]
@authorjapps I have collected all necessary information for this issue, when I go to push to the zerocode.wiki I am experiencing a  permission error. Do you have any specifics on how I should add to [COVID19-FAQ](https://github.com/authorjapps/zerocode/wiki/COVID19-FAQ)?

**Comment by authorjapps** [comment]
@griffinh1 , you can try editing the Wiki now after accepting the `collaboration invitation(check your email please)`

**Comment by griffinh1** [comment]
I have added the information on the branch called ISS-373-COVID19-FAQ.

**Comment by authorjapps** [comment]
@griffinh1 , sounds good! Thanks
Can you please add/edit directly to the Wiki and `save` please?

**Comment by griffinh1** [comment]
@authorjapps All changes are added. Thank you.

**Comment by authorjapps** [comment]
Looks Awesome! Great job @griffinh1 ! Thank you!
