### ISSUE TITLE
How to Calculate Code coverage

### ISSUE THREAD

**Issue by Pravintati** [authorjapps/zerocode#374]
Firstly this is not a issue, it's a query
If we use zerocode test framework in our project, then we are getting 0% coverage with UI based code coverage tools. How we will calculate Code coverage for the projects which are using zerocode as a testing.

**Comment by nirmalchandra** [comment]
@Pravintati , it depends how you have configured your CC tool. CC tools(e.g. Jacoco or Sonar ) is generally configured against your source main/production code(not the test code).

Basically what it means is : It's not dependent on `which` testing tool you use, but depends on the flexibility of the testing tool and `how` you have configured.

> 0% coverage with UI based code coverage tools

This is not part of the problem as UI just shows you the pretty graphs of the underlying coverage %age.

What would be more interesting to know is "How exactly you have configured your repo in the CI pipeline or in local maven/gradle ?"

**Comment by Pravintati** [comment]
I have configured jacoco CC tool in local maven. But not getting any code coverage for the test after successful run of test.

**Comment by aghorpade** [comment]
@Pravintati  - Jacoco CC tool will provide you code coverage on Unit tests which are in built in your project. Have you built in zerocode framework in your project or running as a separate project?

**Comment by Pravintati** [comment]
This is my testing code using zerocode

import static org.junit.Assert.*;

import org.jsmart.zerocode.core.domain.JsonTestCase;
import org.jsmart.zerocode.core.runner.ZeroCodeUnitRunner;
import org.junit.Test;
import org.junit.runner.RunWith;

//@TargetEnv("test_get.properties")
@RunWith(ZeroCodeUnitRunner.class)
public class GetFileTest {
	@JsonTestCase("test_get.json")
	@Test
	public void testGETOk() throws Exception {

	}
}

This is my Json Code
{
    "scenarioName": "Validate the GET Ok",
    "steps": [
        {
            "name": "get_test",
            "url": "http://localhost:8080/sample/adminops/datasources",
            "operation": "GET",
            "request": {
                "headers" : { 
                   "Content-Type" : "application/json"
                }
            },
            
            "assertions": {
                "status": 200,
                "headers" : { 
                	"Content-Type" : [ "text/plain;charset=UTF-8" ]
                },
                "body": {
                	"status": "Default Active DataSource = primary"
                }
            }
        }
   ]
}

**Comment by Pravintati** [comment]
The test are running fine but no code coverage reflecting in jacoco tool

**Comment by authorjapps** [comment]
> Have you built in zerocode framework in your project or running as a separate project?

Answer to the above question asked by Amit will help us to us to understand the problem better and propose a solution @Pravintati . 

Have you joined our [Slack](https://join.slack.com/t/zerocode-workspace/shared_invite/enQtNzYxMDAwNTQ3MjY1LTA2YmJjODJhNzQ4ZjBiYTQwZDBmZmNkNmExYjA3ZDk2OGFiZWFmNWJlNGRkOTdiMDQ4ZmQyNzcyNzVjNWQ4ODQ) and [mailing list](https://groups.google.com/forum/#!forum/zerocode-automation) ?

If you can ping this issue there in Slack, you might get a quicker response?

**Comment by Pravintati** [comment]
Have you joined our Slack and mailing list ? 
No

Have you built in zerocode framework in your project or running as a separate project?
Yes. I have included zerocode in pom.xml

**Comment by Pravintati** [comment]
@authorjapps, @aghorpade, @nirmalchandra,

Hey Guys, can anyone please help me to solve the above query.

**Comment by authorjapps** [comment]
Sorted out via the Slack conversation.

>Pravin Tati  15 hours ago
Hi @authorjapps
Thank You for your valuable inputs in discussion. As you said I tried that flow with sample single API project it worked and showing code coverage.

Thanks Pravin! Happy to see the above. 🤗
