### ISSUE TITLE
how to test SOAP XML result data

### ISSUE THREAD

**Issue by aghorpade** [authorjapps/zerocode#375]
I am trying to put a test case where soap service will be invoked and SOAP XML response will be returned back. I took a look on below scenario - to test SOAP XML test
https://github.com/authorjapps/zerocode/wiki/SOAP-method-validation-with-xml-input
I would like to test elements from SOAP response. can you let me know if it is possible?

If yes then how? if no then can you get a feature to test SOAP XML response data.

Let me know if you need more scenario or test data for this

**Comment by authorjapps** [comment]
Yes, it's possible.
It's explained [here (Click this)](https://github.com/authorjapps/zerocode/wiki/SOAP-method-validation-with-xml-input#convert-xml-to-json-and-assert-using-json-path) i.e. in the same Wiki page slightly towards the trail.

**Comment by macrocks** [comment]
yes, this is what i was looking for. Thanks a lot . we can close this thread. :)
