### ISSUE TITLE
Report to have the method details

### ISSUE THREAD

**Issue by authorjapps** [authorjapps/zerocode#378]
AC1:
As a developer
I want to see the methods failed in my automated tests
So that I can see the granular details in my report

**Comment by Vishalckc** [comment]
Can I work on this issue?

**Comment by authorjapps** [comment]
Available in `1.3.18`

**Comment by authorjapps** [comment]
Released: https://github.com/authorjapps/zerocode/releases/tag/zerocode-tdd-parent-1.3.18
