### ISSUE TITLE
How to read/load a certificate stored in a JKS (Java key stores) file format, in .NET (C#)

### ISSUE THREAD

**Issue by ykvichare** [authorjapps/zerocode#380]
How to read/load a certificate stored in a JKS (Java key stores) file format, in .NET (C#)

after load JKS file, how to validate certificate in .net C# ?

**Comment by authorjapps** [comment]
@ykvichare , Just double checking, is it related to Zerocode?

Can you please add slightly more details? 👍

**Comment by authorjapps** [comment]
Already resolved.
https://github.com/authorjapps/zerocode/issues/413#issuecomment-654093322
