### ISSUE TITLE
[Wiki][Doc] Write the Wiki Page for Automated testing for File upload validation

### ISSUE THREAD

**Issue by authorjapps** [authorjapps/zerocode#394]
As a developer or SDET
I want a help page or an use manual on `Automated File Upload Testing` linked from the Developer's Guide
So that I can verify my automation scenarios related to the file upload business case.

AC : Accesptance Criteria

AC1:
===
- Fill all the sections in this [Wiki page(ask for edit permission)](https://github.com/authorjapps/zerocode/wiki/File-Upload-Using-Http-API-Automated-Testing)
- Refer to this [issue(Click me)](https://github.com/authorjapps/zerocode/issues/107)

AC2:
===
- Link this from the Developer's guide page
- Find TOC link name `File upload using HTTP API`

**Comment by harshasridhar** [comment]
@authorjapps I'm a newbie, can I work on this?

**Comment by authorjapps** [comment]
@harshasridhar, Yes please. Thank for this.

**Comment by harshasridhar** [comment]
@authorjapps please provide me the edit access to wiki page.

**Comment by authorjapps** [comment]
Done.

**Comment by harshasridhar** [comment]
Should I fork the repo and raise a PR?
Committing to the main repo is denied
This is the error message
```remote: Permission to authorjapps/zerocode.wiki.git denied to harshasridhar.
fatal: unable to access 'https://github.com/authorjapps/zerocode.wiki.git/': The requested URL returned error: 403

**Comment by authorjapps** [comment]
@harshasridhar , you need to accept the below invitation and then directly can edit the page.
https://github.com/authorjapps/zerocode/invitations

> Should I fork the repo and raise a PR?

No.

**Comment by harshasridhar** [comment]
Have updated the documentation, please check it and let me know if any changes are to be made?
Will add test cases soon,  please let me know where to add them.

**Comment by authorjapps** [comment]
This is great! Looks awesome. Thank you 🙏 

> Will add test cases soon, please let me know where to add them.

Ok.
In the spring-boot HelloWorld project there are already working test-scenarios as examples. Can you please refer them in the `Conclusion` section? That will be useful for everyone, anyone can clone and run it locally 👍

**Comment by harshasridhar** [comment]
Can you please give me the details of the test cases, I did clone the project and tried to find it, but couldn't find it.

**Comment by authorjapps** [comment]
I have updated it now ✌️ . No worries. Thanks!
