### ISSUE TITLE
[Kafka] End-to-End Testing

### ISSUE THREAD

**Issue by jbiju94** [authorjapps/zerocode#396]
My current scenario is -

1. Using zerocode test framework I publish a message to a topic.
2. I have extended the ZeroCodeRunner to start my consumer also, which should ideally take the message from the topic, do some transformation, and publish it into a different topic.
3. I have added a zerocode step for consumption which checks the message is right or not.

So in total my json test case file has 2 steps- for publishing and consuming 

The end-goal is to check whether the transformation is right and the message are published from my consumer-producer to the right partition.

Would this scenario be possible using zerocode?

**Comment by authorjapps** [comment]
@jbiju94 , just to clarify:
e.g.
1. **Step-1** : Produce `Hello` to `order-topic`
2. The consumer via ZerocodeExRunner picks "Hello", then transforms to `Hello There` 
    - Then publishes to `order-new-topic`
3. **Step-2**: Consume from `order-new-topic` and asserts `Hello There`

> check whether the transformation is right and the message are published from my consumer-producer to the right partition.

Here, In the **Step-2** do you know the partition number to consume from? 
if so what's the `partition-number`?

Then in Step-2 you mention that number using `seek` like below:
```JSON
"seek": "order-new-topic,0,1"

Here 
order-new-topic : Your topic of interest
0 : Partition number
1 : Offset from where you want to read the message
```
Hope it helps!

Are you in Slack, if not can you join the **Kafka** channel and ping us in [Slack(Click)](https://join.slack.com/t/zerocode-workspace/shared_invite/enQtNzYxMDAwNTQ3MjY1LTA2YmJjODJhNzQ4ZjBiYTQwZDBmZmNkNmExYjA3ZDk2OGFiZWFmNWJlNGRkOTdiMDQ4ZmQyNzcyNzVjNWQ4ODQ)
