### ISSUE TITLE
Setting test category in the test

### ISSUE THREAD

**Issue by authorjapps** [authorjapps/zerocode#410]
Background:
===

From Slack:
Raised by @Julian

Hi guys, really nice framework. Would like to know how I can change the test category. The default is:
```java
String DEFAULT_REGRESSION_CATEGORY = "Regression";
```

AC1
===
As an SDET or Dev 
I want to set the test category at test level
So that I can get filter these tests in the HTML report after the test run

Things to do:
- e.g. Allow `#category1 #category2` in the test scenario free text
- Follow the implementation of `@Author1` which sets the filter for authors
  - Look for `ZeroCodeReportGeneratorImpl#optionalAuthor` method implementation and usage
- Do the similar impl for starting with `#free-text` and set to Extent category(which is currently set to `Regression`)

AC3
===
Allow
+ `@Author` for capturing author name e.g. David, Alex, Anton etc
   + Deprecate `@@Author`
+ `#Category` fro capturing category information e.g. DIT, DEV, SIT, Small-Regression, Smoke etc
 
Also relates to:
https://github.com/authorjapps/zerocode/issues/207 (not a AC of this ticket)

**Comment by harshasridhar** [comment]
@authorjapps, can I work on it?
Need some guidance though, as I'm relatively new to the code base.

**Comment by authorjapps** [comment]
@harshasridhar , please go ahead. Thanks!

Please ping us in Slack in case you need any help ✌️

**Comment by authorjapps** [comment]
Available in v `1.3.23`
