### ISSUE TITLE
System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel in C#

### ISSUE THREAD

**Issue by ykvichare** [authorjapps/zerocode#413]
I have written below code to make https connectivity between client and server in C#. 

Below code is working fine with win 10 but facing issue with Win 2019. 

             ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;        
            ServicePointManager.ServerCertificateValidationCallback += (a, b, c, d) => { return true; };            
            X509Certificate2 clientCertificate = new X509Certificate2(@"C:\..\keyfile.p12", "ASDDDDDDDDDDDDDD");            
            var handler = new HttpClientHandler();
            handler.ClientCertificates.Add(clientCertificate);

issue in window server 2019 : 
 “System.Net.Http.HttpRequestException: An error occurred while sending the request. --->  System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel”.

**Comment by authorjapps** [comment]
Related to #380 

@ykvichare just wondering, when exactly you encounter this issue?

You also raised 380 issue earlier, but did not add much details to the description ?

Are you writing an end to end scenario involving Kafka and Http?
or
Just HTTP with the X509 cert setup?

**Comment by ykvichare** [comment]
issue 380 resolved ... 
using keyfile.p12 (X509Certificate2 ) certificate for authentication for HTTPS connection. 

Above code is working fine with windows 10 machine but same code is not working windows server 2019.
Issue : The request was aborted: Could not create SSL/TLS secure channel .

Is any additional setting is required on Win 2019 ? 

Thanks,
Yuvraj

**Comment by ykvichare** [comment]
I am using keyfile.p12 (X509Certificate2 ) certificate for authentication for making HTTPS connection.

Above code is working fine with windows 10 machine but same code is not working windows server 2019.
Issue : The request was aborted: Could not create SSL/TLS secure channel .

Is any additional setting is required on Win 2019 ?

**Comment by authorjapps** [comment]
Just wondering @ykvichare , are you using a custom HTTP client with Zerocode to deal with the SSL?
