### ISSUE TITLE
Assertion fail

### ISSUE THREAD

**Issue by crauadams** [authorjapps/zerocode#416]
When I run the test, I got this response

java.lang.RuntimeException: Assertion failed for :-

  [Get property by closed date and city]
        |
        |
        +---Step --> [get_property_by_closed_date_and_city]

  Failures:
  ---------
  Assertion path '$.body[0].id' with actual value '1' did not match the expected value '1'

Scenario .json file
```JSON
{
  "scenarioName": "Get property by closed date and city",
  "steps": [
    {
      "name": "get_property_by_closed_date_and_city",
      "url": "/api/v1/property",
      "operation": "GET",
      "request": {
        "headers": {
          "Content-Type": "application/json",
          "Authorization": "Basic xxxxx"
        },
        "queryParams": {
          "closeDate": "12/19/2020",
          "city": "Sacramento"
        }
      },
      "assertions": {
        "status": 200,
        "body": [
          {
            "id": "${$.get_property_by_closed_date_and_city.response.body[0].id}",
            "import": null,
            "location": {
              "id": 2,
              "city": "",
              "county": "",
              "state": "",
              "country": ""
            },
            "originalValue": "",
            "jsonContent": "",
            "realEstateTransactionId": -1,
            "dateCreated": "2020-07-06T20:56:22.206",
            "listingId": "0",
            "propertyType": "0",
            "streetName": "0",
            "streetNumberNumeric": 0,
            "streetNumber": "",
            "unitNumber": "",
            "city": "0",
            "countyOrParish": "SA",
            "postalCode": "0",
            "stateOrProvince": "CA",
            "yearBuilt": 0,
            "closeDate": "2020-12-19",
            "closePrice": 0,
            "listPrice": 0,
            "originalListPrice": 0,
            "listingKey": "",
            "mlsAreaMajor": "",
            "mlsStatus": "S",
            "onMarketDate": "",
            "parcelNumber": "",
            "buyerAgentFullName": "",
            "buyerAgentMlsId": "",
            "listAgentFullName": "",
            "listAgentKey": "",
            "listAgentMlsId": "",
            "listOfficeKey": "",
            "listOfficeMlsId": "",
            "listOfficeName": "",
            "buyerOfficeKey": "",
            "buyerOfficeMlsId": "",
            "buyerOfficeName": "",
            "standardStatus": "S",
            "originalEntryTimestamp": "2019-10-29T10:22:59",
            "parties": "",
            "buyer1": "",
            "buyer2": "",
            "fullAddress": "",
            "modificationTimestamp": null,
            "propertySubType": null
          }
        ]
      }
    }
  ]
}
```

**Comment by authorjapps** [comment]
@crauadams , can you paste here your actual response?
You can get this from the console or from the log file.
Only the payload `body` with `id` field should do.

**Comment by crauadams** [comment]
```Response:
{
  "status" : 200,
  "headers" : {
    "Date" : [ "Wed, 29 Jul 2020 14:52:31 GMT" ],
    "Expires" : [ "0" ],
    "Transfer-Encoding" : [ "chunked" ],
    "Vary" : [ "Origin", "Access-Control-Request-Method", "Access-Control-Request-Headers" ],
    "X-Frame-Options" : [ "SAMEORIGIN" ],
    "Pragma" : [ "no-cache" ],
    "Set-Cookie" : [ "JSESSIONID=BC91B9F271A48E8923A5BDD0079AC205; Path=/api; HttpOnly" ],
    "Keep-Alive" : [ "timeout=60" ],
    "X-Content-Type-Options" : [ "nosniff" ],
    "X-XSS-Protection" : [ "1; mode=block" ],
    "Content-Type" : [ "application/json" ],
    "Connection" : [ "keep-alive" ],
    "Cache-Control" : [ "no-cache, no-store, max-age=0, must-revalidate" ]
  },
  "body" : [ {
    "id" : 13,
    "import" : null,
    "location" : {
      "id" : 2,
      "city" : "Sacramento",
      "county" : "SA",
      "state" : "CA",
      "country" : "United States"
    },
    "originalValue" : "",
    "jsonContent" : "",
    "realEstateTransactionId" : -1,
    "dateCreated" : "xxxx-xx-xxT20:17:12.931",
    "listingId" : "xxxxxx",
    "propertyType" : "xxxx" .... ```

**Comment by authorjapps** [comment]
Thanks for the response details.

### Solution:
> "id": "${$.get_property_by_closed_date_and_city.response.body[0].id}",

Update to

> "id": "(int)${$.get_property_by_closed_date_and_city.response.body[0].id}",

### Why ?
As your actual response is `"id" : 4690,` but you are asserting as `"id" : "4690",` , that's causing the problem. And Zerocode is saying that **string** "4690" in not equal to **integer** 4690. _The error message could be enhanced, I agree._

Give it a try and let us know!

**Comment by crauadams** [comment]
Thanks for your response, I'm still getting the same error.
 '$.body[0].id' with actual value '4690' did not match the expected value **'(int)4690'**

**Comment by authorjapps** [comment]
Which version of Zerocode you are using?
Can you update to version `1.3.23` and try?

**Comment by crauadams** [comment]
I was using 1.2.11, now it works! Thank you so much!

**Comment by crauadams** [comment]
Hi @authorjapps where can I found a document with all data type that I can cast ? Because I'm with a BigDecimal value now with the same error and when the value can be null too, eg: 

with actual value 'null' did not match the expected value:
$ONE.OF:[${$.get_property_by_closed_date_and_city.response.body[0].propertySubType}, $IS.NULL]

with actual value '45000.0' did not match the expected value '45000.0'

**Comment by authorjapps** [comment]
Hello @crauadams ,
If you are unsure about the data types, then better to use the below, which should cover your usecase:
>"id": "$EQ.${$.get_property_by_closed_date_and_city.response.body[0].id}",

`$EQ.` does a number value comparison irrespective of integer, float,long, BigDecimal etc...
Which passes for:
```
1=1 
1.5=1.5
-1=-1
left(actual)=right(expected)
```

> where can I found a document with all data type that I can cast ?

Have you searched the Wiki index ? If this is missing we will spin up a page soon(_sorry if this is the case, we will get this sorted soon_).

Also here are list currently supported which might be handy for you in your future usecases until we find the doc page for you.
```
(int)
(long)
(float)
(boolean)
```

**Comment by authorjapps** [comment]
A ticket has been raised now to solve this.  ✌️ 
https://github.com/authorjapps/zerocode/issues/420

**Comment by crauadams** [comment]
Yes, I search on Wiki's page but I didn't found anything about check the field types, only the values.

About the $EQ. I would like to test the structure of response not they values, to make sure that a data type change doesn't broken the UI.
