### ISSUE TITLE
Report DB e.g. H2 in-memory

### ISSUE THREAD

**Issue by dinesh76in** [authorjapps/zerocode#42]
@authorjapps, Can you redirect/persist the testcase and  test-run data into a in-memory DB e.g. H2 or give provision to configure in a DB as well as offline?

**Advantages**
This will provide some bit of useful information as well as  some kind of aggregated charts etc along with, it should allow to navigate to particular test log by a **color** code.

**Comment by authorjapps** [comment]
There are 3rd party libs as well as APIs, JavaScript libraries to just plugin and generate reports. But the current reporting provides quite `useful information` to track a **FAILED**(also PASSED ones) by response delay and the step information.

But the reporting is not limited to this. You can override this feature or provide more feature including retaining this, just by plugging in another ready made reporting lib or writing your **own customized reporting** solution.

See the class - `ZeroCodeTestReportListener` in the package `org.jsmart.zerocode.core.engine.listener` to deal with report.

**Comment by authorjapps** [comment]
Please check `target/zerocode-interactive.html` which gets `aggregated` after each run. It `stores` the previous test run statistics(if not forcibly cleared).
Also it has `searchable` filters by `author, by `Correlation-ID` etc and many more features.

**Comment by authorjapps** [comment]
Fixed long ago.
