### ISSUE TITLE
KafkaReceiver does not account for consumer group joining

### ISSUE THREAD

**Issue by ddingel** [authorjapps/zerocode#421]
Description
===
Following up the discussions in this issue [Kafka-produce and consume JSON message, Assert fails for 'consume' operation
](https://github.com/authorjapps/zerocode/issues/237#issuecomment-678478344) KafkaReceiver currently does not track if the consumer group joining has finished.

## The Problem Statement
If the consumer group join takes longer than `maxNoOfRetryPollsOrTimeouts * pollingTime` the consumer will not process any messages and report an empty record set. This situation also aften expects the `pollingTime` to be adjusted while running in different hardware configuations such as inside a docker or a standalone Jenkins or laptop etc, which is not a very good user/automation experience.

## Solution
AC1 :
A fix could be to modify the receiving part, that the consumer tries to successfully join the consumer group and if that fails err out with an explanation.

AC2:
As explained [here](https://github.com/authorjapps/zerocode/issues/237#issuecomment-678478344)
+ Do a first poll outside of the loop to trigger the consumer group rebalancing
+ Ignore any runs if there is no assignment for that consumer
  + i.e. Do not increase `maxNoOfRetryPollsOrTimeouts` if there is no assignment
  + i.e. Increase the `maxNoOfRetryPollsOrTimeouts` only if there was an successful assignment

**Comment by authorjapps** [comment]
Available in `1.3.24`. Yet to release.

**Comment by authorjapps** [comment]
Released.
See [Release Notes](https://github.com/authorjapps/zerocode/releases/tag/zerocode-tdd-parent-1.3.24) here.
