### ISSUE TITLE
Useful Reports - PASS FAIL Spike, CSV and Aggregated Charts

### ISSUE THREAD

**Issue by albertosipov** [authorjapps/zerocode#43]
Hello, I am using this in a financial project as it it's quite easy and helps to write quality tests.
How does `zerocode` support spike chart showing PASS/FAIL result of the tests run? Can you plugin a dashboard to the CSV report?

How to trace a test into the log file?- e.g. 
In case I need to know which particular `step` failed in a `scenario` just by looking at the chat/report? Color code will be useful! I don't want to see a aggregated fancy chart and drill down to get into it.

I am ok with optional time delay counter value if it provides against `step` info, not against the test scenario. 
Anyway `JUnit`, `maven sure file` or `maven-fail-safe` plugin provides Test case wise and scenario wise report out of the box in a tabular format, but only assertion failures level, not enough to trace a TestCase.

Any pointer towards this will help, Thanks

**Comment by authorjapps** [comment]
@albertosipov , actually you can do anything with chart when you have appropriate data/collections of `test-run` data.
For the sake of your sorting out your issue as well as for your awareness, `Zerocode` produces three types of report(useful ones)-
1. CSV report -Most useful(cool) as you can sort, filter, share using Microsoft Excel.
1. Spike chart(disabled by default) -Instantly eye goes to the taller and smaller spike or red spike -also cool ones
2. Interactive Report - You can filter and search by author or test-correlation-id etc -neat one

fyi-
There is no dashboard on the Spike Chart, but there is dashboard on the interactive chart.
See [Charts and Reports](https://github.com/authorjapps/zerocode#generated-reports-and-charts) in the README.md.
