### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by ankita2210** [authorjapps/zerocode#433]
In the Introduction section : 
Response:
```
{
    "id": 123,
    "type": "Premium High Value",
    "addresses": [
        {
            "type":"home",
            "line1":"10 Random St"
        }
    ]
}
```
All the validators described in the README.md have written the value of  type field as  **Premium Visa** instead of  **Premium High Value** .

Kindly allow me to fix it by assigning this issue to me.

**Comment by authorjapps** [comment]
@ankita2210 , thanks for noticing this. Can you raise a PR please with the changes?

**Comment by ankita2210** [comment]
Sure will do this
