### ISSUE TITLE
Help needed - sending integer in request

### ISSUE THREAD

**Issue by automatedbegginer** [authorjapps/zerocode#446]
AC1:
As an automation tester
I want `"caption": "(int)${RANDOM.UUID}"` to be resolved to `"caption": 123456` instead of `"caption": "123456"`
So that I can pass an int field to the server application.

AC2:
Update the [documentation page](https://github.com/authorjapps/zerocode/wiki/Token:-Random-Number) when ready.

***

Hello,

I may be blind or stupid :) , but i cant find how to send integer in request body.
 example: 
`"body": {
          "caption": "${RANDOM.UUID}",
          "external_id": "${RANDOM.NUMBER}"
        }
      }`

Is there any way to send body.external_id as integer when we are using randomizers?

Thanks in advance

BR

AB

**Comment by RDBreed** [comment]
As far as I could see, this is not possible out-of-the-box. If it is however really desirable, there would be quit a change (the ${} is substituted only, not the surrounded double quotes)...

**Comment by automatedbegginer** [comment]
I mean, its not big problem cuz apps are trying to convert str to integer so it works, but would be nice to have control.

**Comment by authorjapps** [comment]
Thanks, Happy to know @automatedbegginer.
However we will raise a TECH-DEBT for this to address this. 
Something like 
"caption": "(int)${RANDOM.UUID}" should help.

**Comment by rmccarter721** [comment]
I am going to look at implementing this as a first feature.

I know AC1 lists the syntax as: `"caption": "(int)${RANDOM.UUID}"` which follows the java casting style.
From a limiting code change perspective and trying to prevent unintended functionality to users (who may be trying to pass in a static value of (int)) I think something like: `"caption": "${(int)RANDOM.UUID}"` is better as it ties the data type directly into the ZeroCodeValueToken expression
