### ISSUE TITLE
Losing order of steps

### ISSUE THREAD

**Issue by romrich** [authorjapps/zerocode#447]
Problem Statement
===
For review purposes is it useful to use HTML report site to go through all plan steps (step by step)

Currently the system is doing this way:
when a HTML page is generated the plan steps are not in the same order as they were executed, e.g

steps in a yml file:
-- init
-- execute
-- check results

steps in HTML report
-- execute
-- check results
-- init

Expected:
steps in a yml file:
-- init
-- execute
-- check results

steps in HTML report
-- init
-- execute
-- check results

Potential Solution
===

https://github.com/authorjapps/zerocode/blob/357e2f6351c76b496a820a6d0c9e99c09bbffeb8/core/src/main/java/org/jsmart/zerocode/core/report/ZeroCodeReportGeneratorImpl.java#L94

**Comment by RDBreed** [comment]
It says in one of the tests "order different to original: Not really an issue, as the CSV can be sorted ACS or DESC by a an external tool". Changing this to keep the same order would be simple though.
Could you explain why it would be an issue for you?

**Comment by romrich** [comment]
when a HTML page is generated the plan steps are not in the same order as they were executed, e.g

- steps in a yml file:
-- init
-- execute
-- check results

- steps in HTML report
-- execute
-- check results
-- init

**Comment by romrich** [comment]
a possible fix:

`    List<ZeroCodeReportStep> getUniqueSteps(List<ZeroCodeReportStep> steps) {
        Map<String, ZeroCodeReportStep> result = new HashMap<>();
        ArrayList<String> sequenceOfCorrelationIds = new ArrayList<>();
        steps.forEach(step -> {
            result.merge(step.getCorrelationId(), step,
                    (s1, s2) -> RESULT_PASS.equals(s1.getResult()) ? s1 : s2);
            if (!sequenceOfCorrelationIds.contains(step.getCorrelationId())) {
                sequenceOfCorrelationIds.add(step.getCorrelationId());
            }
        });
        ArrayList<ZeroCodeReportStep> resultSteps = new ArrayList<>(result.size());
        sequenceOfCorrelationIds.forEach(correlationId -> resultSteps.add(result.get(correlationId)));

        return resultSteps;
    }
`

**Comment by johnc2017** [comment]
I have the same issue. Would be good if this can be fixed

**Comment by RDBreed** [comment]
> a possible fix:
> 
> ```java
>     List<ZeroCodeReportStep> getUniqueSteps(List<ZeroCodeReportStep> steps) {
>         Map<String, ZeroCodeReportStep> result = new HashMap<>();
>         ArrayList<String> sequenceOfCorrelationIds = new ArrayList<>();
>         steps.forEach(step -> {
>             result.merge(step.getCorrelationId(), step,
>                     (s1, s2) -> RESULT_PASS.equals(s1.getResult()) ? s1 : s2);
>             if (!sequenceOfCorrelationIds.contains(step.getCorrelationId())) {
>                 sequenceOfCorrelationIds.add(step.getCorrelationId());
>             }
>         });
>         ArrayList<ZeroCodeReportStep> resultSteps = new ArrayList<>(result.size());
>         sequenceOfCorrelationIds.forEach(correlationId -> resultSteps.add(result.get(correlationId)));
> 
>         return resultSteps;
>     }
> ```

Thanks for the suggestion, I think a LinkedHashMap instead of a regular HashMap would already do the right thing... :) Didn't have time to look at it further, but will try to look at it one of these days! ;)

**Comment by authorjapps** [comment]
@romrich , could you please add more details to the ticket? Currently it has a subject line "Losing order of steps" and some suggestion to a problem. But the problem has not been clearly outlined.
I have put the placeholders to fill it.

This will help everyone to understand the issue and to come up with a potential solution or answer!

**Comment by romrich** [comment]
@authorjapps, added more details for the issue...

**Comment by sparrowV** [comment]
@romrich  @RDBreed  @johnc2017  If you sort the data in ascending order by requestTimeStamp, it will show the same order as in scenarios. For sure, it will be better if the report is generated already sorted by requestTimeStamp.

**Comment by sparrowV** [comment]
Solved by [this pull request](https://github.com/authorjapps/zerocode/pull/479)
