### ISSUE TITLE
Integrate Spike Chart with Interactive Html report

### ISSUE THREAD

**Issue by authorjapps** [authorjapps/zerocode#45]
- Spike chart is disabled by default
- When Spike chart is enabled, provide a link on the top of the page of interactive chart

This will help the testers to navigate easily to spikes to figure out the `most delayed` test-steps and the `failed test steps` **without** going through the entire interactive html.

This is an enhancement.

Refer the `ReportListener` code for this.

**Comment by authorjapps** [comment]
Please create a branch called `ISSUE-45_link_charts` for this feature for the fork and PR.

**Comment by nirmalchandra** [comment]
Note-
@authorjapps , While reviewing this PR, if you want to `run and see` the report, then make sure you enable `spike.chart`  i.e. by marking it to `true`. Otherwise you may not see the link and the report just runs normally without the link.

**Comment by nirmalchandra** [comment]
PR pending your approval !
