### ISSUE TITLE
Pass information between step files

### ISSUE THREAD

**Issue by r5k5** [authorjapps/zerocode#461]
I have 2 single-step JSON files both of which make API calls to an external service. I have included both the files as steps in a test JSON file. I wanted to use a response field of the first API as a request field of the second API. 

Is this possible?

**Comment by sparrowV** [comment]
@r5k5  yes its possible. lets say request field name is reqParamName, you could write smth like this:   `reqParamNam: "${$.first_step_name.response.body.id}" `   where `first_step_name` is the name you named your first step, and `id` is the parameter  that you want value from ( you should change that according to your needs, in your case it most certainly  will have  a different name).  Give it a try

**Comment by r5k5** [comment]
Thanks, @sparrowV.
