### ISSUE TITLE
Unable to send epoc time using LOCAL.DATE

### ISSUE THREAD

**Issue by vinod-191gs** [authorjapps/zerocode#465]
Unable to send epoc time using LOCAL.DATE

**Comment by sparrowV** [comment]
hey @vinod-191gs . Can you provide more information? The scenario you are trying to run, logs and so on. Thanks

**Comment by vinod-191gs** [comment]
I am trying send epoch time in the payload instead of formatted date but there is no option to send epoch time in the payload.
This is a new feature i am requesting to implement.

**Comment by sparrowV** [comment]
@vinod-191gs  there might be simpler way to do it , but this is one way to do it: The idea is to have a first step that calls our  method, that returns epoch time (or anything you want) and then use that response in second step, like this:

```
"steps":[
        {
            "name": "get_epoch_time",
            "url": "Main",
            "method": "getEpoch",
             "assertions": {
                  }

        },{
         "name": "execute_java_method",
                    "url": "Main",
                    "method": "testEpoch",
                    "request":"${$.get_epoch_time.response}",
                     "assertions": {
                          }
        }
        ]

```

so In step 1 I call getEpoch method of Main class that returns epoch time. In step two I use that with ``` ${$.get_epoch_time.response}```  (keep in mind that  ```get_epoch_time``` this is the name of first step, you most certainly will have a different name so use that ). So in step two I call testEpoch method and I pass the epoch time returned from step one(you might call some api with that time or anything you want).

**Comment by sparrowV** [comment]
@vinod-191gs Hey mate, I think this issue is done. For more questions, you can join our  [Slack](https://join.slack.com/t/zerocode-workspace/shared_invite/enQtNzYxMDAwNTQ3MjY1LTA2YmJjODJhNzQ4ZjBiYTQwZDBmZmNkNmExYjA3ZDk2OGFiZWFmNWJlNGRkOTdiMDQ4ZmQyNzcyNzVjNWQ4ODQ) <br/>
