### ISSUE TITLE
WireMock: Not able to mock url path only regardless the query parameters

### ISSUE THREAD

**Issue by MrXavier** [authorjapps/zerocode#472]
It's not possible to mock url path only using WireMock solution Zerocode provide for step scenarios. Because of that it's not possible to mock a simple url without considering the query parameters. This is easily fixed by using WireMock method called `urlPathEqualTo(url)` [more here](http://wiremock.org/docs/request-matching/).

Solution: A simple and easy solution would be to change `RestEndPointMocker.class` to use `urlEqualTo(url)` if the url has query parameters and `urlPathEqualTo(url)` if the url doesn't have query parameters. To check if url has parameters we can just check for `?` character is placed in the url.

**Comment by sparrowV** [comment]
Hey @MrXavier  , can you provide more details about what kind of url mocking are you talking about?
It would be great if you could provide some scenario file or part of it which uses the mocking that is implemented now VS 
scenario file after integrating your suggestion. Thanks

**Comment by MrXavier** [comment]
Hello @sparrowV, I'm talking about mocking only the path of a http request, disregarding the query parameters. For instance, if I mock the path `cart/price`, then the request `cart/price?para1=value1&param2=value2` won't be matched and the mock's response won't be returned.

Example of a mock step scenario that should work for the path `cart/price` regardless the query params but currently  isn't working.
`
...
"mocks":
[
    {
        "name": "mocking_a_GET_endpoint",
        "operation": "GET",
        "url": "cart/price",
        "response": {
            "status": 200,
            "headers": {
                "Accept": "application/json"
            },
            "body": {
                "id": "UK001",
                "price": "33,00"
            }
        }
    }
]
...
`
Hope this helps.

**Comment by sparrowV** [comment]
@MrXavier  thanks for clarification. if you   make url  `"url": "cart/price?param1=param1"` it should work.

**Comment by MrXavier** [comment]
@sparrowV Yes you are right, let me add one more detail in my problem, the query parameter is not static. They change every request. by it generating a new value. For example first it receives `cart/price?uuid=123-456-789` then in a second test it receives `cart/price?uuid=555-666-999`. Thank you for bring this up and to allow me to clarify the issue.

I created a PR where the issue is fixed. Feel free to take a look: https://github.com/authorjapps/zerocode/pull/475

**Comment by authorjapps** [comment]
Hello @MrXavier , can you [join our Slack](https://join.slack.com/t/zerocode-workspace/shared_invite/enQtNzYxMDAwNTQ3MjY1LTA2YmJjODJhNzQ4ZjBiYTQwZDBmZmNkNmExYjA3ZDk2OGFiZWFmNWJlNGRkOTdiMDQ4ZmQyNzcyNzVjNWQ4ODQ) ?
Also, then pls accept the [collaboration invitation](https://github.com/authorjapps/zerocode/invitations) for branching out the repo and raising the PR.

**Comment by authorjapps** [comment]
Available in release v [1.3.28](https://github.com/authorjapps/zerocode/releases/tag/zerocode-tdd-parent-1.3.28)
