### ISSUE TITLE
why scenarios steps in zerocode-junit-interactive-fuzzy-search.html report are not displayed the same as they are in the scenario json

### ISSUE THREAD

**Issue by sduong1207** [authorjapps/zerocode#477]
why steps in zerocode-junit-interactive-fuzzy-search.html report are not displayed in order as they are in the json scenarios file
For example:
My scenarios in json file, I defined below steps:
```
{
  "scenarioName": "Add Clusters: GIVEN- environment variables endpoint, WHEN- I invoke POST request, I will be able to add/update cluster for my environment",
  "ignoreStepFailures": false,
  "steps": [  
    {
      "name": "check_account",
      "url": "/accounts/${account.name}",
      "method": "GET",
       .....
    },
    {
      "name": "check_solutions",
      "url": "/accounts/${account.name}",
      "method": "GET",
       .....
    },
  {
      "name": "create_environment",
      "url": "/accounts/${account.name}",
      "method": "POST",
       .....
    }
]
}
```
In zerocode-junit-interactive-fuzzy-search.html report, the steps are displayed as 
   create_envrionment
   check_solutions
   check_account

I expected to see the report should be displayed as
   check_account
   check_solutions
   create_environment

**Comment by sparrowV** [comment]
Hey, @sduong1207 . It's definitely not a bug, seems like nice to have  feature. For questions, you can join our [Slack](https://join.slack.com/t/zerocode-workspace/shared_invite/enQtNzYxMDAwNTQ3MjY1LTA2YmJjODJhNzQ4ZjBiYTQwZDBmZmNkNmExYjA3ZDk2OGFiZWFmNWJlNGRkOTdiMDQ4ZmQyNzcyNzVjNWQ4ODQ) <br/>

**Comment by lankor** [comment]
I raised a PR to fix the issue.
The thing is the code was using a `HashMap`  and it needs a `LinkedHashMap` to keep the steps order.

**Comment by authorjapps** [comment]
Available in the next release. Version `1.3.28`
