### ISSUE TITLE
Does zerocode not allow comparison of arrays dynamically? 

### ISSUE THREAD

**Issue by TurbulentCupcake** [authorjapps/zerocode#485]
For example, if my response body has the following: 
` {
                    "type" :  #"HIGH-VALUE",
                    "persons":[
                        {
                            "id": "120.100.80.03",
                            "name": "Dan"
                        },
                        {
                            "id": "120.100.80.11",
                            "name": "Mike"
                        }
                    ]
  }`

whereas the response body i would like to verify against is the following:
` {
                    "type" : "HIGH-VALUE",
                    "persons":[
                        {
                            "id": "120.100.80.11",
                            "name": "Mike"
                        },
                        {
                            "id": "120.100.80.03",
                            "name": "Dan"
                        }
                    ]
  }` 

Zerocode will indicate that the two bodies don't match, although they are in fact the same. Is there no way to check if equivalency in the example indicated above? 

It is indicated [here](https://github.com/authorjapps/zerocode/wiki/Array-assertions-made-easy--e.g.-SIZE,-element-finder) that order of the elements don't matter, however this is clearly not the case in practice. Does "order" mean order of the array elements or key-value pairs in the json? 

The issue described here https://github.com/authorjapps/zerocode-hello-world/issues/16 seems to mention checking array values individually, but this isn't feasible when the response body is large

**Comment by sparrowV** [comment]
Greetings, @TurbulentCupcake . With regard to array validation, order means the order of elements. With matches like `verify `and `assertions` you have to have the exact same order as response. You can use validators, but there also you need to check for each specific element. If you want to implement some custom behaviour, you need to do it via method execution from a step. I actually talk about this [here](https://www.youtube.com/watch?v=sLuRoigQfBg). 

You can join our [Slack](https://join.slack.com/t/zerocode-workspace/shared_invite/enQtNzYxMDAwNTQ3MjY1LTA2YmJjODJhNzQ4ZjBiYTQwZDBmZmNkNmExYjA3ZDk2OGFiZWFmNWJlNGRkOTdiMDQ4ZmQyNzcyNzVjNWQ4ODQ)

**Comment by TurbulentCupcake** [comment]
Are there plans to include functionality enabling the case i described in the issue? I imagine its a common scenario that objects in an array included in the response may not necessarily be in the same order for every call made with the same body

**Comment by sparrowV** [comment]
We need to get feedback from others too on this one. We might do smth like Jetbrains has where people vote for a specific feature. Meanwhile, as I said, you can validate it with a java method call.
