### ISSUE TITLE
Is it possible to disable the test reports in zerocode

### ISSUE THREAD

**Issue by Charlie971** [authorjapps/zerocode#495]
Hello guys,

I use zerocode for some Kafka tests. And I have a question about the test reports. It's possible to disable the test report generation after a test ? If yes what command I need to use on the properties file ?

Thanks very much for your help

Regards 

Charlie.

**Comment by sparrowV** [comment]
Hi @Charlie971. You can use `interactive.html.report.disabled=true` to disable HTML interactive chart.

You can also join our  [Slack](https://join.slack.com/t/zerocode-workspace/shared_invite/enQtNzYxMDAwNTQ3MjY1LTA2YmJjODJhNzQ4ZjBiYTQwZDBmZmNkNmExYjA3ZDk2OGFiZWFmNWJlNGRkOTdiMDQ4ZmQyNzcyNzVjNWQ4ODQ) channel for discussion.

**Comment by Charlie971** [comment]
thanks very much
