### ISSUE TITLE
Date assertion after and before java LocalDateTime

### ISSUE THREAD

**Issue by authorjapps** [authorjapps/zerocode#5]
> Work branch: issue5_after_before_date
> i.e. https://github.com/authorjapps/zerocode/tree/issue5_after_before_date

e.g.
"startDateTime": "$DATE.AFTER:2015-09-14T09:49:34.000Z"
"endDateTime": "$DATE.BEFORE:2015-09-14T09:49:34.000Z"

> See implementation of $GT.
> Trace code:     public static final String ASSERT_VALUE_GREATER_THAN = "$GT.";

### Update:
`$DATE.BEFORE` to `$LOCAL.DATETIME.BEFORE` to avoid confusion in the future.
Also same for
`$DATE.AFTER` to `$LOCAL.DATETIME.AFTER`

**Comment by ispandey81** [comment]
Hi, I would like to contribute to this project. I am a beginner to open source contribution. Please let me know if i can work on any issue or enhancement.
Thanks,
Indra

**Comment by authorjapps** [comment]
Sure, Sounds cool @ispandey81 ,
You can please pick this issue or any other issue which you think is good for the first time. I would suggest to pick a simpler one. This issue is also a simpler one.

Kindly read the [CONTRIBUTING.MD](https://github.com/authorjapps/zerocode/blob/master/CONTRIBUTING.md) which will make things easy. 
And  then could you please join our mailing/gitter lists below.

- Join the collaborators mailing list 
https://groups.google.com/forum/#!members/zerocode-automation

- Join Gitter room
https://gitter.im/zerocode-testing/help-and-usage

**Comment by jbonn360** [comment]
Hi, 

I'd like to work on this issue if that's ok. Please assign it to me.

Thanks

**Comment by authorjapps** [comment]
@jbonn360, thanks, please proceed. Let us know in case you need any heads up please!

@ispandey81, hope you are ok with this as it's been long time the ticket has not been worked upon!
 You can review the PR for your learning(in case it interests you)!

**Comment by jbonn360** [comment]
@authorjapps Cheers! One question, should we support any other datetime formats apart from ISO8601 (as in '2015-09-14T09:49:34.000Z')?

**Comment by ispandey81** [comment]
Hi,

I apologise for not being able to start work on this issue. Happy for it to
be picked up by someone else. Will look for a different issue from the list.

Cheers,
Indra

**Comment by jbonn360** [comment]
@ispandey81 Thank you Indra 🙏

**Comment by authorjapps** [comment]
PR looks great with great test coverage! Thanks @jbonn360. 

`Version 1.3.9` will contain this feature.

**Comment by authorjapps** [comment]
@jbonn360 , can you help us here to amend this PR or raise a new PR please? 🙏 

We need to amend these tokerns to be consistent with the simillar tokens already in use.
_Apologies for the late intimation._

`$DATE.BEFORE` to `$LOCAL.DATETIME.BEFORE` to avoid confusion in the future.
Also same for
`$DATE.AFTER` to `$LOCAL.DATETIME.AFTER`

Thanks for understanding!

**Comment by jbonn360** [comment]
@authorjapps no worries, I'll submit a new PR

**Comment by authorjapps** [comment]
Feature available in version 1.3.9 and higher.
