### ISSUE TITLE
Asserting an exception in ZeroCode for Kafka ACL testing

### ISSUE THREAD

**Issue by arpan57** [authorjapps/zerocode#508]
I am trying to test a kafka reader writer scenario where the user has permission to write to the topic, but does not have permission to read from that topic.

The java code looks like this :

```
@TargetEnv("kafka_servers/kafka_test_server.properties")
@RunWith(ZeroCodeUnitRunner.class)
public class KafkaConsumeJsonTest {

@Test
@Scenario('path/to/writer-can-write-but-cannot-read.json')
public void test writerWritesButCantRead(){}

}

```

The corresponding JSON looks like this :
```

{
  "scenarioName": "Writer can write to a topic but cannot read from it",
  "steps": [{
      "name": "write to test topic",
      "url": "kafka-topic:test-topic",
      "operation": "produce",
      "request": {
        "records": [{
          "key": "101",
          "value": "Hello World"
        }]
      },
      "assertions": {
        "status": "Ok",
        "recordMetadata": "$NOT.NULL"
      }
    },

    {
      "name": "onload_kafka",
      "url": "kafka-topic:test-topic",
      "operation": "unload",
      "request": {
        "consumerLocalConfigs": {
         "recordType": "JSON", 
         "maxNoOfRetryPollsOrTimeouts": 3
        }
      },
      "assertions": {
        "status": "Failed",
        "message": "Caused by: org.apache.kafka.common.errors.GroupAuthorizationException: Not authorized to access group: my-group"
      }
    }
  ]
}

```

When I run the test I encounter :

`java.lang.RuntimeException: org.apache.kafka.common.errors.GroupAuthorizationException: Not authorized to access group: my-group. `

This is a valid exception and I would to assert that in my test code to prove that the user cannot read from the topic with my-group as gorup-id.
How do I assert this in the test case or in the scenario JSON?

**Comment by sparrowV** [comment]
@arpan57  Hi. As I understand the exception fails the step, which fails the scenario, right?

**Comment by arpan57** [comment]
Hi,
Yes, the runtime exception fails the test case, where as I am expecting that exception and want to assert it. Can we assert the exception message (string) or exception type ?

**Comment by sparrowV** [comment]
@arpan57 I dont see out of the box solution here. What you can do it create your own custom kafka client, where insteaed of throwing exception you catch exception and return message. You then need to reference that custom kafka client in the test.

Customer Kafka client example [here](https://github.com/authorjapps/zerocode/blob/master/kafka-testing/src/main/java/org/jsmart/zerocode/kafka/MyCustomKafkaClient.java)

How to reference your customer kafka client [here](https://github.com/authorjapps/zerocode/blob/master/kafka-testing/src/test/java/org/jsmart/zerocode/integration/tests/more/customclientsuite/KafkaProduceCustomClientSuiteTest.java)

Hope this helps.

**Comment by arpan57** [comment]
Thank you @sparrowV . I will try this next week. 
Cheers.

**Comment by sparrowV** [comment]
@arpan57  Yeah example was with test suite but you can change to your needs quick easily. Glad it was helpful. Btw, you can join our [Slack](https://join.slack.com/t/zerocode-workspace/shared_invite/enQtNzYxMDAwNTQ3MjY1LTA2YmJjODJhNzQ4ZjBiYTQwZDBmZmNkNmExYjA3ZDk2OGFiZWFmNWJlNGRkOTdiMDQ4ZmQyNzcyNzVjNWQ4ODQ)  for more discussion etc.

**Comment by arpan57** [comment]
Thanks.
