### ISSUE TITLE
Two CSV reports are generated per run

### ISSUE THREAD

**Issue by officiallysameer** [authorjapps/zerocode#51]
@authorjapps 
Observation-
It seems like two reports are generated per run, in a maven module.

Could you please explain why two?

**Comment by authorjapps** [comment]
@officiallysameer , Ideally we should have a Suite runner which executes `as a suite of tests`. But practically it is not ideal world, hence we exist. The reports are generated `per runner,` then aggregated. That means even if you fire the unit test(s) with`@Test` simply from your IDE or using maven via command line, you will get a report generated(`timestamped`) for that run. Not many tools give this option.

Generally most tools generates the reports only after all test-run finished towards the end of `maven install` phase or if the tests are made to run via `<goal>integration-test</goal>` where one has to wait till that phase gets over to get the reports.

But `Zerocode` has gone extra miles to make this **handy** for testers/developers-
- You run a test, then you have a report by timestamp in the target folder
- You run more tests, then you have another report for this run by timestamp in the  target folder

Hence even if you are seeing two reports towards end of the build cycle, they should be identical as by that time(end of the maven cycle) results have been already aggregated, So you can pick any one of the report. Please pick the one with `latest timestamp`.

Hope it helps!

Note- 
Don't forget to look at the target folder for `zerocode-interactive.html` report which could be useful in term of searching by `TEST-STEP-CORELATION-ID` or by `author` of the test case or simply by test case name. On the right side of each item clicked, it lists the `steps executed` with their status.

**Comment by nirmalchandra** [comment]
Looks like the feature(though it is great) might not be much useful to end users. Probably we can `switch off/on` when needed "per runner" wise in future.
I will be fixing it with a single CSV file picking all step-results and amending to a final `report.csv`.
(anyway this is a minor one)

**Comment by authorjapps** [comment]
Fixed in version-
```
<dependency>
    <groupId>org.jsmart</groupId>
    <artifactId>zerocode-rest-bdd</artifactId>
    <version>1.1.34</version>
</dependency>
```
