### ISSUE TITLE
Test Request/Response in interactive report

### ISSUE THREAD

**Issue by dinesh76in** [authorjapps/zerocode#52]
Currently interactive reports display the individual steps pass/failure in specific test. 
It would be nice to have requests/responses at the step level displayed as well.

**Comment by aghorpade** [comment]
Not necessarily `SUCCESS` log, but at least Failure log trail e.g. `Request/Actual Response/Assertions` is displayed or `navigation/link` towards similar content will be helpful.
Thanks, Amit

**Comment by santhoshTpixler** [comment]
+1

**Comment by santhoshTpixler** [comment]
http://santhoshtpixler.github.io/report

Need some suggestions.

**Comment by authorjapps** [comment]
Yes, only failed ones will be useful.
> Failure log trail e.g. Request/Actual Response/Assertions(i.e. Expected Response)

This method is used to generate RAW json reports, see the usage in the MultiStepRunnerImpl
> org.jsmart.zerocode.core.domain.builders.ZeroCodeReportBuilder#printToFile

**Comment by santhoshTpixler** [comment]
The following changes have been made.
1. ExtentReports upgraded 3.1.3 --> 4.0.9
2. Failed step's request, response and assertion are shown in the HTML report.
3. ChartsAPI removed [Reference](http://extentreports.com/docs/versions/4/java/breaking-changes.html)
4. Author name removed from scenario name in HTML report.

Preview changes --> [Link](http://santhoshtpixler.github.io/zerocode-junit-interactive-fuzzy-search)

I am looking for a review on the HTML report in the above link.
@authorjapps  @dinesh76in @aghorpade

**Comment by authorjapps** [comment]
The fix is available in `v1.3.3`
