### ISSUE TITLE
Run same test case in parallel for no of times. (multi-threading support)

### ISSUE THREAD

**Issue by aghorpade** [authorjapps/zerocode#53]
I would like to run same test case for API testing in parallel. e.g. call GET api around 10 times in parallel and see response so I can check if any issue with my code in case of multi-threaded env.

**Comment by authorjapps** [comment]
Hi,
Thanks for the question. 
This framework leverages the power of `JUnit`. That means all the `advantages` and power of `JUnit `is **already** available to the you(as users). Also you have advantages of overriding the ZerocodeRunners for your own customization e.g. setting up mocks, doing specific tasks to put the `target system` in a `desirable state` etc.

**Parallel running is** easy and simple, you can run parallely-
1. Each test wise
1. Class wise

In **both** ways you have **choices** of running the test cases in parallel.

- Test wise-
```
<configuration>
    <parallel>methods</parallel>
    <threadCount>2</threadCount>
</configuration>
```
- Class wise
```
<configuration>
      <parallel>classes</parallel>
      <threadCount>2</threadCount>
</configuration>
```
**Suggestion**-
Please start with thread **count as 2**, then **increase to 3**, then 4, 5... 10 etc to make sure your system is **able to spawn** so many threads.

Usage-
Look for artefact id `<artifactId>maven-surefire-plugin</artifactId>` in your POM or module POM.
The configure it below way.
```
<plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>${surefire-version}</version>
        <configuration>
            <parallel>classes</parallel>
            <threadCount>2</threadCount>
        </configuration>
    </plugin>
```
Hope it helps!

If you short question and looking for quick answers, you can even put into the [gitter](https://gitter.im/zerocode-testing/help-and-usage) too.

_Zerocode is intuitive for users once you start using it!_

Regards

**Comment by authorjapps** [comment]
See also how to generate [load from your IDE](https://github.com/authorjapps/zerocode/wiki/Load-or-Performance-Testing-(IDE-based)).
e.g.
```java
@LoadWith("your_load_config.properties")
@TestMapping(testClass = AnyTestEndPoint.class, testMethod = "anyTestMethod")
@RunWith(ZeroCodeLoadRunner.class)
public class LoadTest {
}
```

**Comment by Nivetha2020** [comment]
How to pass different testdata when i run the test in parallel by classes
