### ISSUE TITLE
CI pipeline using Actions script

### ISSUE THREAD

**Issue by authorjapps** [authorjapps/zerocode#540]
Background:
Currently, TravisCI setup is not working due to service discontinuation. 
See: https://github.com/authorjapps/zerocode/blob/master/.travis.yml

AC1:
Implement the CI build using the GitHub Actions script. 
Refer to the above CI script to start/stop docker for Kafka e2e tests

AC2:
Make sure the branch build is triggered for PRs which will help to decide the PR can be merged.

Note:
This is delaying and almost blocking the PR review process.
Appreciate if anyone picks this and fixes it.

**Comment by Tineshnehete** [comment]
Hi, there . I think i can fix it. Can you please assign it to me :)

**Comment by nirmalchandra** [comment]
Thank you @Tineshnehete for picking this.
If you need any help related to Kafka tests or any other stuff e.g. maven etc, feel free to ping me, I can arrange a call with other collaborator who initially helped in creating the Travis pipeline.
Nevertheless please tag me in the PR even when partially ready, I should be able to take care after that.

**Comment by authorjapps** [comment]
Amazing work and thanks a lot 🙏 .
I will need some documentation help on this bit, will ping you when I get a chance.
