### ISSUE TITLE
Configure Travis build for for not to appear the as REQUIRED in the CI pipeline

### ISSUE THREAD

**Issue by authorjapps** [authorjapps/zerocode#548]
Background:
Travis is not fully killed/gone. Somewhere it's still referring even after the Actiosn build is successful.
<img width="749" alt="image" src="https://user-images.githubusercontent.com/12598420/199243556-4a5407d7-24c5-4e8c-a685-ebe77eb1296c.png">

See the "Required" tag in the screenshot. This needs to be removed. This should not even appear here. This is no more a required thing.

AC:
Please delete/renamed the associated Travis build files from the repo and check this "Required" tag is no more appearing.
or
Let me know in case I have to do any changes anywhere, happy to do it.

**Comment by nirmalchandra** [comment]
Fixed.
Removed the mandatory check for Travis-CI. ✅ 
Removed from WebHooks + Branch protection rules. ✅ 

EMoji Cheat Sheet help here:
https://github.com/ikatyang/emoji-cheat-sheet/blob/master/README.md#emoji-cheat-sheet
