### ISSUE TITLE
Global unique and random ID for a test suite e2e session

### ISSUE THREAD

**Issue by nirmalchandra** [authorjapps/zerocode#549]
Background:
As a SDET or dev I need a global unique as well as random ID which I can use per test session 
i.e. an ID which is available from start to end of a test session.

AC:
This should allow me to use anywhere 
e.g. inside a test scenario or in a config file if needed.

Suggestion:
>GLOBAL.RANDOM.ID

**Comment by nirmalchandra** [comment]
https://github.com/authorjapps/zerocode/pull/550

**Comment by authorjapps** [comment]
Fixed.
Available in 1.3.31 onwards
