### ISSUE TITLE
Java UUID sometimes referred as GUID(smart devices)

### ISSUE THREAD

**Issue by nirmalchandra** [authorjapps/zerocode#55]
Any generator for it?
e.g. `${random.uuid}` types ?
* Literally output of `java.util.UUID#randomUUID`
e.g. `123e4997-e99b-92d3-a456-996642441212`

[Zerocode UUID or Zerocode uuid random UUID]: https://github.com/authorjapps/zerocode/issues/55

**Comment by authorjapps** [comment]
Done,  v 33 has it.

**Comment by authorjapps** [comment]
README has been updated- [Link here ](https://github.com/authorjapps/zerocode#generating-random-strings-random-numbers-and-static-strings)
