### ISSUE TITLE
Cache consumer for same topic

### ISSUE THREAD

**Issue by nirmalchandra** [authorjapps/zerocode#551]
## Background:
Since recently I am facing an issue in my project when a newly created Consumer `CON_B` in the same consumer group `Group1` wants to poll from another topic `topic_gov_Y`, then it is unable to join the group due to failing to rebalance. 
I think I have figured out why this scenario causing the above issue. I will write up a small article on this and propose a possible solution on how to overcome this if anyone is facing similar problem.

Happy Case:
But note - It works fine and this issue doesn't appear to be an issue when the `CON_B` wants to join `Group1` to consume from the same topic `topic_gov_X` as of `CON_A`.
or
It is also not a problem if CON_B wants to join from a different group `Group2`

I will try to put the above as examples/sample for everyone to reproduce/run it at their machine when ready.

## Potential Fix/Implementation
Instead of creating new consumers everytime for same topic and closing it,  for same topic, cache the consumer(per topic) so that it can be reused for next pollings if any more tests in this run are asserting against the same topic.
When a new topic is to be polled, then create a new consumer, but make sure we close the earlier created consumer.
This way `CON_A` will issue a "LeaveGroup" request to the GC and allow the rebalance to happen, in turn allow CON_B to join the group. This is particularly a problem when we have just one partition and until CON_A not unassigns the partition, GC thinks CON_A is still processing the records and holding the partition.

Since we are using Kafka massively due to the Gov requirements, we need to do shift-left testing with thousands of messages during the test run to validate various business scenarios. I think caching consumers also might help here in terms of speed and resource efficiency.

## Existing Functionality:
Nothing has changed in the way the existing framework work, Just to reiterate==> it creates a consumer, polls the records, closes the consumer(which in turn issues a "LeaveGroup" request to the GC), then does the assertions.

## New Changes:
The changes are behind an optional config flag "consumer.cacheByTopic" in the Kafka env properties. The default value is "false" or you can totally skip it. Or you can totally ignore the above situation as it doesn't affect the existing behavior. Think that you haven't even read the above problem at all :-).

Happy and open for any advice and suggestions on this 🙏 

GC = Group Coordinator

**Comment by authorjapps** [comment]
TODO:
Add Documentation or WIki page
