### ISSUE TITLE
Sort message list or array for deterministic assertions

### ISSUE THREAD

**Issue by authorjapps** [authorjapps/zerocode#555]
Just checking, has anyone faced this and solved it(how)? 
Any pointers and suggestions are welcome and appreciated.

Summary:
When records are received from Kafka topics or any other Sources(e.g. APIs)  as a response, there is a possibility of getting the records in random order which makes it difficult to assert because of the array element positioning.

> only for array or collection response

Solution:
If we have a mechanism to sort it, then probably this will help us to assert deterministically.

AC:
Add or allow a sorting mechanism based on a key or ID.
> Later enhance it based on any field of the record in that collection

Choose:
- Natural order
- or
- Reverse order

**Comment by mevinson** [comment]
Hello, I see no progress has been made on this issue, may I be assigned to it?

**Comment by ampatzidhs** [comment]
I am interested for this issue, would you assign me ?

**Comment by authorjapps** [comment]
Apologies folks for late reply.
Just checking if @ogkunald is still available for this?
If so, requesting to put some outlines/pseducode about your approach to implement this please.
ETA: 20/January/2023 - is it possible by then?

We can review the approach together along with @mevinson , @ampatzidhs , and then you can proceed for the PR.

Just letting you know, the consumed messages which are un-ordered, are not in specific Java Object type.
i.e. why asking to review the approach you would be taking to sort these.

Thanks in advance!

**Comment by mevinson** [comment]
Hey, sorry for late reply, but thanks for assigning. I'm a university student and have classes on Tues/Thurs, so I should have time to start on this tomorrow, I'll try to update by this weekend.

**Comment by authorjapps** [comment]
> Hey, sorry for late reply, but thanks for assigning. I'm a university student and have classes on Tues/Thurs, so I should have time to start on this tomorrow, I'll try to update by this weekend.

Thank you for this. Please shout if you need any help while thinking through the solution etc.

**Comment by ihorsas** [comment]
Hey, @authorjapps I would be happy to help you with this issue. I've already made some progress however I am not sure if my implementation correctly fits these requirements. I'm currently adding a new field 'sort' and have doubts about where it should be located in json/yaml structure.
Here are the examples:
1st option:
```
{
    "scenarioName": "Assert array in the response ,
    "steps": [
        {
            "name": "check_array",
            "url": "some url",
            "method": "get",
            "request": "anything",
            "sort": {
                "key": "ID",
                "order": "NATURAL",
                "path": "$.body.ids"
            },
            "assertions": {
                "results":  {
                //validations
                }
            }
        }
    ]
}
```
2nd case:
{```

    "scenarioName": "Assert array in the response ,
    "steps": [
        {
            "name": "check_array",
            "url": "some url",
            "method": "get",
            "request": "anything",
            "assertions": {
                "sort": {
                    "key": "ID",
                    "order": "NATURAL",
                    "path": "$.body.ids"
                },
                "results":  {
                //validations
                }
            }
        }
    ]
}

```

I've implemented some code for 1st option, but haven't tested it yet. Please let me know which way is better in your opinion.

**Comment by ihorsas** [comment]
@authorjapps I have created a PR with my changes: https://github.com/authorjapps/zerocode/pull/559

**Comment by authorjapps** [comment]
> @authorjapps I have created a PR with my changes: #559

Amazing mate! 
will have a look soon

**Comment by authorjapps** [comment]
Also need to check the build failure on this PR:
https://github.com/authorjapps/zerocode/actions/runs/4276880543/jobs/7546963172

**Comment by ihorsas** [comment]
@authorjapps just pushed new kafka test as you have asked, tested it locally, please approve the build to be sure I did not break anything

**Comment by authorjapps** [comment]
> @authorjapps just pushed new kafka test as you have asked, tested it locally, please approve the build to be sure I did not break anything

yep, Final CI run is in-progress.
Once Green, will approve and merge

**Comment by authorjapps** [comment]
Thank you for all your hard work.

and the final pending bit is pending on the Wiki side. Would you mind adding a couple of examples here? 
Would be really helpful to everyone.

Link:
https://github.com/authorjapps/zerocode/wiki/Sort-records-consumed-from-Kafka-Topic-and-assert(also-sort-API-response)

(Please let me know if you don't have write permission)

**Comment by ihorsas** [comment]
Hey, I am glad to be useful. Looks like I don't have access to edit the wiki page that you have shared with me. Please provide me access and I will add the examples

**Comment by authorjapps** [comment]
> Hey, I am glad to be useful. Looks like I don't have access to edit the wiki page that you have shared with me. Please provide me access and I will add the examples

Hey, Added you as a collaborator now. You might have got an email or GitHub notification. 
If not you can click [here](https://github.com/authorjapps/zerocode/invitations) and join. Then you should have write permission.

**Comment by ihorsas** [comment]
> Hey, Added you as a collaborator now. You might have got an email or GitHub notification. If not you can click [here](https://github.com/authorjapps/zerocode/invitations) and join. Then you should have write permission.

Thanks. I have added a few basic examples with explanations for each field in the sorting step. I am grateful for the opportunity to help you with this feature. Wish you and your project all the best ^^

**Comment by authorjapps** [comment]
Now this has been released. ⏫ 

Thanks to all collaborators and participators. 

This is available in the following release onwards.
https://github.com/authorjapps/zerocode/releases/tag/zerocode-tdd-parent-1.3.33

```xml
<dependency>
  <groupId>org.jsmart</groupId>
  <artifactId>zerocode-tdd</artifactId>
  <version>1.3.33</version>
</dependency>
```
