### ISSUE TITLE
Zerocode unit runner does not work with adobe/S3Mock

### ISSUE THREAD

**Issue by kshitizsinghswiggy** [authorjapps/zerocode#558]
For content type(Adobe/S3mock)->  `application/vnd.openxmlformats-officedocument.spreadsheetml.sheet` , 
Zero code unit runner is not uploading .xlsx file in S3 mock.
Instead it creates a new file and add fileName in there. Attached screenshot.

Can someone please check this?

```
{
      "name": "put_item_master_data_in_s3",
      "url": "http://localhost:9090/masters-data-uploads/master/item/instamart/testItem.xlsx",
      "method": "PUT",
      "request": {
        "headers": {
          "Content-Type": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
        },
        "body": {
          "files": [
            "file:files/itemmaster/item_master_download.xlsx"
          ]
        }
      },
      "verify": {
        "status": 200
      }
    }
```

<img width="616" alt="Screenshot 2023-01-18 at 12 54 28 AM" src="https://user-images.githubusercontent.com/110160936/212993324-5aaf7657-2448-45c2-8e2a-cb264ca4b2aa.png">

**Comment by abhin-dynamify** [comment]
can i take this up?

**Comment by ashutoshak5386** [comment]
I think i have found the error

**Comment by ashutoshak5386** [comment]
> I think i have found the error

here's the new code:

{
  "name": "put_item_master_data_in_s3",
  "url": "http://localhost:9090/masters-data-uploads/master/item/instamart/testItem.xlsx",
  "method": "PUT",
  "request": {
    "headers": {
      "Content-Type": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    },
    "body": {
      "files": [
        "file:files/itemmaster/item_master_download.xlsx"
      ]
    }
  },
  "verify": {
    "status": 200
  }
}

**Comment by ashutoshak5386** [comment]
> I think i have found the error

here's the new code

`{
  "name": "put_item_master_data_in_s3",
  "url": "http://localhost:9090/masters-data-uploads/master/item/instamart/testItem.xlsx",
  "method": "PUT",
  "request": {
    "headers": {
      "Content-Type": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    },
    "body": {
      "files": [
        "file:files/itemmaster/item_master_download.xlsx"
      ]
    }
  },
  "verify": {
    "status": 200
  }
}
`

**Comment by authorjapps** [comment]
Already solved?
Can we close this?

Read Guidelines for raising an issue >> 
https://github.com/authorjapps/zerocode/wiki/Guidelines-for-raising-issues#guidelines
