### ISSUE TITLE
How to use form-data POST request

### ISSUE THREAD

**Issue by felipeEngineer2020** [authorjapps/zerocode#566]
Hi, I need to send a POST request using form-data, can you please advise if I can do this with zerocode and how to do it?
The endpoint consumes = {MediaType.APPLICATION_JSON_VALUE, MediaType.MULTIPART_FORM_DATA_VALUE})

Thank you.

Example from Postman.

![image](https://user-images.githubusercontent.com/73236422/230615184-90b34f39-7bb9-47fe-a0ac-2d890dee4f63.png)

**Comment by felipeEngineer2020** [comment]
Thanks @authorjapps . This is an example of what I need to submit in my request, the file is optional so first I'm trying without sending a file.

"request": {
        "headers": {
          "Content-Type": "multipart/form-data",
          "X-Auth-Token":"ggg"
        },
        "queryParams": {
          "userId": "ggg",
          "subject": "OTHER"
        },
        "body": {
          "RequestObject": {
            "userId": "gggg",
            "comment": "Test123",
            "findings": "OTHER"
          },
          "subscribeRequest":{
            "subscribed":true
          }
        }
      },

I get this exception:

java.lang.ClassCastException: java.util.LinkedHashMap cannot be cast to java.lang.String
        at org.jsmart.zerocode.core.httpclient.utils.FileUploadUtils.buildOtherRequestParams(FileUploadUtils.java:60) 


Caused by: java.lang.ClassCastException: java.util.LinkedHashMap cannot be cast to java.lang.String
        at org.jsmart.zerocode.core.httpclient.utils.FileUploadUtils.buildOtherRequestParams(FileUploadUtils.java:60)
        at org.jsmart.zerocode.core.httpclient.BasicHttpClient.createFileUploadRequestBuilder(BasicHttpClient.java:358)
        at org.jsmart.zerocode.core.httpclient.BasicHttpClient.createRequestBuilder(BasicHttpClient.java:402)
        at org.jsmart.zerocode.core.httpclient.BasicHttpClient.execute(BasicHttpClient.java:130)
        at org.jsmart.zerocode.core.engine.executor.httpapi.HttpApiExecutorImpl.execute(HttpApiExecutorImpl.java:62)
        at org.jsmart.zerocode.core.engine.executor.ApiServiceExecutorImpl.executeHttpApi(ApiServiceExecutorImpl.java:34)

**Comment by nirmalchandra** [comment]
hello @felipeEngineer2020 , can you share this sample test in a GitHub repo?
Will have a look when I get chance.

Have you seen this example in the Spring example repo?

- With file: (see "Without file:" in the next section)
```
                "body": {
                    "files": ["file:project_files/my_zip_file.zip", "file2:project_files/pdf_file.pdf"],
                    "trainList" : "Jubilee, Central, Bakerloo",
                    "id" : "LONDON-TUBE-UNDERGROUND"
                }

```

- Without file:
```

                    // Note-
                    // Also you can send key-value params to server like below

                "body": {
                    "keyTest" : "test.json",
                    "trainList" : "Jubilee, Central, Bakerloo",
                    "id" : "LONDON-TUBE-UNDERGROUND"
                }
```
That should work.

If the aboev doesn't work for you, you might have to override the "BasicHttpClient.java" to suit your requirement.
- org.jsmart.zerocode.core.httpclient.utils.FileUploadUtils#`buildOtherRequestParams`
- invoked from:
  - org.jsmart.zerocode.core.httpclient.BasicHttpClient#`createFileUploadRequestBuilder`

<img width="924" alt="image" src="https://user-images.githubusercontent.com/15079710/232340063-6c24ae9c-f24c-45ca-812e-e7fead3081b2.png">

**Comment by warademilind** [comment]
@authorjapps can we get this merged into release branch so that we can use it?

**Comment by nirmalchandra** [comment]
> @authorjapps can we get this merged into release branch so that we can use it?

This was merged years ago I think.
If not available(by chance), can you raise a PR and paste here?

We can reopen this ticket and get it merged.
