### ISSUE TITLE
Logs are Empty

### ISSUE THREAD

**Issue by nagkumar** [authorjapps/zerocode#574]
![image](https://github.com/authorjapps/zerocode/assets/332234/2ebbb3d4-1a5c-4b16-944b-bf98ee447ddf)

It better say it is testing with xyz param and also found no tests etc..

**Comment by nagkumar** [comment]
Can you pl. share how to configure log level so that if I increase log level, would it print more clues on why no tests are run

**Comment by authorjapps** [comment]
Please follow the HelloWorld example repo.
Clone and run the tests locally, you should be fine with logs etc there.
You can control the logs from logback XMl file. See the examples
