### ISSUE TITLE
[TECH-DEBT] Improve Log levels 

### ISSUE THREAD

**Issue by authorjapps** [authorjapps/zerocode#579]
# ISSUE:
- Most of the logs are in INFO level
- Some are in WARN and ERROR level
- Very less lines are in DEBUG level

There is no functional issues, but for reporting or debugging can be enhanced.

- - - 
# FIX:

AC1:
Level - INFO:
- [x] Write logs relevant to the request / response only

AC2:
Level - WARN:
- [x] Write logs relevant to the any information to be propagated to developers/testers which could be a blocker

AC3:
Level - ERROR:
- [x] Write logs relevant to the any exception scenarios, errors, program halt situations

- - - -

AC4:
Level - DEBUG:
- [x] Write logs relevant to the anything technical developer or tester, that will help in debug or analysing a problem. Verbose mode 

- - - -

AC5:
After the fix:
- [ ] Please paste/stick a run-log of a test scenario of a HTTP API automation test
  - [ ] Happy case
  - [ ] Negative scenario
- [ ] Please paste/stick a run-log of a test scenario of a Kafka test
  - [ ] Happy case
  - [ ] Negative scenario

**Comment by ShiviTripathi13** [comment]
can you assign this issue to me? i want to work on it.

**Comment by IshaJ721** [comment]
I can help with this.

**Comment by IshaJ721** [comment]
In 2 days or earlier. I thought it was not urgent.

**Comment by authorjapps** [comment]
> In 2 days or earlier. I thought it was not urgent.

Sounds good. Even a week's time is also fine imho. 👍 
Just for visibility purpose, it was needed as it helps other participants 😄

**Comment by IshaJ721** [comment]
pull request created #580

**Comment by IshaJ721** [comment]
Fixed the build issue and updated pull request

**Comment by idevkshitij** [comment]
Is this issue closed now?

**Comment by authorjapps** [comment]
@idevkshitij ,
Still there is a build failure in the latest [build(click)](https://github.com/authorjapps/zerocode/pull/580/checks).
The failure may not be due to the logging-fix, but it needs a fix.

**Comment by authorjapps** [comment]
PR https://github.com/authorjapps/zerocode/pull/580 has been merged.
This will be available in the next release automatically.
