### ISSUE TITLE
Duplicate dependency for protobuf-java in pom.xml

### ISSUE THREAD

**Issue by baulea** [authorjapps/zerocode#589]
The dependency
`<dependency>
    			<groupId>com.google.protobuf</groupId>
    			<artifactId>protobuf-java</artifactId>
    			<version>${google.protobuf.version}</version>
			</dependency>`
in the root pom.xml is duplicated. This causes a warning during maven build:

mvn clean install
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.jsmart:zerocode-tdd:jar:1.3.36-SNAPSHOT
[WARNING] 'dependencyManagement.dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: com.google.protobuf:protobuf-java:jar -> duplicate declaration of version ${google.protobuf.version} @ org.jsmart:zerocode-tdd-parent:1.3.36-SNAPSHOT, /home/al/eclipse-workspace-zerocode/zerocode/pom.xml, line 276, column 16
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]

**Comment by RachelwenxuanCao** [comment]
hi, I think I can work on this issue, can you please assign it to me? thank you!

**Comment by authorjapps** [comment]
> hi, I think I can work on this issue, can you please assign it to me? thank you!

done.

Thanks for picking this. 👍 

Can you please raise the PR and paste the PR link here when ready?

**Comment by baulea** [comment]
I already sent the PR yesterday shortly after creating this issue: https://github.com/authorjapps/zerocode/pull/590
Is there anything missing? I'm a newbie in open source workflows.

**Comment by RachelwenxuanCao** [comment]
> I already sent the PR yesterday shortly after creating this issue: #590
> Is there anything missing? I'm a newbie in open source workflows.

hi! I was working on this issue as well and I checked your code. We basically did the same thing and remove one duplicated dependency.
