### ISSUE TITLE
File upload : How to do it using Zerocode

### ISSUE THREAD

**Issue by warademilind** [authorjapps/zerocode#591]
I am using zerocode0tdd version 1.3.26. Needs to upload two files while automating it. 
Below is Postman script which is working -

POSTMAN:
```
POST request.
URL: https://localhost:8021/core-test/materialVersionAsset/content
Beaer token - Jub25jZSIMDF9KIQ
Uploaded two files (added two files in form-data)
```

CURL:
```
curl --location 'https://localhost:8021/core-test/materialVersionAsset/content' \
--header 'Authorization: Bearer Jub25jZSIMDF9KIQ' \
--form 'fileContent=@"/C:/Users/milindw/Downloads/LatestL55.i2s"' \
--form 'metadata=@"/C:/Users/milindw/Downloads/L55.json"'
```

Can you let me know how to write zerocode script. I have tried to write code in this way:
- - - - -
```
{
	"scenarioName": "Multiple File Upload Test",
	"steps": [
		{
			"name": "Upload Files",
			"url": "/materialVersionAsset/content",
			"operation": "POST",
			"request": {
				"headers": {
					"Authorization": "Bearer Jub25jZSIMDF9KIQ",
					"Content-Type": "multipart/form-data"
				},
				"body": {
					"files": [
						"metadata:D:/Users/milindw/Downloads/L55.json",
						"fileContent:D:/Users/milindw/Downloads/LatestL55.i2s"
					]					

				}
			},
			"assertions": {
				"status": 200,
				"body": {
					"message": "$CONTAINS.STRING:File uploaded successfully !"
				}
			}
		}
	]
}
```

- - - -

but its not working, can somebody suggest solution for the same.

**Comment by warademilind** [comment]
@authorjapps please help

**Comment by authorjapps** [comment]
Hello @warademilind, hope you are well. 
The documentation site is more searchable now and can get you a precise result.

https://next.zerocode-tdd-docs.pages.dev/  <--- Search here.
_(Note: Site is currently draft and pre-live mode... aiming to go live in next couple of weeks)_

Give it a try!

**Comment by warademilind** [comment]
@authorjapps will try the above mentioned link. Will let you know. 
Thanks

**Comment by wojdeb** [comment]
Hi, 
I've created a helloworld example for uploading files via API. Please approve this PR if you find it helpful.

**Comment by warademilind** [comment]
I will check this one. Thanks

**Comment by authorjapps** [comment]
Example as well as logs attached to the PR.

Closing this ticket soon as soon as the [doc page](https://github.com/authorjapps/zerocode/pull/600#issuecomment-1789087120) is ready with the new PR example content.
