### ISSUE TITLE
[Doc] Site Documentation content fixing

### ISSUE THREAD

**Issue by authorjapps** [authorjapps/zerocode#593]
# AC1:
Remove the "Table Of Content" section from all documentation MD files.

_Nextra framework automatically puts a TOC on the right side bar anyways_

Repo:
https://github.com/authorjapps/zerocode-tdd-docs

# AC2:
Remove the "====" from all the titles and replace it with "#"

Same Repo:
https://github.com/authorjapps/zerocode-tdd-docs

e.g.
```
Introduction
===


replace it with 

# Introduction

```

# AC3:
- Apply "#" to the first or top title
- Apply "##" to subsequent titles in that page
- Apply "###" to any subtitles(if needed) under "##" 

# How to Fix?
Steps mentioned here:
https://github.com/authorjapps/zerocode/wiki/Documentation-How-To-Fix-Steps

- - - -

Related Tickets:
- https://github.com/authorjapps/zerocode/issues/569
- https://github.com/authorjapps/zerocode/issues/420

**Comment by authorjapps** [comment]
> I am working on this issue right now. If it is possible, please assign it to me!

Hello @u7480181 , Thanks for this.
I am adding some more details which will help in navigating through the folders and MD files to fix them.

Please ask for help or information when you need.

**Comment by u7480181** [comment]
Will be completed within the next one or two days

**Comment by u7480181** [comment]
I have created a second pull request in that repo for a few more folders. Please review and let me know

**Comment by authorjapps** [comment]
> I have created a second pull request in that repo for a few more folders. Please review and let me know

Thank You. Really appreciate your contributions.

If you have covered everything, we can close this ticket.

Happy to wait and keep this opened if you're preparing more PRs.

Let us know either way.

Have a great weekend!

**Comment by u7480181** [comment]
I will finish the rest of the folders now and create one more PR.

**Comment by u7480181** [comment]
I have created the final PR for this issue in the repo. https://github.com/authorjapps/zerocode-tdd-docs/pull/5

**Comment by u7480181** [comment]
Is there an issue I could work on that includes maybe writing some documentation? For example, I saw in the file "Mocking-end-points-via-WireMock(Simple-and-flexible).md" within the assertions folder that there is a TODO tag requiring the completion of a few tasks. Can you help me with doing that or give me a similar task?

**Comment by authorjapps** [comment]
> Is there an issue I could work on that includes maybe writing some documentation? For example, I saw in the file "Mocking-end-points-via-WireMock(Simple-and-flexible).md" within the assertions folder that there is a TODO tag requiring the completion of a few tasks. Can you help me with doing that or give me a similar task?

No problems at all if you are happy to pick other issues and work on it 👍 

But please raise new ticket(s) and list down the things which you have identified as gaps, then you can work on it and raise PRs.
Yes, it can have new content, TODO contents and contents those need fix.

Please follow this while fixing:
https://github.com/authorjapps/zerocode/wiki/Documentation-How-To-Fix-Steps

**Comment by u7480181** [comment]
Can I create a new issue describing what I will add to the file?
