### ISSUE TITLE
warnings during maven build regarding missing version for maven-compiler-plugin

### ISSUE THREAD

**Issue by baulea** [authorjapps/zerocode#596]
The following warnings show up during a maven build

[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.jsmart:http-testing:jar:1.3.36-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ line 50, column 21
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.jsmart:kafka-testing:jar:1.3.36-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ line 56, column 12
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.jsmart:zerocode-tdd-jupiter:jar:1.3.36-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ line 145, column 21
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]

**Comment by baulea** [comment]
You can assign this to me for a fix.

**Comment by baulea** [comment]
I would suggest to create a <pluginManagement> section in the parent pom and remove redundant configuration for the maven-compiler-plugin in the child poms

**Comment by nirmalchandra** [comment]
> You can assign this to me for a fix.

Assigned now. Thanks for trying to fix these.

When you're ready, please raise a PR and link to this issue.

**Comment by baulea** [comment]
I have create the pull request https://github.com/authorjapps/zerocode/pull/597
In the parent pom I introduced a <pluginManagement> section with configuration for maven-compiler-plugin.

If you agree I would also move the configuration for the other maven-plugins into this <pluginManagement> section and update their versions to the most current ones. If these changes are in your sense, please tell me, if I should add these changes to the current pull request or if I should create a new issue and a separate pull request.

**Comment by baulea** [comment]
Hello @nirmalchandra, is the pull request https://github.com/authorjapps/zerocode/pull/597 acceptable for you? 

If you agree I would also move the configuration for the other maven-plugins into this pluginManagement section and update their versions to the most current ones. If these changes are in your sense, please tell me, if I should add these changes to the current pull request or if I should create a new issue and a separate pull request.

**Comment by baulea** [comment]
Will be done with issue #607 and PR #609
