### ISSUE TITLE
How to disable console output of any required step ?

### ISSUE THREAD

**Issue by sudhindra95** [authorjapps/zerocode#603]
Hello community,

I have a sample scenario file:
```

{
  "scenarioName": "Disable Console Output Demo",
  "steps": [
    {
      "name": "Step with Console Output",
      "url": "/api/resource",
      "method": "GET",
      "request": {
        "headers": {
          "Authorization": "Bearer your_token"
        }
      },
      "assertions": {
        "status": 200
      }
    },
    {
      "name": "Step without Console Output",
      "url": "/api/other_resource",
      "method": "POST",
      "request": {
        "data": {
          "key": "value"
        }
      },
      "assertions": {
        "status": 201
      },
      "print": false  // Set the "print" attribute to false to disable console output
    }
  ]
}
```

I would like to hide the output from displaying on the console. How can I achieve this?

- - - - -

# AC1:
Things such as Credentials(e.g. passwords,passcodes, secrets), authentication tokens for REST APIs and various other credentials to connect to services such as secret etc should not be printed to both console and logs.

## Implementation:
- Mask these fields in the output e.g. `"***masked***"`. Then displaying/printing to the console/log is fine.
- Provide mechanism which allows a field to be displayed as masked in the output

e.g.
```
Usual way:
"Authorization": "Basic ${$.get_credentials.response.authentication_token}"
Masked way:
"Authorization": "Basic $MASKED:${$.get_credentials.response.authentication_token}"

Output:
"Authorization": "Basic ***masked***"
```

e.g.
```
"Authorization": "Basic ${$.get_credentials.response.authentication_token}"
"Authorization": "$MASKED:Basic ${$.get_credentials.response.authentication_token}"

Output:
"Authorization": "***masked***"
```

e.g.
```
"secrets": "${SYSTEM.PROPERTY:secrets}"
"secrets": "$MASKED:${SYSTEM.PROPERTY:secrets}"

Output:
"secrets": "***masked***"
```

e.g.
```
"secrets": "secret123"
"secrets": "$MASKED:secret123"

Output:
"secrets": "***masked***"
```

- - - - - 

# AC2:
So the output of the first step should be hidden in the console(and log files), but the response should still be accessed by the successive steps
e.g.
to authenticate again the test-stpe needs these tokens in situations like SSO and non-SSO infra.

- - - -

# IMPLEMENTATION GUIDANCE
Follow the `$CONTAINS.STRING:` implementation for implementing `$MASKED:`

**Comment by authorjapps** [comment]
@sudhindra95 , can you please fill the "TODO - 1) " and "TODO - 2) " sections above when you get chance?

**Comment by sudhindra95** [comment]
@authorjapps 
1. I am storing credentials related to Cassandra, authentication tokens for REST APIs and various other credentials to connect to services in a secret.properties file which will be sent through command line as -Dsecrets=/path/to/secrets/file and the values stored in it will be output in Zerocode which will be used by some other step while connecting to services/databases.
For example:
`
{
  "scenarioName": "My sample scenario",
  "steps": [
    {
      "name": "get_credentials",
      "url": "com.demo.GetCredentials",
      "method": "fetchSecrets",
      "request": {
        "secrets": "${SYSTEM.PROPERTY:secrets}"
      },
      "assertions":{
        "result": "$NOT.NULL"
      }
    },
   {
      "name": "get_solr_data",
      "url": "${$.get_credentials.response.solr_url}/query",
      "method": "GET",
      "request": {
        "headers": {
          "Authorization": "Basic ${$.get_credentials.response.authentication_token}"
        },
        "queryParams":{
          "q": "*:*",
          "q.op": "OR",
          "fq": "user_id:123"
        }
      },
      "assertions": {
        "status": 200,
        "body": {
          "response.docs[0].user_id": "123"
        }
      }
    }
  ]
} 
 `
In this first step, the credentials read from the secrets file will be displayed in the Zerocode console (current feature which needs to be hidden). 
The credentials read from the previous(authentication token) will be used to connect to REST API (Solr in my case).

2. As the credentials are secrets of a team/org, they should not be displayed in the console which can be seen by others and accessed. So the output of the first step should be hidden in the console but the response should still be accessed by the successive steps.

**Comment by nirmalchandra** [comment]
Hello, I have now updated the ACs. Please have a look and then, can you please confirm if you're happy and it will solve your problem?

**Comment by sudhindra95** [comment]
Hi @nirmalchandra ,While the implementation of accessing secrets via `$MASKED` appears promising, there is uncertainty regarding how to effectively display the masked value when outputting it. 
Specifically, in https://github.com/authorjapps/zerocode/issues/603#issuecomment-1848848872, the get_credentials step retrieves data from the secrets file passed through command line parameters (-Dsecrets) and displays it on the console for the 'get_solr_data' step to access the authentication token. The challenge lies in masking this outputted data to ensure secure handling for subsequent steps, allowing access using `$MASKED:Basic ${$.get_credentials.response.authentication_token}`

**Comment by nirmalchandra** [comment]
> Hi @nirmalchandra ,While the implementation of accessing secrets via `$MASKED` appears promising, there is uncertainty regarding how to effectively display the masked value when outputting it. Specifically, in [#603 (comment)](https://github.com/authorjapps/zerocode/issues/603#issuecomment-1848848872), the get_credentials step retrieves data from the secrets file passed through command line parameters (-Dsecrets) and displays it on the console for the 'get_solr_data' step to access the authentication token. The challenge lies in masking this outputted data to ensure secure handling for subsequent steps, allowing access using `$MASKED:Basic ${$.get_credentials.response.authentication_token}`

Got you. You're right in thinking the next usage of the secret field in subsequent steps.

Then, in the following situation:
_>> to ensure secure handling for subsequent steps_ 

"$MASKED:" should be used again imo, otherwise the logger will print the content in plaintext.

I think the framework should provide the **masking** as well as **plaintext** ability of any field(secret fields in this case). 
It's the developer/tester, who should use it as per their requirements.

- - - - 

Also there is another suggestion to solve this:

Solution-2
===

1. When a field is marked as`$MASKED`, then print the content as "***masked***" from then onwards including where it is referenced in the subsequent steps.

But this might be challenging to implement it in terms of identifying whether that field was marked as "MASKED" earlier.

Hence, until the **Solution-2** is analysed thoroughly, it'll be better to implement the basic "$MASKED" solution which might at least unblock you. 
Only caveat here is you need to use this "$MASKED" in every steps where this "secret" is reused/referenced.

Let me know your thoughts anyways if you see any other problems or sideeffects.

**Comment by sudhindra95** [comment]
Please let me know when this feature will be released

**Comment by anishlukk123** [comment]
@sudhindra95  anyone working on this

**Comment by authorjapps** [comment]
> @sudhindra95 anyone working on this

@sudhindra95,
As the requirements looking fine now,
Someone needs to work on this, as it's open for collaboration!

**Comment by DohaRamadan** [comment]
Hello, This is my first time contributing to this project, is this a good issue to start with?

**Comment by nirmalchandra** [comment]
> Hello, This is my first time contributing to this project, is this a good issue to start with?

@DohaRamadan. Thanks for your interest.
This particular one may be a slight tidious one to start with. 
But you can still help us in adding few unit tests and few integration tests to cover the feature and make sure there are no CI failures after that(or fix it if there may any).

If you're ok, I will try to push the initial framework code by next week(work in progress ⚠️ and still trying to figure out the solution).

Is this fine with you?

**Comment by DohaRamadan** [comment]
> > Hello, This is my first time contributing to this project, is this a good issue to start with?
> 
> @DohaRamadan. Thanks for your interest. This particular one may be a slight tidious one to start with. But you can still help us in adding few unit tests and few integration tests to cover the feature and make sure there are no CI failures after that(or fix it if there may any).
> 
> If you're ok, I will try to push the initial framework code by next week(work in progress ⚠️ and still trying to figure out the solution).
> 
> Is this fine with you?

Yeah sounds great!
Can you suggest an issue that would be good for first-time-contributors?

**Comment by nirmalchandra** [comment]
> > > Hello, This is my first time contributing to this project, is this a good issue to start with?
> > 
> > 
> > @DohaRamadan. Thanks for your interest. This particular one may be a slight tidious one to start with. But you can still help us in adding few unit tests and few integration tests to cover the feature and make sure there are no CI failures after that(or fix it if there may any).
> > If you're ok, I will try to push the initial framework code by next week(work in progress ⚠️ and still trying to figure out the solution).
> > Is this fine with you?
> 
> Yeah sounds great! Can you suggest an issue that would be good for first-time-contributors?

Ok. You can now use this PR : https://github.com/authorjapps/zerocode/pull/618

**Comment by nirmalchandra** [comment]
Fixed.

The following are sample test scenarios and their run logs.
These can be used for Documentation purpose.

```js
{
    "scenarioName": "Masked Secret path as step param - Reusable Secret or Bearer token",
    "steps": [
        {
            "name": "get_balance_via_secret_token",
            "url": "/home/accounts/123/balance",
            "operation": "GET",
            "request": {
                "headers": {
                    "Authorization": "Bearer ${MASKED:token1002003004}",
                    "request-bank-name": "${MASKED:HSBC}",
                    "secretCode": "${MASKED:Amazing}"
                }

            },
            "assertions": {
                "status": 200,
                "body" : {
                    "balance" : 3900,
                    "name" : "${$.get_balance_via_secret_token.request.headers.request-bank-name}",
                    "current" : true
                }
            }
        },
        {
            "name": "find_match",
            "url": "/api/v1/search/persons",
            "method": "GET",
            "request": {
                "queryParams": {
                    "lang": "${$.get_balance_via_secret_token.request.headers.secretCode}",
                    "city": "${MASKED:Lon}"
                }
            },
            "verify": {
                "status": 200,
                "body": {
                    "exactMatches": true,
                    "name": "Mr Bean",
                    "lang": "${$.get_balance_via_secret_token.request.headers.secretCode}",
                    "city": "${$.find_match.request.queryParams.city}"
                }
            }
        }

    ]
}

```

Run log or Console logs:
```js
-----------------------------------------------------------------------------------

Scenario:
+++++++++

Masked Secret path as step param - Reusable Secret or Bearer token 
-----------------------------------------------------------------------------------

--------- TEST-STEP-CORRELATION-ID: 204cadc1-5d2a-435f-b67d-935f2392b1e2 ---------
*requestTimeStamp:2024-02-07T20:32:49.296
step:get_balance_via_secret_token
id:None
url:http://localhost:9998/home/accounts/123/balance
method:GET
request:
{
  "headers" : {
    "Authorization" : "Bearer ***masked***",
    "request-bank-name" : "***masked***",
    "secretCode" : "***masked***"
  }
} 
--------- TEST-STEP-CORRELATION-ID: 204cadc1-5d2a-435f-b67d-935f2392b1e2 ---------
Response:
{
  "status" : 200,
  "headers" : {
    "Date" : [ "Wed, 07 Feb 2024 20:32:49 GMT" ],
    "Last-Modified" : [ "Wed, 07 Feb 2024 20:32:49 GMT" ],
    "Transfer-Encoding" : [ "chunked" ],
    "Content-Type" : [ "application/json" ],
    "Connection" : [ "keep-alive" ]
  },
  "body" : {
    "balance" : 3900,
    "name" : "HSBC",
    "current" : true
  }
}
*responseTimeStamp:2024-02-07T20:32:49.302 
*Response delay:6.0 milli-secs 
---------> Expected Response: <----------
{
  "status" : 200,
  "body" : {
    "balance" : 3900,
    "name" : "***masked***",
    "current" : true
  }
} 
 
-done-


--------- TEST-STEP-CORRELATION-ID: 2e04e240-abcb-44c4-86da-d9155d5a71c6 ---------
*requestTimeStamp:2024-02-07T20:32:49.304
step:find_match
id:None
url:http://localhost:9998/api/v1/search/persons
method:GET
request:
{
  "queryParams" : {
    "lang" : "***masked***",
    "city" : "***masked***"
  }
} 
--------- TEST-STEP-CORRELATION-ID: 2e04e240-abcb-44c4-86da-d9155d5a71c6 ---------
Response:
{
  "status" : 200,
  "headers" : {
    "Date" : [ "Wed, 07 Feb 2024 20:32:49 GMT" ],
    "Last-Modified" : [ "Wed, 07 Feb 2024 20:32:49 GMT" ],
    "Transfer-Encoding" : [ "chunked" ],
    "Content-Type" : [ "application/json" ],
    "Connection" : [ "keep-alive" ]
  },
  "body" : {
    "exactMatches" : true,
    "name" : "Mr Bean",
    "lang" : "Amazing",
    "city" : "Lon"
  }
}
*responseTimeStamp:2024-02-07T20:32:49.308 
*Response delay:4.0 milli-secs 
---------> Expected Response: <----------
{
  "status" : 200,
  "body" : {
    "exactMatches" : true,
    "name" : "Mr Bean",
    "lang" : "***masked***",
    "city" : "***masked***"
  }
} 
 
-done-


```

**Comment by authorjapps** [comment]
Pending:
- Update the Documentation(docs) with how to use this feature
- To update docs, here are the [collaboration guidelines(easy steps)](https://github.com/authorjapps/zerocode/tree/master?tab=readme-ov-file#documentation)

**Comment by nirmalchandra** [comment]
> Available in `1.3.36` and higher versions when released.
> 
> Pending:
> 
>     * Update the Documentation(docs) with how to use this feature
> 
>     * To update docs, here are the [collaboration guidelines(easy steps)](https://github.com/authorjapps/zerocode/tree/master?tab=readme-ov-file#documentation)

Basic Doc added.
https://github.com/authorjapps/zerocode-tdd-docs/pulls

**Comment by authorjapps** [comment]
Doc link in here:
https://zerocode-tdd-docs.pages.dev/ 
--> Look for "MASK" or "secret"

**Comment by sudhindra95** [comment]
Thank you. I hope the secrets will be read by the step when passed as "${MASKED:${SYSTEM.PROPERTY:secrets}}", where secrets refers to data passed in command line arguments as -Dsecrets=<secrets/tokens>

**Comment by authorjapps** [comment]
> Thank you @authorjapps . I hope the secrets will be read by the step when passed as "${MASKED:${SYSTEM.PROPERTY:secrets}}", where secrets refers to data passed in command line arguments as -Dsecrets=<secrets/tokens>

@sudhindra95 , understood.
Best way to check is to add a scenario with your above use case and test.

How?
Ans: Fork from current 'master' and run your scenario locally at your laptop or desktop.

And/Or
Share the runnable scenario here, I can try to execute and check.

Hope it helps.
