### ISSUE TITLE
Request for Compatibility with Other Programming Languages or CLI Version

### ISSUE THREAD

**Issue by Tineshnehete** [authorjapps/zerocode#611]
Hi community , i found zerocode really interesting and useful . But the obstacle is its in java ( i don't have java background ) or I dont fount way to use it as cli tool or integrating it with   other programming language .  I believe that expanding compatibility with other programming languages or introducing a command-line interface (CLI) version would greatly enhance its usability and adoption in diverse environments.

Can anyone help in the case ?

**Comment by authorjapps** [comment]
> Hi community , i found zerocode really interesting and useful . But the obstacle is its in java ( i don't have java background ) or I dont fount way to use it as cli tool or integrating it with other programming language . I believe that expanding compatibility with other programming languages or introducing a command-line interface (CLI) version would greatly enhance its usability and adoption in diverse environments.
> 
> Can anyone help in the case ?

Hello @Tineshnehete , agree with you on the CLI usage.
Actually one can use Maven(mvn CLI) for time being via a shell wrapper, but not sure about non-java folks, whether they are used to maven(mvn).

If you get chance, please explore any possible options. 🍏 

Some Ideas Below Here:
- Create a FAT Jar and wrap it with Shell options
- Use maven for Shell wrapping
- Or implement CLI options(e.g. Java Command line pasrsers)

Happy to get input/feedback from all.
