### ISSUE TITLE
Static java method invocation in step

### ISSUE THREAD

**Issue by a1shadows** [authorjapps/zerocode#622]
Right not it looks like it is only possible to invoke instance methods from objects as part of a step. Is it also possible to invoke static methods like `System#currentTimeMillis`? 

If not, I can look into adding this as a feature

**Comment by a1shadows** [comment]
@authorjapps  what are your thoughts

**Comment by authorjapps** [comment]
> Right not it looks like it is only possible to invoke instance methods from objects as part of a step. Is it also possible to invoke static methods like `System#currentTimeMillis`? 
> 
> If not, I can look into adding this as a feature

Hello mate @a1shadows ,
It should straight away work even now as uses Reflection.
But Happy for you to look at and fix it via a PR if this doesn't work.
My suggestion would be to pick this after the Retry comment you raised has been fixed please.
Many Thanks

**Comment by a1shadows** [comment]
@authorjapps  Going by the code in `JavaMethodExecutorImpl`, the code always fetches an instance from the injector before calling a method. I don't think this will work for static methods

**Comment by authorjapps** [comment]
> Got you @a1shadows , let's get this fixed. I remember in some instances it worked in the past, but may be we wrapped it by a Class n nonstatic method. Let's make it better from usability point. Better to fix. Would advise a separate PR for this.
> 
> Thanks once again for your diligence in looking into it.

@a1shadows,  I think you can pick this 1st(when you are ready) because the other issue/feature in still under discussion.

**Comment by a1shadows** [comment]
@authorjapps  Sure, I'll start looking into this

**Comment by authorjapps** [comment]
This feature is available in v `1.0.36` and higher when released.

PENDING:
- [ ] Documentation for this feature
