### ISSUE TITLE
Support for multiple parameters in the Java method invocation Step

### ISSUE THREAD

**Issue by a1shadows** [authorjapps/zerocode#626]
@authorjapps 
It looks like currently we can support only 1 or 0 argument methods for invocation through steps. I can look into this to support a variable number of arguments

**Comment by a1shadows** [comment]
@authorjapps  Can you please assign the issues I raised to me? I'll look into them one by one

**Comment by authorjapps** [comment]
> @authorjapps Can you please assign the issues I raised to me? I'll look into them one by one

Happy to assign @a1shadows .

Just checking what would be usecases for more than 1 params ?

Currently, if you pass an object to the function, it can accommodate 0 or 1 or more parameters as input to the function imo, which addresses most of the usecases.

**Comment by a1shadows** [comment]
@authorjapps  I think that would be true for any method written specifically for use in Zerocode. However, for already existing methods, this necessitates creating wrapper methods and DTO classes for methods that could have been directly called without writing extra code

**Comment by authorjapps** [comment]
Got you @a1shadows, lets go for it if it makes testing process and dev/test life further easy.

Please make sure backward compatibility is maintained, as existing projects should not break. Of course you might know this already, just a note due to we all forget during the dev :-)

**Comment by authorjapps** [comment]
Closed by PR #628

**Comment by authorjapps** [comment]
This feature is available in v `1.0.36` and higher when released.

PENDING:
- [ ] Documentation for this feature
