### ISSUE TITLE
[TECH-DEBT] Move to jackson json provider in JsonPath instead of jsonsmart

### ISSUE THREAD

**Issue by a1shadows** [authorjapps/zerocode#648]
We can have uniformity across the repo if we do this and can avoid pulling in the json-smart dependency

was raised during #647

**Comment by baulea** [comment]
@a1shadows You may assign this issue to me. I'll have a closer look at json array handling :-)

**Comment by baulea** [comment]
@a1shadows Do you know the reason, why Gson is used in the Kafka part? Couldn't that also be changed to Jackson?

**Comment by a1shadows** [comment]
> shadows Do you know the reason, why Gson is used in the Kafka part? Couldn't that also be changed to Jackson?

Hey @authorjapps  any idea on this?

**Comment by authorjapps** [comment]
> Gson is used in the Kafka part? 

@a1shadows, I vaguely remember, a collaborator introduced for a quick fix.
Yes, Jackson can be used instead of Gson 👍 .

Worth checking anywhere else Gson is not used before completely getting rid of it.
