### ISSUE TITLE
recordType does not take into account differences between key and value for kafka

### ISSUE THREAD

**Issue by a1shadows** [authorjapps/zerocode#654]
When we supply recordType for kafka producer or consumer step or RAW/JSON, it assumes that both key and value will be both either RAW or JSON.

In reality, there are many scenarios where the key is an integer/string but the value is JSON.

**Comment by a1shadows** [comment]
@authorjapps what are your thoughts?

**Comment by authorjapps** [comment]
> @authorjapps what are your thoughts?

@a1shadows , is it possible to provide an example with a usecase please?

A scenario with steps will be useful.

**Comment by a1shadows** [comment]
I think #657  is an example of this
