### ISSUE TITLE
Flaky tests detected: ConsumerJsonRecordTest.should_serialize_a_record_with_headers

### ISSUE THREAD

**Issue by hermya** [authorjapps/zerocode#685]
The Problem:
----------
There are some flaky-tests in the repo, which assert the output of non-deterministic outputs. They may pass in specific environment but possible fail in others. By using [nondex](https://github.com/TestingResearchIllinois/NonDex), one can find such cases. 

For example: **ConsumerJsonRecordTest.should_serialize_a_record_with_headers** fails intermittently
```
Expected: "{\"key\":123,\"value\":\"val\",\"headers\":{\"hKey\":\"hValue\",\"hKeyWithNullValue\":null}}"
     but: was "{\"key\":123,\"value\":\"val\",\"headers\":{\"hKeyWithNullValue\":null,\"hKey\":\"hValue\"}}"
```
*Notice the string mismatch due to change in ordering of keys*: `{hKey, hKeyWithNullValue}` <=> `{hKeyWithNullValue, hKey}`

About The Fix:
----------
Answered [here](https://github.com/authorjapps/zerocode/pull/684#issuecomment-2395588675).

**Comment by nirmalchandra** [comment]
PR merge. Changes were only to Test classes, so no impact to the release versions.
