### ISSUE TITLE
[HTML-REPORT][BUG]Interactive report missing the Light and Dark mode switch

### ISSUE THREAD

**Issue by authorjapps** [authorjapps/zerocode#694]
The earlier version of generate HTML report was having a "toggle" feature for Light/Dark mode towards the bottom left corner.
However, this feature is missing in the latest version.

This change could be due to a recent update in the Extent library, or possibly an unintentional code change that disabled it—though the library update seems more likely. It's also possible that the Extent library now requires a specific flag to enable this feature.

AC1:
Investigate the root cause of this bug and comment in this ticket

AC2;
Fix and raise a PR

--------------

*********Screenshots*********
- of report ran with an older version "1.3.20" :

**Light mode:**

<img width="1717" alt="Pasted Graphic 17" src="https://github.com/user-attachments/assets/002fa440-cee1-459d-bf4b-454e6c5585b3">

---------------

**Dark mode:**

<img width="1720" alt="Pasted Graphic 18" src="https://github.com/user-attachments/assets/2f347a8f-661d-487f-82a5-b9cade6edf46">

**Comment by authorjapps** [comment]
> I would like to join this issue

Hello @maya5768 , just checking what you mean by "join the issue" ?
Do you mean, are you planning to fix the issue?

**Comment by maya5768** [comment]
I will try , but I need  more information. 
1. can we get the UI screenshot the the toggling feature are shown?
2. can we get a refrence to the code of this bug? 
3. can we get the UI screenshot of the expacted valid result?

**Comment by authorjapps** [comment]
> I will try , but I need more information.
> 
> 1. can we get the UI screenshot the the toggling feature are shown?
> 2. can we get a refrence to the code of this bug?
> 3. can we get the UI screenshot of the expacted valid result?

Thanks for clarifying.

> 1. can we get the UI screenshot the the toggling feature are shown?

Just run a test with an earlier version, Example: 1.3.20(more or less), you should be able to figure out the Light/Dark mode on the HTML report.

> 2. can we get a refrence to the code of this bug?

Check the Report related code [here](https://github.com/authorjapps/zerocode/tree/master/core/src/main/java/org/jsmart/zerocode/core/report). You should find in general how it is building up the reports.
More on how to build the project, refer to this [ BUILDING.md ](https://github.com/authorjapps/zerocode/blob/master/BUILDING.md)

> 3. can we get the UI screenshot of the expacted valid result?

Same as 1.

**Comment by authorjapps** [comment]
> I will try , but I need more information.
> 
> 1. can we get the UI screenshot the the toggling feature are shown?
> 2. can we get a refrence to the code of this bug?
> 3. can we get the UI screenshot of the expacted valid result?

@maya5768 
Can you reply here as Yes , that you're not looking at this ticket and it's free for another collaborator to pick?

- [ ] Yes (tick this)

**Comment by bppdanto-t** [comment]
Hi @authorjapps,
I've looked into the issue and I want to share my findings:

1. The toggle icon has been removed completely in ExtentReport's new versions and it seems there's no way to add it with specific flags
2. From https://github.com/extent-framework/extentreports-java/wiki/ExtentSparkReporter#misc, It supports theme toggle using keyboard press, using "L" key
3. It's possible to add it manually by adding JS and CSS code to the ExtentSparkReporter's config

I've successfully added the toggle icon back and tested it locally. I can create the pull request for the fix if it's allowed
![image](https://github.com/user-attachments/assets/030d305e-9474-43e0-b7fe-48d82ef93ca6)
![image](https://github.com/user-attachments/assets/5b4d21ce-8ea8-4ad2-bc77-466bc4130342)

Kindly advice, thanks!

**Comment by authorjapps** [comment]
> Hi @authorjapps, I've looked into the issue and I want to share my findings:
> 
> 1. The toggle icon has been removed completely in ExtentReport's new versions and it seems there's no way to add it with specific flags
> 2. From https://github.com/extent-framework/extentreports-java/wiki/ExtentSparkReporter#misc, It supports theme toggle using keyboard press, using "L" key
> 3. It's possible to add it manually by adding JS and CSS code to the ExtentSparkReporter's config
> 
> I've successfully added the toggle icon back and tested it locally. I can create the pull request for the fix if it's allowed ![image](https://private-user-images.githubusercontent.com/31839126/390773136-030d305e-9474-43e0-b7fe-48d82ef93ca6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4MDc0ODgsIm5iZiI6MTczMjgwNzE4OCwicGF0aCI6Ii8zMTgzOTEyNi8zOTA3NzMxMzYtMDMwZDMwNWUtOTQ3NC00M2UwLWI3ZmUtNDhkODJlZjkzY2E2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI4VDE1MTk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmMzEzMTI5ZTUxYmM1NTEyYmU0ODBkYzIzZjNjZDM1M2JiMTgwOTA2MzNjY2Y2MzlhZmI5YjJhZjlkNjZlYTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qE2mpkncUxwHVUw_mz5UvmQAhH0QbLskCSiaGfQw8GQ) ![image](https://private-user-images.githubusercontent.com/31839126/390773333-5b4d21ce-8ea8-4ad2-bc77-466bc4130342.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4MDc0ODgsIm5iZiI6MTczMjgwNzE4OCwicGF0aCI6Ii8zMTgzOTEyNi8zOTA3NzMzMzMtNWI0ZDIxY2UtOGVhOC00YWQyLWJjNzctNDY2YmM0MTMwMzQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI4VDE1MTk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2MDNjYmM3ZDI4MDZiOTI1YmUwNDdiOTlkM2YyOThhNmI0ZDAzNjQxOGVkYjBlZTZjMDFkYzM3MDY5Mzc4NTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8M1LB7R9rnECTPaafgW0gIj4jpMg6hJqmPvNYJE2Bvc)
> 
> Kindly advice, thanks!

@bppdanto-t , thanks for your investigation and more insight on this.


> I've successfully added the toggle icon back and tested it locally. I can create the pull request for the fix if it's allowed !

That's amazing.
Then I think it's better to add this to top right side corner, for better visibility.

Hope this is not a massive change for you to pull it from bottom left to top right? 

Please go ahead with the PR.

**Comment by bppdanto-t** [comment]
@authorjapps Please help to review the PR. I moved the icon to the top right with the same style of the other element besides it. I attached the result in the PR as well.

**Comment by authorjapps** [comment]
Fixed.
This feature is in the version ==> `1.3.45` and later versions
