### ISSUE TITLE
LocalDateTimeSerializer to embrace nano seconds

### ISSUE THREAD

**Issue by officiallysameer** [authorjapps/zerocode#76]
@JsonSerialize(using = LocalDateTimeSerializer.class) 
- Amend this to generate or accept nano secs.
- Useful for load aka stress test reports in case loads are generated at same secs e.g. within 0(zero) second, you launch 5 to 10 users. 
There is no fine grain than nanoseconds in Java, so considere until the finest grain.

**Comment by authorjapps** [comment]
Not needed. Enough upto microsec.
Revive this only if you have a evidence based use case.
