### ISSUE TITLE
Wiki- Page for community about load runner usage with examples 

### ISSUE THREAD

**Issue by nirmalchandra** [authorjapps/zerocode#81]
- Create a Wiki page, provide the link from README file.
- Clearly define each properties, the theory/thought-process behind it.
- Provide examples of usage in the hello-world project or create a separate project/module
- Provide charts/graphs(not fancy ones) which will help to visualize the load issues(if any)
-List our RESTful and SOAP end point load test result with linear-graph and bar-graphs
- This will help the community to understand and anyone can integrate/reuse the test code easily.

**Comment by authorjapps** [comment]
Use this Issue Number(81) for general improvements on REDAME or Wiki pages(incl. load runner).
