### ISSUE TITLE
Grafana with auto throughput section

### ISSUE THREAD

**Issue by siddhagalaxy** [authorjapps/zerocode#89]
- First make request-timestamp and responseDelayMilliSec adjacent to each other for **load-run**
- Create a auto throughput section for **load** reports

**Comment by authorjapps** [comment]
Sounds interesting, but it will be better if we can bring up the time-series using Grafana.
With or without Prometheus. Without Prometheus, we can consider using a lightweight H2DB or a Postgres.
> It also provides plugin for JSON plugin and Simple JSON plugin. Explore both. See link:
https://grafana.com/plugins?type=datasource

**Comment by authorjapps** [comment]
Out of current scope.
