### ISSUE TITLE
Simple way to provide URL query parameters for GET requests as in for POST request

### ISSUE THREAD

**Issue by ruwanka** [authorjapps/zerocode#99]
@authorjapps Excited about this awesome project, I've ran into a scenario where it require to pass number of query parameters in url. Can't we have the support for GET requests as in [this POST example](https://github.com/authorjapps/zerocode/blob/75459c5f99d63f8c889da728f2b047182ade9b30/src/test/resources/03_test_one_multi_steps/02_test_single_flow_two_step.json). Please ignore if there is existing support, I couldn't find and unable to get my trial and error working.

sample json:
```
{
  "scenarioName": "A scenario which has huge number of url query parameters",
  "steps": [
    {
      "name": "get_user_details",
      "url": "/example",
      "operation": "GET",
      "request": {
        "queryParams": {
          "queryParam1": "...",
          "queryParam2": "...",
          "queryParam3": "...",
          "queryParam4": "...",
          "queryParam5": "..",
          "more": "..."
        }
      },
      "assertions": {
        "status": 200,
        "body": {
          "...": "...",
        }
      }
    }
  ]
}
```
otherwise url will be like `"url":"/examplequeryParam1=...&queryParam2=...&queryParam3=...&queryParam4=...&queryParam5=..."
`
which can grow more and become harder to grasp. Can't we have the support for this kind of scenario? Once get more familiar with the code I'd love to contribute. Thanks.

**Comment by authorjapps** [comment]
@ruwanka That's a nice feature. Thanks for raising this. This was already supported in the earlier versions. Yes, you can kindly contribute and fix this, if this is missed in the recent versions.
+ You can please raise a PR by forking the repo, please read the [CONTRIBUTING.md](https://github.com/authorjapps/zerocode/blob/master/CONTRIBUTING.md#how-to-contribute).
+ The code is pretty easy to change and test, once you become familiar.
+ Please go step by step. Please start with a unit test, then add an integration test, then a sample working code into the `hello-word repo` and finally a reference into the README file.

Initially I can help you to locate the code where this needs change/amendment(_if you need_).

**Comment by authorjapps** [comment]
@ruwanka , Can you please look at the `queryParams` code at the branch `ISS-99_query_params` and add some more tests to
> org.jsmart.zerocode.core.httpclient.utils.UrlQueryParamsUtilsTest
org.jsmart.zerocode.core.verification.queryparams.QueryParamVerifyTest

when you get chance please. Test scenarios could be
> - If no "queryParams" are present 
> - and You can think of any other scenarios

This will give some ideas into the framework in terms of how the query params are handled.

**Comment by authorjapps** [comment]
Version <version>1.2.5</version> has this feature now.
